// Code generated by chgo-rowgen; DO NOT EDIT.

package canonical

import (
	"net"

	"github.com/ClickHouse/ch-go/proto"
	"github.com/ethpandaops/xatu/pkg/consumoor/route"
	"github.com/ethpandaops/xatu/pkg/proto/xatu"
)

const canonicalBeaconBlockExecutionTransactionTableName route.TableName = "canonical_beacon_block_execution_transaction"

type canonicalBeaconBlockExecutionTransactionBatch struct {
	UpdatedDateTime                           proto.ColDateTime
	Slot                                      proto.ColUInt32
	SlotStartDateTime                         proto.ColDateTime
	Epoch                                     proto.ColUInt32
	EpochStartDateTime                        proto.ColDateTime
	BlockRoot                                 route.SafeColFixedStr
	BlockVersion                              proto.ColStr
	Position                                  proto.ColUInt32
	Hash                                      route.SafeColFixedStr
	From                                      route.SafeColFixedStr
	To                                        *proto.ColNullable[[]byte]
	Nonce                                     proto.ColUInt64
	GasPrice                                  proto.ColUInt128
	Gas                                       proto.ColUInt64
	GasTipCap                                 *proto.ColNullable[proto.UInt128]
	GasFeeCap                                 *proto.ColNullable[proto.UInt128]
	Value                                     proto.ColUInt128
	Type                                      proto.ColUInt8
	Size                                      proto.ColUInt32
	CallDataSize                              proto.ColUInt32
	BlobGas                                   *proto.ColNullable[uint64]
	BlobGasFeeCap                             *proto.ColNullable[proto.UInt128]
	BlobHashes                                *proto.ColArr[string]
	BlobSidecarsSize                          *proto.ColNullable[uint32]
	BlobSidecarsEmptySize                     *proto.ColNullable[uint32]
	MetaClientName                            proto.ColStr
	MetaClientID                              proto.ColStr
	MetaClientVersion                         proto.ColStr
	MetaClientImplementation                  proto.ColStr
	MetaClientOS                              proto.ColStr
	MetaClientIP                              *proto.ColNullable[proto.IPv6]
	MetaClientGeoCity                         proto.ColStr
	MetaClientGeoCountry                      proto.ColStr
	MetaClientGeoCountryCode                  proto.ColStr
	MetaClientGeoContinentCode                proto.ColStr
	MetaClientGeoLongitude                    *proto.ColNullable[float64]
	MetaClientGeoLatitude                     *proto.ColNullable[float64]
	MetaClientGeoAutonomousSystemNumber       *proto.ColNullable[uint32]
	MetaClientGeoAutonomousSystemOrganization *proto.ColNullable[string]
	MetaNetworkID                             proto.ColInt32
	MetaNetworkName                           proto.ColStr
	MetaConsensusVersion                      proto.ColStr
	MetaConsensusVersionMajor                 proto.ColStr
	MetaConsensusVersionMinor                 proto.ColStr
	MetaConsensusVersionPatch                 proto.ColStr
	MetaConsensusImplementation               proto.ColStr
	MetaLabels                                *proto.ColMap[string, string]
	rows                                      int
}

func newcanonicalBeaconBlockExecutionTransactionBatch() *canonicalBeaconBlockExecutionTransactionBatch {
	return &canonicalBeaconBlockExecutionTransactionBatch{
		BlockRoot:                           func() route.SafeColFixedStr { var c route.SafeColFixedStr; c.SetSize(66); return c }(),
		Hash:                                func() route.SafeColFixedStr { var c route.SafeColFixedStr; c.SetSize(66); return c }(),
		From:                                func() route.SafeColFixedStr { var c route.SafeColFixedStr; c.SetSize(42); return c }(),
		To:                                  route.NewNullableFixedStr(42),
		GasTipCap:                           new(proto.ColUInt128).Nullable(),
		GasFeeCap:                           new(proto.ColUInt128).Nullable(),
		BlobGas:                             new(proto.ColUInt64).Nullable(),
		BlobGasFeeCap:                       new(proto.ColUInt128).Nullable(),
		BlobHashes:                          proto.NewArray[string](new(proto.ColStr)),
		BlobSidecarsSize:                    new(proto.ColUInt32).Nullable(),
		BlobSidecarsEmptySize:               new(proto.ColUInt32).Nullable(),
		MetaClientIP:                        new(proto.ColIPv6).Nullable(),
		MetaClientGeoLongitude:              new(proto.ColFloat64).Nullable(),
		MetaClientGeoLatitude:               new(proto.ColFloat64).Nullable(),
		MetaClientGeoAutonomousSystemNumber: new(proto.ColUInt32).Nullable(),
		MetaClientGeoAutonomousSystemOrganization: new(proto.ColStr).Nullable(),
		MetaLabels: proto.NewMap[string, string](new(proto.ColStr), new(proto.ColStr)),
	}
}

func (b *canonicalBeaconBlockExecutionTransactionBatch) Rows() int {
	return b.rows
}

func (b *canonicalBeaconBlockExecutionTransactionBatch) appendMetadata(event *xatu.DecoratedEvent) {
	if event == nil || event.GetMeta() == nil {
		b.MetaClientName.Append("")
		b.MetaClientID.Append("")
		b.MetaClientVersion.Append("")
		b.MetaClientImplementation.Append("")
		b.MetaClientOS.Append("")
		b.MetaClientIP.Append(proto.Nullable[proto.IPv6]{})
		b.MetaClientGeoCity.Append("")
		b.MetaClientGeoCountry.Append("")
		b.MetaClientGeoCountryCode.Append("")
		b.MetaClientGeoContinentCode.Append("")
		b.MetaClientGeoLongitude.Append(proto.Nullable[float64]{})
		b.MetaClientGeoLatitude.Append(proto.Nullable[float64]{})
		b.MetaClientGeoAutonomousSystemNumber.Append(proto.Nullable[uint32]{})
		b.MetaClientGeoAutonomousSystemOrganization.Append(proto.Nullable[string]{})
		b.MetaNetworkID.Append(0)
		b.MetaNetworkName.Append("")
		b.MetaConsensusVersion.Append("")
		b.MetaConsensusVersionMajor.Append("")
		b.MetaConsensusVersionMinor.Append("")
		b.MetaConsensusVersionPatch.Append("")
		b.MetaConsensusImplementation.Append("")
		b.MetaLabels.Append(nil)
		return
	}

	b.MetaClientName.Append(event.GetMeta().GetClient().GetName())
	b.MetaClientID.Append(event.GetMeta().GetClient().GetId())
	b.MetaClientVersion.Append(event.GetMeta().GetClient().GetVersion())
	b.MetaClientImplementation.Append(event.GetMeta().GetClient().GetImplementation())
	b.MetaClientOS.Append(event.GetMeta().GetClient().GetOs())
	b.MetaClientIP.Append(proto.NewNullable[proto.IPv6](route.NormalizeIPToIPv6(event.GetMeta().GetServer().GetClient().GetIP())))
	b.MetaClientGeoCity.Append(event.GetMeta().GetServer().GetClient().GetGeo().GetCity())
	b.MetaClientGeoCountry.Append(event.GetMeta().GetServer().GetClient().GetGeo().GetCountry())
	b.MetaClientGeoCountryCode.Append(event.GetMeta().GetServer().GetClient().GetGeo().GetCountryCode())
	b.MetaClientGeoContinentCode.Append(event.GetMeta().GetServer().GetClient().GetGeo().GetContinentCode())
	b.MetaClientGeoLongitude.Append(proto.NewNullable[float64](event.GetMeta().GetServer().GetClient().GetGeo().GetLongitude()))
	b.MetaClientGeoLatitude.Append(proto.NewNullable[float64](event.GetMeta().GetServer().GetClient().GetGeo().GetLatitude()))
	b.MetaClientGeoAutonomousSystemNumber.Append(proto.NewNullable[uint32](event.GetMeta().GetServer().GetClient().GetGeo().GetAutonomousSystemNumber()))
	b.MetaClientGeoAutonomousSystemOrganization.Append(proto.NewNullable[string](event.GetMeta().GetServer().GetClient().GetGeo().GetAutonomousSystemOrganization()))
	b.MetaNetworkID.Append(int32(event.GetMeta().GetClient().GetEthereum().GetNetwork().GetId()))
	b.MetaNetworkName.Append(event.GetMeta().GetClient().GetEthereum().GetNetwork().GetName())
	b.MetaConsensusVersion.Append(route.NormalizeConsensusVersion(event.GetMeta().GetClient().GetEthereum().GetConsensus().GetVersion()))
	b.MetaConsensusVersionMajor.Append(route.ConsensusVersionMajor(event.GetMeta().GetClient().GetEthereum().GetConsensus().GetVersion()))
	b.MetaConsensusVersionMinor.Append(route.ConsensusVersionMinor(event.GetMeta().GetClient().GetEthereum().GetConsensus().GetVersion()))
	b.MetaConsensusVersionPatch.Append(route.ConsensusVersionPatch(event.GetMeta().GetClient().GetEthereum().GetConsensus().GetVersion()))
	b.MetaConsensusImplementation.Append(event.GetMeta().GetClient().GetEthereum().GetConsensus().GetImplementation())
	if labels := event.GetMeta().GetClient().GetLabels(); labels != nil {
		b.MetaLabels.Append(labels)
	} else {
		b.MetaLabels.Append(map[string]string{})
	}
}

func (b *canonicalBeaconBlockExecutionTransactionBatch) Input() proto.Input {
	return proto.Input{
		{Name: "updated_date_time", Data: &b.UpdatedDateTime},
		{Name: "slot", Data: &b.Slot},
		{Name: "slot_start_date_time", Data: &b.SlotStartDateTime},
		{Name: "epoch", Data: &b.Epoch},
		{Name: "epoch_start_date_time", Data: &b.EpochStartDateTime},
		{Name: "block_root", Data: &b.BlockRoot},
		{Name: "block_version", Data: &b.BlockVersion},
		{Name: "position", Data: &b.Position},
		{Name: "hash", Data: &b.Hash},
		{Name: "from", Data: &b.From},
		{Name: "to", Data: b.To},
		{Name: "nonce", Data: &b.Nonce},
		{Name: "gas_price", Data: &b.GasPrice},
		{Name: "gas", Data: &b.Gas},
		{Name: "gas_tip_cap", Data: b.GasTipCap},
		{Name: "gas_fee_cap", Data: b.GasFeeCap},
		{Name: "value", Data: &b.Value},
		{Name: "type", Data: &b.Type},
		{Name: "size", Data: &b.Size},
		{Name: "call_data_size", Data: &b.CallDataSize},
		{Name: "blob_gas", Data: b.BlobGas},
		{Name: "blob_gas_fee_cap", Data: b.BlobGasFeeCap},
		{Name: "blob_hashes", Data: b.BlobHashes},
		{Name: "blob_sidecars_size", Data: b.BlobSidecarsSize},
		{Name: "blob_sidecars_empty_size", Data: b.BlobSidecarsEmptySize},
		{Name: "meta_client_name", Data: &b.MetaClientName},
		{Name: "meta_client_id", Data: &b.MetaClientID},
		{Name: "meta_client_version", Data: &b.MetaClientVersion},
		{Name: "meta_client_implementation", Data: &b.MetaClientImplementation},
		{Name: "meta_client_os", Data: &b.MetaClientOS},
		{Name: "meta_client_ip", Data: b.MetaClientIP},
		{Name: "meta_client_geo_city", Data: &b.MetaClientGeoCity},
		{Name: "meta_client_geo_country", Data: &b.MetaClientGeoCountry},
		{Name: "meta_client_geo_country_code", Data: &b.MetaClientGeoCountryCode},
		{Name: "meta_client_geo_continent_code", Data: &b.MetaClientGeoContinentCode},
		{Name: "meta_client_geo_longitude", Data: b.MetaClientGeoLongitude},
		{Name: "meta_client_geo_latitude", Data: b.MetaClientGeoLatitude},
		{Name: "meta_client_geo_autonomous_system_number", Data: b.MetaClientGeoAutonomousSystemNumber},
		{Name: "meta_client_geo_autonomous_system_organization", Data: b.MetaClientGeoAutonomousSystemOrganization},
		{Name: "meta_network_id", Data: &b.MetaNetworkID},
		{Name: "meta_network_name", Data: &b.MetaNetworkName},
		{Name: "meta_consensus_version", Data: &b.MetaConsensusVersion},
		{Name: "meta_consensus_version_major", Data: &b.MetaConsensusVersionMajor},
		{Name: "meta_consensus_version_minor", Data: &b.MetaConsensusVersionMinor},
		{Name: "meta_consensus_version_patch", Data: &b.MetaConsensusVersionPatch},
		{Name: "meta_consensus_implementation", Data: &b.MetaConsensusImplementation},
		{Name: "meta_labels", Data: b.MetaLabels},
	}
}

func (b *canonicalBeaconBlockExecutionTransactionBatch) Reset() {
	b.UpdatedDateTime.Reset()
	b.Slot.Reset()
	b.SlotStartDateTime.Reset()
	b.Epoch.Reset()
	b.EpochStartDateTime.Reset()
	b.BlockRoot.Reset()
	b.BlockVersion.Reset()
	b.Position.Reset()
	b.Hash.Reset()
	b.From.Reset()
	b.To.Reset()
	b.Nonce.Reset()
	b.GasPrice.Reset()
	b.Gas.Reset()
	b.GasTipCap.Reset()
	b.GasFeeCap.Reset()
	b.Value.Reset()
	b.Type.Reset()
	b.Size.Reset()
	b.CallDataSize.Reset()
	b.BlobGas.Reset()
	b.BlobGasFeeCap.Reset()
	b.BlobHashes.Reset()
	b.BlobSidecarsSize.Reset()
	b.BlobSidecarsEmptySize.Reset()
	b.MetaClientName.Reset()
	b.MetaClientID.Reset()
	b.MetaClientVersion.Reset()
	b.MetaClientImplementation.Reset()
	b.MetaClientOS.Reset()
	b.MetaClientIP.Reset()
	b.MetaClientGeoCity.Reset()
	b.MetaClientGeoCountry.Reset()
	b.MetaClientGeoCountryCode.Reset()
	b.MetaClientGeoContinentCode.Reset()
	b.MetaClientGeoLongitude.Reset()
	b.MetaClientGeoLatitude.Reset()
	b.MetaClientGeoAutonomousSystemNumber.Reset()
	b.MetaClientGeoAutonomousSystemOrganization.Reset()
	b.MetaNetworkID.Reset()
	b.MetaNetworkName.Reset()
	b.MetaConsensusVersion.Reset()
	b.MetaConsensusVersionMajor.Reset()
	b.MetaConsensusVersionMinor.Reset()
	b.MetaConsensusVersionPatch.Reset()
	b.MetaConsensusImplementation.Reset()
	b.MetaLabels.Reset()
	b.rows = 0
}

func (b *canonicalBeaconBlockExecutionTransactionBatch) Snapshot() []map[string]any {
	n := b.rows
	out := make([]map[string]any, n)

	for i := 0; i < n; i++ {
		row := make(map[string]any, 47)
		row["updated_date_time"] = b.UpdatedDateTime.Row(i).Unix()
		row["slot"] = b.Slot.Row(i)
		row["slot_start_date_time"] = b.SlotStartDateTime.Row(i).Unix()
		row["epoch"] = b.Epoch.Row(i)
		row["epoch_start_date_time"] = b.EpochStartDateTime.Row(i).Unix()
		row["block_root"] = string(b.BlockRoot.Row(i))
		row["block_version"] = b.BlockVersion.Row(i)
		row["position"] = b.Position.Row(i)
		row["hash"] = string(b.Hash.Row(i))
		row["from"] = string(b.From.Row(i))
		if v := b.To.Row(i); v.Set {
			row["to"] = string(v.Value)
		} else {
			row["to"] = nil
		}
		row["nonce"] = b.Nonce.Row(i)
		row["gas_price"] = route.UInt128ToString(b.GasPrice.Row(i))
		row["gas"] = b.Gas.Row(i)
		if v := b.GasTipCap.Row(i); v.Set {
			row["gas_tip_cap"] = route.UInt128ToString(v.Value)
		} else {
			row["gas_tip_cap"] = nil
		}
		if v := b.GasFeeCap.Row(i); v.Set {
			row["gas_fee_cap"] = route.UInt128ToString(v.Value)
		} else {
			row["gas_fee_cap"] = nil
		}
		row["value"] = route.UInt128ToString(b.Value.Row(i))
		row["type"] = b.Type.Row(i)
		row["size"] = b.Size.Row(i)
		row["call_data_size"] = b.CallDataSize.Row(i)
		if v := b.BlobGas.Row(i); v.Set {
			row["blob_gas"] = v.Value
		} else {
			row["blob_gas"] = nil
		}
		if v := b.BlobGasFeeCap.Row(i); v.Set {
			row["blob_gas_fee_cap"] = route.UInt128ToString(v.Value)
		} else {
			row["blob_gas_fee_cap"] = nil
		}
		row["blob_hashes"] = b.BlobHashes.Row(i)
		if v := b.BlobSidecarsSize.Row(i); v.Set {
			row["blob_sidecars_size"] = v.Value
		} else {
			row["blob_sidecars_size"] = nil
		}
		if v := b.BlobSidecarsEmptySize.Row(i); v.Set {
			row["blob_sidecars_empty_size"] = v.Value
		} else {
			row["blob_sidecars_empty_size"] = nil
		}
		row["meta_client_name"] = b.MetaClientName.Row(i)
		row["meta_client_id"] = b.MetaClientID.Row(i)
		row["meta_client_version"] = b.MetaClientVersion.Row(i)
		row["meta_client_implementation"] = b.MetaClientImplementation.Row(i)
		row["meta_client_os"] = b.MetaClientOS.Row(i)
		if v := b.MetaClientIP.Row(i); v.Set {
			row["meta_client_ip"] = net.IP(v.Value[:]).String()
		} else {
			row["meta_client_ip"] = nil
		}
		row["meta_client_geo_city"] = b.MetaClientGeoCity.Row(i)
		row["meta_client_geo_country"] = b.MetaClientGeoCountry.Row(i)
		row["meta_client_geo_country_code"] = b.MetaClientGeoCountryCode.Row(i)
		row["meta_client_geo_continent_code"] = b.MetaClientGeoContinentCode.Row(i)
		if v := b.MetaClientGeoLongitude.Row(i); v.Set {
			row["meta_client_geo_longitude"] = v.Value
		} else {
			row["meta_client_geo_longitude"] = nil
		}
		if v := b.MetaClientGeoLatitude.Row(i); v.Set {
			row["meta_client_geo_latitude"] = v.Value
		} else {
			row["meta_client_geo_latitude"] = nil
		}
		if v := b.MetaClientGeoAutonomousSystemNumber.Row(i); v.Set {
			row["meta_client_geo_autonomous_system_number"] = v.Value
		} else {
			row["meta_client_geo_autonomous_system_number"] = nil
		}
		if v := b.MetaClientGeoAutonomousSystemOrganization.Row(i); v.Set {
			row["meta_client_geo_autonomous_system_organization"] = v.Value
		} else {
			row["meta_client_geo_autonomous_system_organization"] = nil
		}
		row["meta_network_id"] = b.MetaNetworkID.Row(i)
		row["meta_network_name"] = b.MetaNetworkName.Row(i)
		row["meta_consensus_version"] = b.MetaConsensusVersion.Row(i)
		row["meta_consensus_version_major"] = b.MetaConsensusVersionMajor.Row(i)
		row["meta_consensus_version_minor"] = b.MetaConsensusVersionMinor.Row(i)
		row["meta_consensus_version_patch"] = b.MetaConsensusVersionPatch.Row(i)
		row["meta_consensus_implementation"] = b.MetaConsensusImplementation.Row(i)
		row["meta_labels"] = b.MetaLabels.Row(i)
		out[i] = row
	}

	return out
}
