linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - decorder
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goheader
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - whitespace
    - wsl

run:
  issues-exit-code: 1
