project_name: xatu

before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: linux-amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    binary: xatu-{{.Version}}
    goos:
    - linux
    goarch: 
    - amd64
    ldflags:
      - -s -w -X github.com/ethpandaops/xatu/pkg/proto/xatu.Release={{.Tag}} -X github.com/ethpandaops/xatu/pkg/proto/xatu.GitCommit={{.ShortCommit}}
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: linux-arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    binary: xatu-{{.Version}}
    goos: 
    - linux
    goarch: 
    - arm64
    ldflags:
      - -s -w -X github.com/ethpandaops/xatu/pkg/proto/xatu.Release={{.Tag}} -X github.com/ethpandaops/xatu/pkg/proto/xatu.GitCommit={{.ShortCommit}}
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: windows-amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    binary: xatu-{{.Version}}
    goos:
    - windows
    goarch:
    - amd64
    ldflags:
      - -s -w -X github.com/ethpandaops/xatu/pkg/proto/xatu.Release={{.Tag}} -X github.com/ethpandaops/xatu/pkg/proto/xatu.GitCommit={{.ShortCommit}}
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: darwin-amd64
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    binary: xatu-{{.Version}}
    goos:
    - darwin
    goarch:
    - amd64
    ldflags:
      - -s -w -X github.com/ethpandaops/xatu/pkg/proto/xatu.Release={{.Tag}} -X github.com/ethpandaops/xatu/pkg/proto/xatu.GitCommit={{.ShortCommit}}
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: darwin-arm64
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    binary: xatu-{{.Version}}
    goos:
    - darwin
    goarch:
    - arm64
    ldflags:
      - -s -w -X github.com/ethpandaops/xatu/pkg/proto/xatu.Release={{.Tag}} -X github.com/ethpandaops/xatu/pkg/proto/xatu.GitCommit={{.ShortCommit}}
    mod_timestamp: "{{ .CommitTimestamp }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  ## Scratch
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: goreleaser-scratch.Dockerfile
    image_templates:
      - "ethpandaops/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ethpandaops/{{ .ProjectName }}:{{ if .Env.RELEASE_SUFFIX }}{{ .Env.RELEASE_SUFFIX }}-{{ end }}latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: goreleaser-scratch.Dockerfile
    image_templates:
      - "ethpandaops/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "ethpandaops/{{ .ProjectName }}:{{ if .Env.RELEASE_SUFFIX }}{{ .Env.RELEASE_SUFFIX }}-{{ end }}latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  ## Debian
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: goreleaser-debian.Dockerfile
    image_templates:
      - "ethpandaops/{{ .ProjectName }}:{{ .Version }}-debian-amd64"
      - "ethpandaops/{{ .ProjectName }}:{{ if .Env.RELEASE_SUFFIX }}{{ .Env.RELEASE_SUFFIX }}-{{ end }}debian-latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: goreleaser-debian.Dockerfile
    image_templates:
      - "ethpandaops/{{ .ProjectName }}:{{ .Version }}-debian-arm64v8"
      - "ethpandaops/{{ .ProjectName }}:{{ if .Env.RELEASE_SUFFIX }}{{ .Env.RELEASE_SUFFIX }}-{{ end }}debian-latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  ## Scratch
  - name_template: ethpandaops/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ethpandaops/{{ .ProjectName }}:{{ .Version }}-amd64
      - ethpandaops/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ethpandaops/{{ .ProjectName }}:{{ .Version }}-arm64
    image_templates:
      - ethpandaops/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ethpandaops/{{ .ProjectName }}:{{ if .Env.RELEASE_SUFFIX }}{{ .Env.RELEASE_SUFFIX }}-{{ end }}latest
    image_templates:
      - ethpandaops/{{ .ProjectName }}:{{ if .Env.RELEASE_SUFFIX }}{{ .Env.RELEASE_SUFFIX }}-{{ end }}latest-amd64
      - ethpandaops/{{ .ProjectName }}:{{ if .Env.RELEASE_SUFFIX }}{{ .Env.RELEASE_SUFFIX }}-{{ end }}latest-arm64v8

  ## Debian
  - name_template: ethpandaops/{{ .ProjectName }}:{{ .Version }}-debian
    image_templates:
      - ethpandaops/{{ .ProjectName }}:{{ .Version }}-debian-amd64
      - ethpandaops/{{ .ProjectName }}:{{ .Version }}-debian-arm64v8
  - name_template: ethpandaops/{{ .ProjectName }}:{{ .Version }}-debian-arm64
    image_templates:
      - ethpandaops/{{ .ProjectName }}:{{ .Version }}-debian-arm64v8
  - name_template: ethpandaops/{{ .ProjectName }}:{{ if .Env.RELEASE_SUFFIX }}{{ .Env.RELEASE_SUFFIX }}-{{ end }}debian-latest
    image_templates:
      - ethpandaops/{{ .ProjectName }}:{{ if .Env.RELEASE_SUFFIX }}{{ .Env.RELEASE_SUFFIX }}-{{ end }}debian-latest-amd64
      - ethpandaops/{{ .ProjectName }}:{{ if .Env.RELEASE_SUFFIX }}{{ .Env.RELEASE_SUFFIX }}-{{ end }}debian-latest-arm64v8
