apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://xatu-prometheus:9090

  - name: ClickHouse-official
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: default
      port: 9000
      server: xatu-clickhouse-01
      tlsSkipVerify: true
      username: readonly
    user: readonly
    secureJsonData:
      password: $CLICKHOUSE_USER_READONLY_PASSWORD

  - name: ClickHouse-vert
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://xatu-clickhouse-01:8123
    user: readonly
    jsonData:
      user: readonly
    secureJsonData:
      password: $CLICKHOUSE_USER_READONLY_PASSWORD
  - name: Tempo
    type: tempo
    access: proxy
    uid: EbPG8fYoz
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
