// Code generated by chgo-rowgen; DO NOT EDIT.

package execution

import (
	"net"

	"github.com/ClickHouse/ch-go/proto"
	"github.com/ethpandaops/xatu/pkg/consumoor/sinks/clickhouse/transform/flattener"
	"github.com/ethpandaops/xatu/pkg/consumoor/sinks/clickhouse/transform/metadata"
)

const executionStateSizeTableName flattener.TableName = "execution_state_size"

type executionStateSizeBatch struct {
	UpdatedDateTime                           proto.ColDateTime
	EventDateTime                             proto.ColDateTime64
	BlockNumber                               proto.ColUInt64
	StateRoot                                 flattener.SafeColFixedStr
	Accounts                                  proto.ColUInt64
	AccountBytes                              proto.ColUInt64
	AccountTrienodes                          proto.ColUInt64
	AccountTrienodeBytes                      proto.ColUInt64
	ContractCodes                             proto.ColUInt64
	ContractCodeBytes                         proto.ColUInt64
	Storages                                  proto.ColUInt64
	StorageBytes                              proto.ColUInt64
	StorageTrienodes                          proto.ColUInt64
	StorageTrienodeBytes                      proto.ColUInt64
	MetaClientName                            proto.ColStr
	MetaClientID                              proto.ColStr
	MetaClientVersion                         proto.ColStr
	MetaClientImplementation                  proto.ColStr
	MetaClientOS                              proto.ColStr
	MetaClientIP                              *proto.ColNullable[proto.IPv6]
	MetaClientGeoCity                         proto.ColStr
	MetaClientGeoCountry                      proto.ColStr
	MetaClientGeoCountryCode                  proto.ColStr
	MetaClientGeoContinentCode                proto.ColStr
	MetaClientGeoLongitude                    *proto.ColNullable[float64]
	MetaClientGeoLatitude                     *proto.ColNullable[float64]
	MetaClientGeoAutonomousSystemNumber       *proto.ColNullable[uint32]
	MetaClientGeoAutonomousSystemOrganization *proto.ColNullable[string]
	MetaNetworkID                             proto.ColInt32
	MetaNetworkName                           proto.ColStr
	MetaExecutionVersion                      proto.ColStr
	MetaExecutionVersionMajor                 proto.ColStr
	MetaExecutionVersionMinor                 proto.ColStr
	MetaExecutionVersionPatch                 proto.ColStr
	MetaExecutionImplementation               proto.ColStr
	MetaLabels                                *proto.ColMap[string, string]
	rows                                      int
}

func newexecutionStateSizeBatch() *executionStateSizeBatch {
	return &executionStateSizeBatch{
		EventDateTime:                             func() proto.ColDateTime64 { var c proto.ColDateTime64; c.WithPrecision(proto.Precision(3)); return c }(),
		StateRoot:                                 func() flattener.SafeColFixedStr { var c flattener.SafeColFixedStr; c.SetSize(66); return c }(),
		MetaClientIP:                              new(proto.ColIPv6).Nullable(),
		MetaClientGeoLongitude:                    new(proto.ColFloat64).Nullable(),
		MetaClientGeoLatitude:                     new(proto.ColFloat64).Nullable(),
		MetaClientGeoAutonomousSystemNumber:       new(proto.ColUInt32).Nullable(),
		MetaClientGeoAutonomousSystemOrganization: new(proto.ColStr).Nullable(),
		MetaLabels:                                proto.NewMap[string, string](new(proto.ColStr), new(proto.ColStr)),
	}
}

func (b *executionStateSizeBatch) Rows() int {
	return b.rows
}

func (b *executionStateSizeBatch) appendMetadata(meta *metadata.CommonMetadata) {
	if meta == nil {
		b.MetaClientName.Append("")
		b.MetaClientID.Append("")
		b.MetaClientVersion.Append("")
		b.MetaClientImplementation.Append("")
		b.MetaClientOS.Append("")
		b.MetaClientIP.Append(proto.Nullable[proto.IPv6]{})
		b.MetaClientGeoCity.Append("")
		b.MetaClientGeoCountry.Append("")
		b.MetaClientGeoCountryCode.Append("")
		b.MetaClientGeoContinentCode.Append("")
		b.MetaClientGeoLongitude.Append(proto.Nullable[float64]{})
		b.MetaClientGeoLatitude.Append(proto.Nullable[float64]{})
		b.MetaClientGeoAutonomousSystemNumber.Append(proto.Nullable[uint32]{})
		b.MetaClientGeoAutonomousSystemOrganization.Append(proto.Nullable[string]{})
		b.MetaNetworkID.Append(0)
		b.MetaNetworkName.Append("")
		b.MetaExecutionVersion.Append("")
		b.MetaExecutionVersionMajor.Append("")
		b.MetaExecutionVersionMinor.Append("")
		b.MetaExecutionVersionPatch.Append("")
		b.MetaExecutionImplementation.Append("")
		b.MetaLabels.Append(nil)
		return
	}

	b.MetaClientName.Append(meta.MetaClientName)
	b.MetaClientID.Append(meta.MetaClientID)
	b.MetaClientVersion.Append(meta.MetaClientVersion)
	b.MetaClientImplementation.Append(meta.MetaClientImplementation)
	b.MetaClientOS.Append(meta.MetaClientOS)
	b.MetaClientIP.Append(proto.NewNullable[proto.IPv6](flattener.ParseIPv6(meta.MetaClientIP)))
	b.MetaClientGeoCity.Append(meta.MetaClientGeoCity)
	b.MetaClientGeoCountry.Append(meta.MetaClientGeoCountry)
	b.MetaClientGeoCountryCode.Append(meta.MetaClientGeoCountryCode)
	b.MetaClientGeoContinentCode.Append(meta.MetaClientGeoContinentCode)
	b.MetaClientGeoLongitude.Append(proto.NewNullable[float64](meta.MetaClientGeoLongitude))
	b.MetaClientGeoLatitude.Append(proto.NewNullable[float64](meta.MetaClientGeoLatitude))
	b.MetaClientGeoAutonomousSystemNumber.Append(proto.NewNullable[uint32](meta.MetaClientGeoAutonomousSystemNumber))
	b.MetaClientGeoAutonomousSystemOrganization.Append(proto.NewNullable[string](meta.MetaClientGeoAutonomousSystemOrganization))
	b.MetaNetworkID.Append(int32(meta.MetaNetworkID))
	b.MetaNetworkName.Append(meta.MetaNetworkName)
	b.MetaExecutionVersion.Append(meta.MetaExecutionVersion)
	b.MetaExecutionVersionMajor.Append(meta.MetaExecutionVersionMajor)
	b.MetaExecutionVersionMinor.Append(meta.MetaExecutionVersionMinor)
	b.MetaExecutionVersionPatch.Append(meta.MetaExecutionVersionPatch)
	b.MetaExecutionImplementation.Append(meta.MetaExecutionImplementation)
	if meta.MetaLabels != nil {
		b.MetaLabels.Append(meta.MetaLabels)
	} else {
		b.MetaLabels.Append(map[string]string{})
	}
}

func (b *executionStateSizeBatch) Input() proto.Input {
	return proto.Input{
		{Name: "updated_date_time", Data: &b.UpdatedDateTime},
		{Name: "event_date_time", Data: &b.EventDateTime},
		{Name: "block_number", Data: &b.BlockNumber},
		{Name: "state_root", Data: &b.StateRoot},
		{Name: "accounts", Data: &b.Accounts},
		{Name: "account_bytes", Data: &b.AccountBytes},
		{Name: "account_trienodes", Data: &b.AccountTrienodes},
		{Name: "account_trienode_bytes", Data: &b.AccountTrienodeBytes},
		{Name: "contract_codes", Data: &b.ContractCodes},
		{Name: "contract_code_bytes", Data: &b.ContractCodeBytes},
		{Name: "storages", Data: &b.Storages},
		{Name: "storage_bytes", Data: &b.StorageBytes},
		{Name: "storage_trienodes", Data: &b.StorageTrienodes},
		{Name: "storage_trienode_bytes", Data: &b.StorageTrienodeBytes},
		{Name: "meta_client_name", Data: &b.MetaClientName},
		{Name: "meta_client_id", Data: &b.MetaClientID},
		{Name: "meta_client_version", Data: &b.MetaClientVersion},
		{Name: "meta_client_implementation", Data: &b.MetaClientImplementation},
		{Name: "meta_client_os", Data: &b.MetaClientOS},
		{Name: "meta_client_ip", Data: b.MetaClientIP},
		{Name: "meta_client_geo_city", Data: &b.MetaClientGeoCity},
		{Name: "meta_client_geo_country", Data: &b.MetaClientGeoCountry},
		{Name: "meta_client_geo_country_code", Data: &b.MetaClientGeoCountryCode},
		{Name: "meta_client_geo_continent_code", Data: &b.MetaClientGeoContinentCode},
		{Name: "meta_client_geo_longitude", Data: b.MetaClientGeoLongitude},
		{Name: "meta_client_geo_latitude", Data: b.MetaClientGeoLatitude},
		{Name: "meta_client_geo_autonomous_system_number", Data: b.MetaClientGeoAutonomousSystemNumber},
		{Name: "meta_client_geo_autonomous_system_organization", Data: b.MetaClientGeoAutonomousSystemOrganization},
		{Name: "meta_network_id", Data: &b.MetaNetworkID},
		{Name: "meta_network_name", Data: &b.MetaNetworkName},
		{Name: "meta_execution_version", Data: &b.MetaExecutionVersion},
		{Name: "meta_execution_version_major", Data: &b.MetaExecutionVersionMajor},
		{Name: "meta_execution_version_minor", Data: &b.MetaExecutionVersionMinor},
		{Name: "meta_execution_version_patch", Data: &b.MetaExecutionVersionPatch},
		{Name: "meta_execution_implementation", Data: &b.MetaExecutionImplementation},
		{Name: "meta_labels", Data: b.MetaLabels},
	}
}

func (b *executionStateSizeBatch) Reset() {
	b.UpdatedDateTime.Reset()
	b.EventDateTime.Reset()
	b.BlockNumber.Reset()
	b.StateRoot.Reset()
	b.Accounts.Reset()
	b.AccountBytes.Reset()
	b.AccountTrienodes.Reset()
	b.AccountTrienodeBytes.Reset()
	b.ContractCodes.Reset()
	b.ContractCodeBytes.Reset()
	b.Storages.Reset()
	b.StorageBytes.Reset()
	b.StorageTrienodes.Reset()
	b.StorageTrienodeBytes.Reset()
	b.MetaClientName.Reset()
	b.MetaClientID.Reset()
	b.MetaClientVersion.Reset()
	b.MetaClientImplementation.Reset()
	b.MetaClientOS.Reset()
	b.MetaClientIP.Reset()
	b.MetaClientGeoCity.Reset()
	b.MetaClientGeoCountry.Reset()
	b.MetaClientGeoCountryCode.Reset()
	b.MetaClientGeoContinentCode.Reset()
	b.MetaClientGeoLongitude.Reset()
	b.MetaClientGeoLatitude.Reset()
	b.MetaClientGeoAutonomousSystemNumber.Reset()
	b.MetaClientGeoAutonomousSystemOrganization.Reset()
	b.MetaNetworkID.Reset()
	b.MetaNetworkName.Reset()
	b.MetaExecutionVersion.Reset()
	b.MetaExecutionVersionMajor.Reset()
	b.MetaExecutionVersionMinor.Reset()
	b.MetaExecutionVersionPatch.Reset()
	b.MetaExecutionImplementation.Reset()
	b.MetaLabels.Reset()
	b.rows = 0
}

func (b *executionStateSizeBatch) Snapshot() []map[string]any {
	n := b.rows
	out := make([]map[string]any, n)

	for i := 0; i < n; i++ {
		row := make(map[string]any, 36)
		row["updated_date_time"] = b.UpdatedDateTime.Row(i).Unix()
		row["event_date_time"] = b.EventDateTime.Row(i).UnixMilli()
		row["block_number"] = b.BlockNumber.Row(i)
		row["state_root"] = string(b.StateRoot.Row(i))
		row["accounts"] = b.Accounts.Row(i)
		row["account_bytes"] = b.AccountBytes.Row(i)
		row["account_trienodes"] = b.AccountTrienodes.Row(i)
		row["account_trienode_bytes"] = b.AccountTrienodeBytes.Row(i)
		row["contract_codes"] = b.ContractCodes.Row(i)
		row["contract_code_bytes"] = b.ContractCodeBytes.Row(i)
		row["storages"] = b.Storages.Row(i)
		row["storage_bytes"] = b.StorageBytes.Row(i)
		row["storage_trienodes"] = b.StorageTrienodes.Row(i)
		row["storage_trienode_bytes"] = b.StorageTrienodeBytes.Row(i)
		row["meta_client_name"] = b.MetaClientName.Row(i)
		row["meta_client_id"] = b.MetaClientID.Row(i)
		row["meta_client_version"] = b.MetaClientVersion.Row(i)
		row["meta_client_implementation"] = b.MetaClientImplementation.Row(i)
		row["meta_client_os"] = b.MetaClientOS.Row(i)
		if v := b.MetaClientIP.Row(i); v.Set {
			row["meta_client_ip"] = net.IP(v.Value[:]).String()
		} else {
			row["meta_client_ip"] = nil
		}
		row["meta_client_geo_city"] = b.MetaClientGeoCity.Row(i)
		row["meta_client_geo_country"] = b.MetaClientGeoCountry.Row(i)
		row["meta_client_geo_country_code"] = b.MetaClientGeoCountryCode.Row(i)
		row["meta_client_geo_continent_code"] = b.MetaClientGeoContinentCode.Row(i)
		if v := b.MetaClientGeoLongitude.Row(i); v.Set {
			row["meta_client_geo_longitude"] = v.Value
		} else {
			row["meta_client_geo_longitude"] = nil
		}
		if v := b.MetaClientGeoLatitude.Row(i); v.Set {
			row["meta_client_geo_latitude"] = v.Value
		} else {
			row["meta_client_geo_latitude"] = nil
		}
		if v := b.MetaClientGeoAutonomousSystemNumber.Row(i); v.Set {
			row["meta_client_geo_autonomous_system_number"] = v.Value
		} else {
			row["meta_client_geo_autonomous_system_number"] = nil
		}
		if v := b.MetaClientGeoAutonomousSystemOrganization.Row(i); v.Set {
			row["meta_client_geo_autonomous_system_organization"] = v.Value
		} else {
			row["meta_client_geo_autonomous_system_organization"] = nil
		}
		row["meta_network_id"] = b.MetaNetworkID.Row(i)
		row["meta_network_name"] = b.MetaNetworkName.Row(i)
		row["meta_execution_version"] = b.MetaExecutionVersion.Row(i)
		row["meta_execution_version_major"] = b.MetaExecutionVersionMajor.Row(i)
		row["meta_execution_version_minor"] = b.MetaExecutionVersionMinor.Row(i)
		row["meta_execution_version_patch"] = b.MetaExecutionVersionPatch.Row(i)
		row["meta_execution_implementation"] = b.MetaExecutionImplementation.Row(i)
		row["meta_labels"] = b.MetaLabels.Row(i)
		out[i] = row
	}

	return out
}
