// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for block_native_mempool_transaction

package clickhouse

import (
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// BlockNativeMempoolTransactionRow is a ClickHouse-scannable result row for the block_native_mempool_transaction table.
// Field types match the SELECT column expressions produced by
// BuildListBlockNativeMempoolTransactionQuery and BuildGetBlockNativeMempoolTransactionQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type BlockNativeMempoolTransactionRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	Detecttime int64 `ch:"detecttime" json:"detecttime"`
	Hash *string `ch:"hash" json:"hash"`
	Status string `ch:"status" json:"status"`
	Region string `ch:"region" json:"region"`
	Reorg *string `ch:"reorg" json:"reorg"`
	Replace *string `ch:"replace" json:"replace"`
	Curblocknumber *uint64 `ch:"curblocknumber" json:"curblocknumber"`
	Failurereason *string `ch:"failurereason" json:"failurereason"`
	Blockspending *uint64 `ch:"blockspending" json:"blockspending"`
	Timepending *uint64 `ch:"timepending" json:"timepending"`
	Nonce uint64 `ch:"nonce" json:"nonce"`
	Gas uint64 `ch:"gas" json:"gas"`
	Gasprice string `ch:"gasprice" json:"gasprice"`
	Value string `ch:"value" json:"value"`
	Toaddress *string `ch:"toaddress" json:"toaddress"`
	Fromaddress *string `ch:"fromaddress" json:"fromaddress"`
	Datasize uint32 `ch:"datasize" json:"datasize"`
	Data4Bytes *string `ch:"data4bytes" json:"data4bytes"`
	Network string `ch:"network" json:"network"`
	Type uint32 `ch:"type" json:"type"`
	Maxpriorityfeepergas *string `ch:"maxpriorityfeepergas" json:"maxpriorityfeepergas"`
	Maxfeepergas *string `ch:"maxfeepergas" json:"maxfeepergas"`
	Basefeepergas *string `ch:"basefeepergas" json:"basefeepergas"`
	Dropreason *string `ch:"dropreason" json:"dropreason"`
	Rejectionreason *string `ch:"rejectionreason" json:"rejectionreason"`
	Stuck bool `ch:"stuck" json:"stuck"`
	Gasused *uint64 `ch:"gasused" json:"gasused"`
}

// TableName returns the ClickHouse table this row maps to.
func (BlockNativeMempoolTransactionRow) TableName() string {
	return "block_native_mempool_transaction"
}

// ToProto converts the row to its protobuf message.
func (r *BlockNativeMempoolTransactionRow) ToProto() *BlockNativeMempoolTransaction {
	p := &BlockNativeMempoolTransaction{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.Detecttime = r.Detecttime
	if r.Hash != nil {
		p.Hash = *r.Hash
	}
	p.Status = r.Status
	p.Region = r.Region
	if r.Reorg != nil {
		p.Reorg = wrapperspb.String(*r.Reorg)
	}
	if r.Replace != nil {
		p.Replace = wrapperspb.String(*r.Replace)
	}
	if r.Curblocknumber != nil {
		p.Curblocknumber = wrapperspb.UInt64(*r.Curblocknumber)
	}
	if r.Failurereason != nil {
		p.Failurereason = wrapperspb.String(*r.Failurereason)
	}
	if r.Blockspending != nil {
		p.Blockspending = wrapperspb.UInt64(*r.Blockspending)
	}
	if r.Timepending != nil {
		p.Timepending = wrapperspb.UInt64(*r.Timepending)
	}
	p.Nonce = r.Nonce
	p.Gas = r.Gas
	p.Gasprice = r.Gasprice
	p.Value = r.Value
	if r.Toaddress != nil {
		p.Toaddress = wrapperspb.String(*r.Toaddress)
	}
	if r.Fromaddress != nil {
		p.Fromaddress = *r.Fromaddress
	}
	p.Datasize = r.Datasize
	if r.Data4Bytes != nil {
		p.Data4Bytes = wrapperspb.String(*r.Data4Bytes)
	}
	p.Network = r.Network
	p.Type = r.Type
	if r.Maxpriorityfeepergas != nil {
		p.Maxpriorityfeepergas = wrapperspb.String(*r.Maxpriorityfeepergas)
	}
	if r.Maxfeepergas != nil {
		p.Maxfeepergas = wrapperspb.String(*r.Maxfeepergas)
	}
	if r.Basefeepergas != nil {
		p.Basefeepergas = wrapperspb.String(*r.Basefeepergas)
	}
	if r.Dropreason != nil {
		p.Dropreason = wrapperspb.String(*r.Dropreason)
	}
	if r.Rejectionreason != nil {
		p.Rejectionreason = wrapperspb.String(*r.Rejectionreason)
	}
	p.Stuck = r.Stuck
	if r.Gasused != nil {
		p.Gasused = wrapperspb.UInt64(*r.Gasused)
	}
	return p
}
