// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for canonical_beacon_block_access_list_summary

package clickhouse

import (
	"net"

	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// CanonicalBeaconBlockAccessListSummaryRow is a ClickHouse-scannable result row for the canonical_beacon_block_access_list_summary table.
// Field types match the SELECT column expressions produced by
// BuildListCanonicalBeaconBlockAccessListSummaryQuery and BuildGetCanonicalBeaconBlockAccessListSummaryQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type CanonicalBeaconBlockAccessListSummaryRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	Slot uint32 `ch:"slot" json:"slot"`
	SlotStartDateTime uint32 `ch:"slot_start_date_time" json:"slot_start_date_time"`
	Epoch uint32 `ch:"epoch" json:"epoch"`
	EpochStartDateTime uint32 `ch:"epoch_start_date_time" json:"epoch_start_date_time"`
	BlockRoot *string `ch:"block_root" json:"block_root"`
	BlockVersion string `ch:"block_version" json:"block_version"`
	BlockNumber uint64 `ch:"block_number" json:"block_number"`
	BlockHash *string `ch:"block_hash" json:"block_hash"`
	AccountsTouched uint32 `ch:"accounts_touched" json:"accounts_touched"`
	StorageSlotsChanged uint32 `ch:"storage_slots_changed" json:"storage_slots_changed"`
	StorageChanges uint32 `ch:"storage_changes" json:"storage_changes"`
	StorageReads uint32 `ch:"storage_reads" json:"storage_reads"`
	BalanceChanges uint32 `ch:"balance_changes" json:"balance_changes"`
	NonceChanges uint32 `ch:"nonce_changes" json:"nonce_changes"`
	CodeChanges uint32 `ch:"code_changes" json:"code_changes"`
	TotalChanges uint32 `ch:"total_changes" json:"total_changes"`
	BalSizeBytes uint32 `ch:"bal_size_bytes" json:"bal_size_bytes"`
	BalHash *string `ch:"bal_hash" json:"bal_hash"`
	MetaClientName string `ch:"meta_client_name" json:"meta_client_name"`
	MetaClientId string `ch:"meta_client_id" json:"meta_client_id"`
	MetaClientVersion string `ch:"meta_client_version" json:"meta_client_version"`
	MetaClientImplementation string `ch:"meta_client_implementation" json:"meta_client_implementation"`
	MetaClientOs string `ch:"meta_client_os" json:"meta_client_os"`
	MetaClientIp *net.IP `ch:"meta_client_ip" json:"meta_client_ip"`
	MetaClientGeoCity string `ch:"meta_client_geo_city" json:"meta_client_geo_city"`
	MetaClientGeoCountry string `ch:"meta_client_geo_country" json:"meta_client_geo_country"`
	MetaClientGeoCountryCode string `ch:"meta_client_geo_country_code" json:"meta_client_geo_country_code"`
	MetaClientGeoContinentCode string `ch:"meta_client_geo_continent_code" json:"meta_client_geo_continent_code"`
	MetaClientGeoLongitude *float64 `ch:"meta_client_geo_longitude" json:"meta_client_geo_longitude"`
	MetaClientGeoLatitude *float64 `ch:"meta_client_geo_latitude" json:"meta_client_geo_latitude"`
	MetaClientGeoAutonomousSystemNumber *uint32 `ch:"meta_client_geo_autonomous_system_number" json:"meta_client_geo_autonomous_system_number"`
	MetaClientGeoAutonomousSystemOrganization *string `ch:"meta_client_geo_autonomous_system_organization" json:"meta_client_geo_autonomous_system_organization"`
	MetaNetworkId int32 `ch:"meta_network_id" json:"meta_network_id"`
	MetaNetworkName string `ch:"meta_network_name" json:"meta_network_name"`
	MetaConsensusVersion string `ch:"meta_consensus_version" json:"meta_consensus_version"`
	MetaConsensusVersionMajor string `ch:"meta_consensus_version_major" json:"meta_consensus_version_major"`
	MetaConsensusVersionMinor string `ch:"meta_consensus_version_minor" json:"meta_consensus_version_minor"`
	MetaConsensusVersionPatch string `ch:"meta_consensus_version_patch" json:"meta_consensus_version_patch"`
	MetaConsensusImplementation string `ch:"meta_consensus_implementation" json:"meta_consensus_implementation"`
	MetaLabels map[string]string `ch:"meta_labels" json:"meta_labels"`
}

// TableName returns the ClickHouse table this row maps to.
func (CanonicalBeaconBlockAccessListSummaryRow) TableName() string {
	return "canonical_beacon_block_access_list_summary"
}

// ToProto converts the row to its protobuf message.
func (r *CanonicalBeaconBlockAccessListSummaryRow) ToProto() *CanonicalBeaconBlockAccessListSummary {
	p := &CanonicalBeaconBlockAccessListSummary{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.Slot = r.Slot
	p.SlotStartDateTime = r.SlotStartDateTime
	p.Epoch = r.Epoch
	p.EpochStartDateTime = r.EpochStartDateTime
	if r.BlockRoot != nil {
		p.BlockRoot = *r.BlockRoot
	}
	p.BlockVersion = r.BlockVersion
	p.BlockNumber = r.BlockNumber
	if r.BlockHash != nil {
		p.BlockHash = *r.BlockHash
	}
	p.AccountsTouched = r.AccountsTouched
	p.StorageSlotsChanged = r.StorageSlotsChanged
	p.StorageChanges = r.StorageChanges
	p.StorageReads = r.StorageReads
	p.BalanceChanges = r.BalanceChanges
	p.NonceChanges = r.NonceChanges
	p.CodeChanges = r.CodeChanges
	p.TotalChanges = r.TotalChanges
	p.BalSizeBytes = r.BalSizeBytes
	if r.BalHash != nil {
		p.BalHash = *r.BalHash
	}
	p.MetaClientName = r.MetaClientName
	p.MetaClientId = r.MetaClientId
	p.MetaClientVersion = r.MetaClientVersion
	p.MetaClientImplementation = r.MetaClientImplementation
	p.MetaClientOs = r.MetaClientOs
	if r.MetaClientIp != nil {
		p.MetaClientIp = wrapperspb.String(r.MetaClientIp.String())
	}
	p.MetaClientGeoCity = r.MetaClientGeoCity
	p.MetaClientGeoCountry = r.MetaClientGeoCountry
	p.MetaClientGeoCountryCode = r.MetaClientGeoCountryCode
	p.MetaClientGeoContinentCode = r.MetaClientGeoContinentCode
	if r.MetaClientGeoLongitude != nil {
		p.MetaClientGeoLongitude = wrapperspb.Double(*r.MetaClientGeoLongitude)
	}
	if r.MetaClientGeoLatitude != nil {
		p.MetaClientGeoLatitude = wrapperspb.Double(*r.MetaClientGeoLatitude)
	}
	if r.MetaClientGeoAutonomousSystemNumber != nil {
		p.MetaClientGeoAutonomousSystemNumber = wrapperspb.UInt32(*r.MetaClientGeoAutonomousSystemNumber)
	}
	if r.MetaClientGeoAutonomousSystemOrganization != nil {
		p.MetaClientGeoAutonomousSystemOrganization = wrapperspb.String(*r.MetaClientGeoAutonomousSystemOrganization)
	}
	p.MetaNetworkId = r.MetaNetworkId
	p.MetaNetworkName = r.MetaNetworkName
	p.MetaConsensusVersion = r.MetaConsensusVersion
	p.MetaConsensusVersionMajor = r.MetaConsensusVersionMajor
	p.MetaConsensusVersionMinor = r.MetaConsensusVersionMinor
	p.MetaConsensusVersionPatch = r.MetaConsensusVersionPatch
	p.MetaConsensusImplementation = r.MetaConsensusImplementation
	p.MetaLabels = r.MetaLabels
	return p
}
