// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for canonical_beacon_validators

package clickhouse

import (
	"fmt"
)

// BuildListCanonicalBeaconValidatorsQuery constructs a parameterized SQL query from a ListCanonicalBeaconValidatorsRequest
func BuildListCanonicalBeaconValidatorsQuery(req *ListCanonicalBeaconValidatorsRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.MetaNetworkName == nil {
		return SQLQuery{}, fmt.Errorf("primary key field meta_network_name is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.MetaNetworkName.Filter.(type) {
	case *StringFilter_Eq:
		qb.AddCondition("meta_network_name", "=", filter.Eq)
	case *StringFilter_Ne:
		qb.AddCondition("meta_network_name", "!=", filter.Ne)
	case *StringFilter_Contains:
		qb.AddLikeCondition("meta_network_name", "%" + filter.Contains + "%")
	case *StringFilter_StartsWith:
		qb.AddLikeCondition("meta_network_name", filter.StartsWith + "%")
	case *StringFilter_EndsWith:
		qb.AddLikeCondition("meta_network_name", "%" + filter.EndsWith)
	case *StringFilter_Like:
		qb.AddLikeCondition("meta_network_name", filter.Like)
	case *StringFilter_NotLike:
		qb.AddNotLikeCondition("meta_network_name", filter.NotLike)
	case *StringFilter_In:
		if len(filter.In.Values) > 0 {
			qb.AddInCondition("meta_network_name", StringSliceToInterface(filter.In.Values))
		}
	case *StringFilter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			qb.AddNotInCondition("meta_network_name", StringSliceToInterface(filter.NotIn.Values))
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: epoch
	if req.Epoch != nil {
		switch filter := req.Epoch.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("epoch", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("epoch", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("epoch", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("epoch", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("epoch", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("epoch", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("epoch", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("epoch", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("epoch", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: epoch_start_date_time
	if req.EpochStartDateTime != nil {
		switch filter := req.EpochStartDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("epoch_start_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("epoch_start_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("epoch_start_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("epoch_start_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("epoch_start_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("epoch_start_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("epoch_start_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("epoch_start_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("epoch_start_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: index
	if req.Index != nil {
		switch filter := req.Index.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("index", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("index", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("index", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("index", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("index", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("index", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("index", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("index", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("index", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: balance
	if req.Balance != nil {
		switch filter := req.Balance.Filter.(type) {
		case *NullableUInt64Filter_Eq:
			qb.AddCondition("balance", "=", filter.Eq)
		case *NullableUInt64Filter_Ne:
			qb.AddCondition("balance", "!=", filter.Ne)
		case *NullableUInt64Filter_Lt:
			qb.AddCondition("balance", "<", filter.Lt)
		case *NullableUInt64Filter_Lte:
			qb.AddCondition("balance", "<=", filter.Lte)
		case *NullableUInt64Filter_Gt:
			qb.AddCondition("balance", ">", filter.Gt)
		case *NullableUInt64Filter_Gte:
			qb.AddCondition("balance", ">=", filter.Gte)
		case *NullableUInt64Filter_Between:
			qb.AddBetweenCondition("balance", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("balance", UInt64SliceToInterface(filter.In.Values))
			}
		case *NullableUInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("balance", UInt64SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt64Filter_IsNull:
			qb.AddIsNullCondition("balance")
		case *NullableUInt64Filter_IsNotNull:
			qb.AddIsNotNullCondition("balance")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: status
	if req.Status != nil {
		switch filter := req.Status.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("status", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("status", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("status", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("status", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("status", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("status", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("status", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("status", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("status", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: effective_balance
	if req.EffectiveBalance != nil {
		switch filter := req.EffectiveBalance.Filter.(type) {
		case *NullableUInt64Filter_Eq:
			qb.AddCondition("effective_balance", "=", filter.Eq)
		case *NullableUInt64Filter_Ne:
			qb.AddCondition("effective_balance", "!=", filter.Ne)
		case *NullableUInt64Filter_Lt:
			qb.AddCondition("effective_balance", "<", filter.Lt)
		case *NullableUInt64Filter_Lte:
			qb.AddCondition("effective_balance", "<=", filter.Lte)
		case *NullableUInt64Filter_Gt:
			qb.AddCondition("effective_balance", ">", filter.Gt)
		case *NullableUInt64Filter_Gte:
			qb.AddCondition("effective_balance", ">=", filter.Gte)
		case *NullableUInt64Filter_Between:
			qb.AddBetweenCondition("effective_balance", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("effective_balance", UInt64SliceToInterface(filter.In.Values))
			}
		case *NullableUInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("effective_balance", UInt64SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt64Filter_IsNull:
			qb.AddIsNullCondition("effective_balance")
		case *NullableUInt64Filter_IsNotNull:
			qb.AddIsNotNullCondition("effective_balance")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: slashed
	if req.Slashed != nil {
		switch filter := req.Slashed.Filter.(type) {
		case *BoolFilter_Eq:
			qb.AddCondition("slashed", "=", filter.Eq)
		case *BoolFilter_Ne:
			qb.AddCondition("slashed", "!=", filter.Ne)
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: activation_epoch
	if req.ActivationEpoch != nil {
		switch filter := req.ActivationEpoch.Filter.(type) {
		case *NullableUInt64Filter_Eq:
			qb.AddCondition("activation_epoch", "=", filter.Eq)
		case *NullableUInt64Filter_Ne:
			qb.AddCondition("activation_epoch", "!=", filter.Ne)
		case *NullableUInt64Filter_Lt:
			qb.AddCondition("activation_epoch", "<", filter.Lt)
		case *NullableUInt64Filter_Lte:
			qb.AddCondition("activation_epoch", "<=", filter.Lte)
		case *NullableUInt64Filter_Gt:
			qb.AddCondition("activation_epoch", ">", filter.Gt)
		case *NullableUInt64Filter_Gte:
			qb.AddCondition("activation_epoch", ">=", filter.Gte)
		case *NullableUInt64Filter_Between:
			qb.AddBetweenCondition("activation_epoch", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("activation_epoch", UInt64SliceToInterface(filter.In.Values))
			}
		case *NullableUInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("activation_epoch", UInt64SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt64Filter_IsNull:
			qb.AddIsNullCondition("activation_epoch")
		case *NullableUInt64Filter_IsNotNull:
			qb.AddIsNotNullCondition("activation_epoch")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: activation_eligibility_epoch
	if req.ActivationEligibilityEpoch != nil {
		switch filter := req.ActivationEligibilityEpoch.Filter.(type) {
		case *NullableUInt64Filter_Eq:
			qb.AddCondition("activation_eligibility_epoch", "=", filter.Eq)
		case *NullableUInt64Filter_Ne:
			qb.AddCondition("activation_eligibility_epoch", "!=", filter.Ne)
		case *NullableUInt64Filter_Lt:
			qb.AddCondition("activation_eligibility_epoch", "<", filter.Lt)
		case *NullableUInt64Filter_Lte:
			qb.AddCondition("activation_eligibility_epoch", "<=", filter.Lte)
		case *NullableUInt64Filter_Gt:
			qb.AddCondition("activation_eligibility_epoch", ">", filter.Gt)
		case *NullableUInt64Filter_Gte:
			qb.AddCondition("activation_eligibility_epoch", ">=", filter.Gte)
		case *NullableUInt64Filter_Between:
			qb.AddBetweenCondition("activation_eligibility_epoch", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("activation_eligibility_epoch", UInt64SliceToInterface(filter.In.Values))
			}
		case *NullableUInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("activation_eligibility_epoch", UInt64SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt64Filter_IsNull:
			qb.AddIsNullCondition("activation_eligibility_epoch")
		case *NullableUInt64Filter_IsNotNull:
			qb.AddIsNotNullCondition("activation_eligibility_epoch")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: exit_epoch
	if req.ExitEpoch != nil {
		switch filter := req.ExitEpoch.Filter.(type) {
		case *NullableUInt64Filter_Eq:
			qb.AddCondition("exit_epoch", "=", filter.Eq)
		case *NullableUInt64Filter_Ne:
			qb.AddCondition("exit_epoch", "!=", filter.Ne)
		case *NullableUInt64Filter_Lt:
			qb.AddCondition("exit_epoch", "<", filter.Lt)
		case *NullableUInt64Filter_Lte:
			qb.AddCondition("exit_epoch", "<=", filter.Lte)
		case *NullableUInt64Filter_Gt:
			qb.AddCondition("exit_epoch", ">", filter.Gt)
		case *NullableUInt64Filter_Gte:
			qb.AddCondition("exit_epoch", ">=", filter.Gte)
		case *NullableUInt64Filter_Between:
			qb.AddBetweenCondition("exit_epoch", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("exit_epoch", UInt64SliceToInterface(filter.In.Values))
			}
		case *NullableUInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("exit_epoch", UInt64SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt64Filter_IsNull:
			qb.AddIsNullCondition("exit_epoch")
		case *NullableUInt64Filter_IsNotNull:
			qb.AddIsNotNullCondition("exit_epoch")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: withdrawable_epoch
	if req.WithdrawableEpoch != nil {
		switch filter := req.WithdrawableEpoch.Filter.(type) {
		case *NullableUInt64Filter_Eq:
			qb.AddCondition("withdrawable_epoch", "=", filter.Eq)
		case *NullableUInt64Filter_Ne:
			qb.AddCondition("withdrawable_epoch", "!=", filter.Ne)
		case *NullableUInt64Filter_Lt:
			qb.AddCondition("withdrawable_epoch", "<", filter.Lt)
		case *NullableUInt64Filter_Lte:
			qb.AddCondition("withdrawable_epoch", "<=", filter.Lte)
		case *NullableUInt64Filter_Gt:
			qb.AddCondition("withdrawable_epoch", ">", filter.Gt)
		case *NullableUInt64Filter_Gte:
			qb.AddCondition("withdrawable_epoch", ">=", filter.Gte)
		case *NullableUInt64Filter_Between:
			qb.AddBetweenCondition("withdrawable_epoch", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("withdrawable_epoch", UInt64SliceToInterface(filter.In.Values))
			}
		case *NullableUInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("withdrawable_epoch", UInt64SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt64Filter_IsNull:
			qb.AddIsNullCondition("withdrawable_epoch")
		case *NullableUInt64Filter_IsNotNull:
			qb.AddIsNotNullCondition("withdrawable_epoch")
		default:
			// Unsupported filter type
		}
	}

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "epoch", "epoch_start_date_time", "index", "balance", "status", "effective_balance", "slashed", "activation_epoch", "activation_eligibility_epoch", "exit_epoch", "withdrawable_epoch", "meta_network_name"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY meta_network_name" + ", epoch_start_date_time" + ", index" + ", status"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "epoch", "toUnixTimestamp(`epoch_start_date_time`) AS `epoch_start_date_time`", "index", "balance", "status", "effective_balance", "slashed", "activation_epoch", "activation_eligibility_epoch", "exit_epoch", "withdrawable_epoch", "meta_network_name"}

	return BuildParameterizedQuery("canonical_beacon_validators", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetCanonicalBeaconValidatorsQuery constructs a parameterized SQL query from a GetCanonicalBeaconValidatorsRequest
func BuildGetCanonicalBeaconValidatorsQuery(req *GetCanonicalBeaconValidatorsRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.MetaNetworkName == "" {
		return SQLQuery{}, fmt.Errorf("primary key field meta_network_name is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("meta_network_name", "=", req.MetaNetworkName)

	// Build ORDER BY clause
	orderByClause := " ORDER BY meta_network_name, epoch_start_date_time, index, status"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "epoch", "toUnixTimestamp(`epoch_start_date_time`) AS `epoch_start_date_time`", "index", "balance", "status", "effective_balance", "slashed", "activation_epoch", "activation_eligibility_epoch", "exit_epoch", "withdrawable_epoch", "meta_network_name"}

	// Return single record
	return BuildParameterizedQuery("canonical_beacon_validators", columns, qb, orderByClause, 1, 0, options...)
}
