// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for canonical_beacon_proposer_duty

package clickhouse

// CanonicalBeaconProposerDutyRow is a ClickHouse-scannable result row for the canonical_beacon_proposer_duty table.
// Field types match the SELECT column expressions produced by
// BuildListCanonicalBeaconProposerDutyQuery and BuildGetCanonicalBeaconProposerDutyQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type CanonicalBeaconProposerDutyRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	Slot uint32 `ch:"slot" json:"slot"`
	SlotStartDateTime uint32 `ch:"slot_start_date_time" json:"slot_start_date_time"`
	Epoch uint32 `ch:"epoch" json:"epoch"`
	EpochStartDateTime uint32 `ch:"epoch_start_date_time" json:"epoch_start_date_time"`
	ProposerValidatorIndex uint32 `ch:"proposer_validator_index" json:"proposer_validator_index"`
	ProposerPubkey string `ch:"proposer_pubkey" json:"proposer_pubkey"`
	MetaNetworkName string `ch:"meta_network_name" json:"meta_network_name"`
}

// TableName returns the ClickHouse table this row maps to.
func (CanonicalBeaconProposerDutyRow) TableName() string {
	return "canonical_beacon_proposer_duty"
}

// ToProto converts the row to its protobuf message.
func (r *CanonicalBeaconProposerDutyRow) ToProto() *CanonicalBeaconProposerDuty {
	p := &CanonicalBeaconProposerDuty{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.Slot = r.Slot
	p.SlotStartDateTime = r.SlotStartDateTime
	p.Epoch = r.Epoch
	p.EpochStartDateTime = r.EpochStartDateTime
	p.ProposerValidatorIndex = r.ProposerValidatorIndex
	p.ProposerPubkey = r.ProposerPubkey
	p.MetaNetworkName = r.MetaNetworkName
	return p
}
