// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for canonical_execution_transaction

package clickhouse

import (
	"fmt"
)

// BuildListCanonicalExecutionTransactionQuery constructs a parameterized SQL query from a ListCanonicalExecutionTransactionRequest
func BuildListCanonicalExecutionTransactionQuery(req *ListCanonicalExecutionTransactionRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.MetaNetworkName == nil {
		return SQLQuery{}, fmt.Errorf("primary key field meta_network_name is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.MetaNetworkName.Filter.(type) {
	case *StringFilter_Eq:
		qb.AddCondition("meta_network_name", "=", filter.Eq)
	case *StringFilter_Ne:
		qb.AddCondition("meta_network_name", "!=", filter.Ne)
	case *StringFilter_Contains:
		qb.AddLikeCondition("meta_network_name", "%" + filter.Contains + "%")
	case *StringFilter_StartsWith:
		qb.AddLikeCondition("meta_network_name", filter.StartsWith + "%")
	case *StringFilter_EndsWith:
		qb.AddLikeCondition("meta_network_name", "%" + filter.EndsWith)
	case *StringFilter_Like:
		qb.AddLikeCondition("meta_network_name", filter.Like)
	case *StringFilter_NotLike:
		qb.AddNotLikeCondition("meta_network_name", filter.NotLike)
	case *StringFilter_In:
		if len(filter.In.Values) > 0 {
			qb.AddInCondition("meta_network_name", StringSliceToInterface(filter.In.Values))
		}
	case *StringFilter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			qb.AddNotInCondition("meta_network_name", StringSliceToInterface(filter.NotIn.Values))
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: block_number
	if req.BlockNumber != nil {
		switch filter := req.BlockNumber.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("block_number", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("block_number", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("block_number", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("block_number", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("block_number", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("block_number", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("block_number", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("block_number", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("block_number", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: transaction_index
	if req.TransactionIndex != nil {
		switch filter := req.TransactionIndex.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("transaction_index", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("transaction_index", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("transaction_index", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("transaction_index", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("transaction_index", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("transaction_index", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("transaction_index", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("transaction_index", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("transaction_index", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: transaction_hash
	if req.TransactionHash != nil {
		switch filter := req.TransactionHash.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("transaction_hash", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("transaction_hash", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("transaction_hash", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("transaction_hash", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("transaction_hash", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("transaction_hash", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("transaction_hash", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("transaction_hash", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("transaction_hash", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: nonce
	if req.Nonce != nil {
		switch filter := req.Nonce.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("nonce", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("nonce", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("nonce", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("nonce", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("nonce", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("nonce", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("nonce", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("nonce", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("nonce", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: from_address
	if req.FromAddress != nil {
		switch filter := req.FromAddress.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("from_address", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("from_address", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("from_address", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("from_address", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("from_address", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("from_address", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("from_address", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("from_address", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("from_address", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: to_address
	if req.ToAddress != nil {
		switch filter := req.ToAddress.Filter.(type) {
		case *NullableStringFilter_Eq:
			qb.AddCondition("to_address", "=", filter.Eq)
		case *NullableStringFilter_Ne:
			qb.AddCondition("to_address", "!=", filter.Ne)
		case *NullableStringFilter_Contains:
			qb.AddLikeCondition("to_address", "%" + filter.Contains + "%")
		case *NullableStringFilter_StartsWith:
			qb.AddLikeCondition("to_address", filter.StartsWith + "%")
		case *NullableStringFilter_EndsWith:
			qb.AddLikeCondition("to_address", "%" + filter.EndsWith)
		case *NullableStringFilter_Like:
			qb.AddLikeCondition("to_address", filter.Like)
		case *NullableStringFilter_NotLike:
			qb.AddNotLikeCondition("to_address", filter.NotLike)
		case *NullableStringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("to_address", StringSliceToInterface(filter.In.Values))
			}
		case *NullableStringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("to_address", StringSliceToInterface(filter.NotIn.Values))
			}
		case *NullableStringFilter_IsNull:
			qb.AddIsNullCondition("to_address")
		case *NullableStringFilter_IsNotNull:
			qb.AddIsNotNullCondition("to_address")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: value
	if req.Value != nil {
		switch filter := req.Value.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("value", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("value", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("value", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("value", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("value", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("value", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("value", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("value", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("value", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: input
	if req.Input != nil {
		switch filter := req.Input.Filter.(type) {
		case *NullableStringFilter_Eq:
			qb.AddCondition("input", "=", filter.Eq)
		case *NullableStringFilter_Ne:
			qb.AddCondition("input", "!=", filter.Ne)
		case *NullableStringFilter_Contains:
			qb.AddLikeCondition("input", "%" + filter.Contains + "%")
		case *NullableStringFilter_StartsWith:
			qb.AddLikeCondition("input", filter.StartsWith + "%")
		case *NullableStringFilter_EndsWith:
			qb.AddLikeCondition("input", "%" + filter.EndsWith)
		case *NullableStringFilter_Like:
			qb.AddLikeCondition("input", filter.Like)
		case *NullableStringFilter_NotLike:
			qb.AddNotLikeCondition("input", filter.NotLike)
		case *NullableStringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("input", StringSliceToInterface(filter.In.Values))
			}
		case *NullableStringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("input", StringSliceToInterface(filter.NotIn.Values))
			}
		case *NullableStringFilter_IsNull:
			qb.AddIsNullCondition("input")
		case *NullableStringFilter_IsNotNull:
			qb.AddIsNotNullCondition("input")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: gas_limit
	if req.GasLimit != nil {
		switch filter := req.GasLimit.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("gas_limit", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("gas_limit", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("gas_limit", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("gas_limit", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("gas_limit", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("gas_limit", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("gas_limit", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("gas_limit", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("gas_limit", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: gas_used
	if req.GasUsed != nil {
		switch filter := req.GasUsed.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("gas_used", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("gas_used", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("gas_used", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("gas_used", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("gas_used", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("gas_used", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("gas_used", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("gas_used", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("gas_used", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: gas_price
	if req.GasPrice != nil {
		switch filter := req.GasPrice.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("gas_price", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("gas_price", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("gas_price", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("gas_price", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("gas_price", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("gas_price", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("gas_price", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("gas_price", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("gas_price", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: transaction_type
	if req.TransactionType != nil {
		switch filter := req.TransactionType.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("transaction_type", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("transaction_type", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("transaction_type", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("transaction_type", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("transaction_type", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("transaction_type", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("transaction_type", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("transaction_type", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("transaction_type", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: max_priority_fee_per_gas
	if req.MaxPriorityFeePerGas != nil {
		switch filter := req.MaxPriorityFeePerGas.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("max_priority_fee_per_gas", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("max_priority_fee_per_gas", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("max_priority_fee_per_gas", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("max_priority_fee_per_gas", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("max_priority_fee_per_gas", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("max_priority_fee_per_gas", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("max_priority_fee_per_gas", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("max_priority_fee_per_gas", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("max_priority_fee_per_gas", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: max_fee_per_gas
	if req.MaxFeePerGas != nil {
		switch filter := req.MaxFeePerGas.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("max_fee_per_gas", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("max_fee_per_gas", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("max_fee_per_gas", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("max_fee_per_gas", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("max_fee_per_gas", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("max_fee_per_gas", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("max_fee_per_gas", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("max_fee_per_gas", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("max_fee_per_gas", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: success
	if req.Success != nil {
		switch filter := req.Success.Filter.(type) {
		case *BoolFilter_Eq:
			qb.AddCondition("success", "=", filter.Eq)
		case *BoolFilter_Ne:
			qb.AddCondition("success", "!=", filter.Ne)
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: n_input_bytes
	if req.NInputBytes != nil {
		switch filter := req.NInputBytes.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("n_input_bytes", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("n_input_bytes", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("n_input_bytes", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("n_input_bytes", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("n_input_bytes", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("n_input_bytes", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("n_input_bytes", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("n_input_bytes", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("n_input_bytes", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: n_input_zero_bytes
	if req.NInputZeroBytes != nil {
		switch filter := req.NInputZeroBytes.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("n_input_zero_bytes", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("n_input_zero_bytes", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("n_input_zero_bytes", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("n_input_zero_bytes", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("n_input_zero_bytes", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("n_input_zero_bytes", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("n_input_zero_bytes", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("n_input_zero_bytes", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("n_input_zero_bytes", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: n_input_nonzero_bytes
	if req.NInputNonzeroBytes != nil {
		switch filter := req.NInputNonzeroBytes.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("n_input_nonzero_bytes", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("n_input_nonzero_bytes", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("n_input_nonzero_bytes", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("n_input_nonzero_bytes", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("n_input_nonzero_bytes", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("n_input_nonzero_bytes", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("n_input_nonzero_bytes", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("n_input_nonzero_bytes", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("n_input_nonzero_bytes", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "block_number", "transaction_index", "transaction_hash", "nonce", "from_address", "to_address", "value", "input", "gas_limit", "gas_used", "gas_price", "transaction_type", "max_priority_fee_per_gas", "max_fee_per_gas", "success", "n_input_bytes", "n_input_zero_bytes", "n_input_nonzero_bytes", "meta_network_name"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY meta_network_name" + ", block_number" + ", transaction_hash"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "block_number", "transaction_index", "NULLIF(`transaction_hash`, repeat('\x00', 66)) AS `transaction_hash`", "nonce", "from_address", "to_address", "toString(`value`) AS `value`", "input", "gas_limit", "gas_used", "toString(`gas_price`) AS `gas_price`", "toUInt32(`transaction_type`) AS `transaction_type`", "max_priority_fee_per_gas", "max_fee_per_gas", "success", "n_input_bytes", "n_input_zero_bytes", "n_input_nonzero_bytes", "meta_network_name"}

	return BuildParameterizedQuery("canonical_execution_transaction", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetCanonicalExecutionTransactionQuery constructs a parameterized SQL query from a GetCanonicalExecutionTransactionRequest
func BuildGetCanonicalExecutionTransactionQuery(req *GetCanonicalExecutionTransactionRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.MetaNetworkName == "" {
		return SQLQuery{}, fmt.Errorf("primary key field meta_network_name is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("meta_network_name", "=", req.MetaNetworkName)

	// Build ORDER BY clause
	orderByClause := " ORDER BY meta_network_name, block_number, transaction_hash"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "block_number", "transaction_index", "NULLIF(`transaction_hash`, repeat('\x00', 66)) AS `transaction_hash`", "nonce", "from_address", "to_address", "toString(`value`) AS `value`", "input", "gas_limit", "gas_used", "toString(`gas_price`) AS `gas_price`", "toUInt32(`transaction_type`) AS `transaction_type`", "max_priority_fee_per_gas", "max_fee_per_gas", "success", "n_input_bytes", "n_input_zero_bytes", "n_input_nonzero_bytes", "meta_network_name"}

	// Return single record
	return BuildParameterizedQuery("canonical_execution_transaction", columns, qb, orderByClause, 1, 0, options...)
}
