// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for canonical_execution_four_byte_counts

package clickhouse

import (
	"fmt"
)

// BuildListCanonicalExecutionFourByteCountsQuery constructs a parameterized SQL query from a ListCanonicalExecutionFourByteCountsRequest
func BuildListCanonicalExecutionFourByteCountsQuery(req *ListCanonicalExecutionFourByteCountsRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.MetaNetworkName == nil {
		return SQLQuery{}, fmt.Errorf("primary key field meta_network_name is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.MetaNetworkName.Filter.(type) {
	case *StringFilter_Eq:
		qb.AddCondition("meta_network_name", "=", filter.Eq)
	case *StringFilter_Ne:
		qb.AddCondition("meta_network_name", "!=", filter.Ne)
	case *StringFilter_Contains:
		qb.AddLikeCondition("meta_network_name", "%" + filter.Contains + "%")
	case *StringFilter_StartsWith:
		qb.AddLikeCondition("meta_network_name", filter.StartsWith + "%")
	case *StringFilter_EndsWith:
		qb.AddLikeCondition("meta_network_name", "%" + filter.EndsWith)
	case *StringFilter_Like:
		qb.AddLikeCondition("meta_network_name", filter.Like)
	case *StringFilter_NotLike:
		qb.AddNotLikeCondition("meta_network_name", filter.NotLike)
	case *StringFilter_In:
		if len(filter.In.Values) > 0 {
			qb.AddInCondition("meta_network_name", StringSliceToInterface(filter.In.Values))
		}
	case *StringFilter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			qb.AddNotInCondition("meta_network_name", StringSliceToInterface(filter.NotIn.Values))
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: block_number
	if req.BlockNumber != nil {
		switch filter := req.BlockNumber.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("block_number", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("block_number", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("block_number", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("block_number", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("block_number", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("block_number", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("block_number", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("block_number", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("block_number", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: transaction_index
	if req.TransactionIndex != nil {
		switch filter := req.TransactionIndex.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("transaction_index", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("transaction_index", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("transaction_index", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("transaction_index", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("transaction_index", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("transaction_index", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("transaction_index", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("transaction_index", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("transaction_index", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: transaction_hash
	if req.TransactionHash != nil {
		switch filter := req.TransactionHash.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("transaction_hash", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("transaction_hash", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("transaction_hash", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("transaction_hash", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("transaction_hash", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("transaction_hash", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("transaction_hash", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("transaction_hash", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("transaction_hash", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: signature
	if req.Signature != nil {
		switch filter := req.Signature.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("signature", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("signature", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("signature", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("signature", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("signature", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("signature", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("signature", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("signature", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("signature", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: size
	if req.Size != nil {
		switch filter := req.Size.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("size", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("size", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("size", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("size", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("size", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("size", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("size", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("size", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("size", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: count
	if req.Count != nil {
		switch filter := req.Count.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("count", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("count", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("count", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("count", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("count", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("count", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("count", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("count", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "block_number", "transaction_index", "transaction_hash", "signature", "size", "count", "meta_network_name"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY meta_network_name" + ", block_number" + ", transaction_hash" + ", signature"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "block_number", "transaction_index", "NULLIF(`transaction_hash`, repeat('\x00', 66)) AS `transaction_hash`", "signature", "size", "count", "meta_network_name"}

	return BuildParameterizedQuery("canonical_execution_four_byte_counts", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetCanonicalExecutionFourByteCountsQuery constructs a parameterized SQL query from a GetCanonicalExecutionFourByteCountsRequest
func BuildGetCanonicalExecutionFourByteCountsQuery(req *GetCanonicalExecutionFourByteCountsRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.MetaNetworkName == "" {
		return SQLQuery{}, fmt.Errorf("primary key field meta_network_name is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("meta_network_name", "=", req.MetaNetworkName)

	// Build ORDER BY clause
	orderByClause := " ORDER BY meta_network_name, block_number, transaction_hash, signature"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "block_number", "transaction_index", "NULLIF(`transaction_hash`, repeat('\x00', 66)) AS `transaction_hash`", "signature", "size", "count", "meta_network_name"}

	// Return single record
	return BuildParameterizedQuery("canonical_execution_four_byte_counts", columns, qb, orderByClause, 1, 0, options...)
}
