// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for canonical_beacon_block_execution_payload_bid

package clickhouse

import (
	"fmt"
)

// BuildListCanonicalBeaconBlockExecutionPayloadBidQuery constructs a parameterized SQL query from a ListCanonicalBeaconBlockExecutionPayloadBidRequest
func BuildListCanonicalBeaconBlockExecutionPayloadBidQuery(req *ListCanonicalBeaconBlockExecutionPayloadBidRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.SlotStartDateTime == nil {
		return SQLQuery{}, fmt.Errorf("primary key field slot_start_date_time is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.SlotStartDateTime.Filter.(type) {
	case *UInt32Filter_Eq:
		qb.AddCondition("slot_start_date_time", "=", DateTimeValue{filter.Eq})
	case *UInt32Filter_Ne:
		qb.AddCondition("slot_start_date_time", "!=", DateTimeValue{filter.Ne})
	case *UInt32Filter_Lt:
		qb.AddCondition("slot_start_date_time", "<", DateTimeValue{filter.Lt})
	case *UInt32Filter_Lte:
		qb.AddCondition("slot_start_date_time", "<=", DateTimeValue{filter.Lte})
	case *UInt32Filter_Gt:
		qb.AddCondition("slot_start_date_time", ">", DateTimeValue{filter.Gt})
	case *UInt32Filter_Gte:
		qb.AddCondition("slot_start_date_time", ">=", DateTimeValue{filter.Gte})
	case *UInt32Filter_Between:
		qb.AddBetweenCondition("slot_start_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
	case *UInt32Filter_In:
		if len(filter.In.Values) > 0 {
			converted := make([]interface{}, len(filter.In.Values))
			for i, v := range filter.In.Values {
				converted[i] = DateTimeValue{v}
			}
			qb.AddInCondition("slot_start_date_time", converted)
		}
	case *UInt32Filter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			converted := make([]interface{}, len(filter.NotIn.Values))
			for i, v := range filter.NotIn.Values {
				converted[i] = DateTimeValue{v}
			}
			qb.AddNotInCondition("slot_start_date_time", converted)
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: slot
	if req.Slot != nil {
		switch filter := req.Slot.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("slot", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("slot", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("slot", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("slot", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("slot", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("slot", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("slot", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("slot", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("slot", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: epoch
	if req.Epoch != nil {
		switch filter := req.Epoch.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("epoch", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("epoch", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("epoch", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("epoch", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("epoch", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("epoch", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("epoch", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("epoch", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("epoch", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: epoch_start_date_time
	if req.EpochStartDateTime != nil {
		switch filter := req.EpochStartDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("epoch_start_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("epoch_start_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("epoch_start_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("epoch_start_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("epoch_start_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("epoch_start_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("epoch_start_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("epoch_start_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("epoch_start_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: block_root
	if req.BlockRoot != nil {
		switch filter := req.BlockRoot.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("block_root", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("block_root", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("block_root", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("block_root", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("block_root", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("block_root", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("block_root", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("block_root", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("block_root", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: block_version
	if req.BlockVersion != nil {
		switch filter := req.BlockVersion.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("block_version", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("block_version", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("block_version", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("block_version", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("block_version", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("block_version", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("block_version", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("block_version", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("block_version", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: builder_index
	if req.BuilderIndex != nil {
		switch filter := req.BuilderIndex.Filter.(type) {
		case *NullableUInt64Filter_Eq:
			qb.AddCondition("builder_index", "=", filter.Eq)
		case *NullableUInt64Filter_Ne:
			qb.AddCondition("builder_index", "!=", filter.Ne)
		case *NullableUInt64Filter_Lt:
			qb.AddCondition("builder_index", "<", filter.Lt)
		case *NullableUInt64Filter_Lte:
			qb.AddCondition("builder_index", "<=", filter.Lte)
		case *NullableUInt64Filter_Gt:
			qb.AddCondition("builder_index", ">", filter.Gt)
		case *NullableUInt64Filter_Gte:
			qb.AddCondition("builder_index", ">=", filter.Gte)
		case *NullableUInt64Filter_Between:
			qb.AddBetweenCondition("builder_index", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("builder_index", UInt64SliceToInterface(filter.In.Values))
			}
		case *NullableUInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("builder_index", UInt64SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt64Filter_IsNull:
			qb.AddIsNullCondition("builder_index")
		case *NullableUInt64Filter_IsNotNull:
			qb.AddIsNotNullCondition("builder_index")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: block_hash
	if req.BlockHash != nil {
		switch filter := req.BlockHash.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("block_hash", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("block_hash", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("block_hash", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("block_hash", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("block_hash", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("block_hash", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("block_hash", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("block_hash", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("block_hash", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: parent_block_hash
	if req.ParentBlockHash != nil {
		switch filter := req.ParentBlockHash.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("parent_block_hash", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("parent_block_hash", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("parent_block_hash", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("parent_block_hash", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("parent_block_hash", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("parent_block_hash", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("parent_block_hash", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("parent_block_hash", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("parent_block_hash", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: parent_block_root
	if req.ParentBlockRoot != nil {
		switch filter := req.ParentBlockRoot.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("parent_block_root", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("parent_block_root", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("parent_block_root", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("parent_block_root", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("parent_block_root", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("parent_block_root", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("parent_block_root", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("parent_block_root", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("parent_block_root", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: value
	if req.Value != nil {
		switch filter := req.Value.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("value", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("value", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("value", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("value", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("value", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("value", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("value", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("value", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("value", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: execution_payment
	if req.ExecutionPayment != nil {
		switch filter := req.ExecutionPayment.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("execution_payment", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("execution_payment", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("execution_payment", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("execution_payment", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("execution_payment", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("execution_payment", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("execution_payment", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("execution_payment", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("execution_payment", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: fee_recipient
	if req.FeeRecipient != nil {
		switch filter := req.FeeRecipient.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("fee_recipient", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("fee_recipient", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("fee_recipient", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("fee_recipient", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("fee_recipient", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("fee_recipient", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("fee_recipient", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("fee_recipient", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("fee_recipient", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: gas_limit
	if req.GasLimit != nil {
		switch filter := req.GasLimit.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("gas_limit", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("gas_limit", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("gas_limit", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("gas_limit", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("gas_limit", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("gas_limit", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("gas_limit", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("gas_limit", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("gas_limit", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: prev_randao
	if req.PrevRandao != nil {
		switch filter := req.PrevRandao.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("prev_randao", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("prev_randao", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("prev_randao", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("prev_randao", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("prev_randao", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("prev_randao", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("prev_randao", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("prev_randao", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("prev_randao", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: blob_kzg_commitment_count
	if req.BlobKzgCommitmentCount != nil {
		switch filter := req.BlobKzgCommitmentCount.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("blob_kzg_commitment_count", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("blob_kzg_commitment_count", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("blob_kzg_commitment_count", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("blob_kzg_commitment_count", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("blob_kzg_commitment_count", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("blob_kzg_commitment_count", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("blob_kzg_commitment_count", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("blob_kzg_commitment_count", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("blob_kzg_commitment_count", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_name
	if req.MetaClientName != nil {
		switch filter := req.MetaClientName.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_name", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_name", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_name", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_name", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_name", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_name", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_name", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_name", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_name", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_id
	if req.MetaClientId != nil {
		switch filter := req.MetaClientId.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_id", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_id", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_id", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_id", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_id", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_id", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_id", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_id", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_id", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_version
	if req.MetaClientVersion != nil {
		switch filter := req.MetaClientVersion.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_version", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_version", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_version", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_version", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_version", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_version", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_version", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_version", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_version", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_implementation
	if req.MetaClientImplementation != nil {
		switch filter := req.MetaClientImplementation.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_implementation", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_implementation", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_implementation", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_implementation", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_implementation", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_implementation", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_implementation", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_implementation", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_implementation", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_os
	if req.MetaClientOs != nil {
		switch filter := req.MetaClientOs.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_os", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_os", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_os", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_os", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_os", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_os", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_os", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_os", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_os", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_ip
	if req.MetaClientIp != nil {
		switch filter := req.MetaClientIp.Filter.(type) {
		case *NullableStringFilter_Eq:
			qb.AddCondition("meta_client_ip", "=", filter.Eq)
		case *NullableStringFilter_Ne:
			qb.AddCondition("meta_client_ip", "!=", filter.Ne)
		case *NullableStringFilter_Contains:
			qb.AddLikeCondition("meta_client_ip", "%" + filter.Contains + "%")
		case *NullableStringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_ip", filter.StartsWith + "%")
		case *NullableStringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_ip", "%" + filter.EndsWith)
		case *NullableStringFilter_Like:
			qb.AddLikeCondition("meta_client_ip", filter.Like)
		case *NullableStringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_ip", filter.NotLike)
		case *NullableStringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_ip", StringSliceToInterface(filter.In.Values))
			}
		case *NullableStringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_ip", StringSliceToInterface(filter.NotIn.Values))
			}
		case *NullableStringFilter_IsNull:
			qb.AddIsNullCondition("meta_client_ip")
		case *NullableStringFilter_IsNotNull:
			qb.AddIsNotNullCondition("meta_client_ip")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_city
	if req.MetaClientGeoCity != nil {
		switch filter := req.MetaClientGeoCity.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_geo_city", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_geo_city", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_geo_city", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_geo_city", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_geo_city", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_geo_city", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_geo_city", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_city", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_city", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_country
	if req.MetaClientGeoCountry != nil {
		switch filter := req.MetaClientGeoCountry.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_geo_country", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_geo_country", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_geo_country", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_geo_country", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_geo_country", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_geo_country", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_geo_country", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_country", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_country", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_country_code
	if req.MetaClientGeoCountryCode != nil {
		switch filter := req.MetaClientGeoCountryCode.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_geo_country_code", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_geo_country_code", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_geo_country_code", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_geo_country_code", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_geo_country_code", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_geo_country_code", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_geo_country_code", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_country_code", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_country_code", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_continent_code
	if req.MetaClientGeoContinentCode != nil {
		switch filter := req.MetaClientGeoContinentCode.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_geo_continent_code", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_geo_continent_code", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_geo_continent_code", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_geo_continent_code", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_geo_continent_code", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_geo_continent_code", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_geo_continent_code", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_continent_code", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_continent_code", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_longitude

	// Add filter for column: meta_client_geo_latitude

	// Add filter for column: meta_client_geo_autonomous_system_number
	if req.MetaClientGeoAutonomousSystemNumber != nil {
		switch filter := req.MetaClientGeoAutonomousSystemNumber.Filter.(type) {
		case *NullableUInt32Filter_Eq:
			qb.AddCondition("meta_client_geo_autonomous_system_number", "=", filter.Eq)
		case *NullableUInt32Filter_Ne:
			qb.AddCondition("meta_client_geo_autonomous_system_number", "!=", filter.Ne)
		case *NullableUInt32Filter_Lt:
			qb.AddCondition("meta_client_geo_autonomous_system_number", "<", filter.Lt)
		case *NullableUInt32Filter_Lte:
			qb.AddCondition("meta_client_geo_autonomous_system_number", "<=", filter.Lte)
		case *NullableUInt32Filter_Gt:
			qb.AddCondition("meta_client_geo_autonomous_system_number", ">", filter.Gt)
		case *NullableUInt32Filter_Gte:
			qb.AddCondition("meta_client_geo_autonomous_system_number", ">=", filter.Gte)
		case *NullableUInt32Filter_Between:
			qb.AddBetweenCondition("meta_client_geo_autonomous_system_number", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_autonomous_system_number", UInt32SliceToInterface(filter.In.Values))
			}
		case *NullableUInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_autonomous_system_number", UInt32SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt32Filter_IsNull:
			qb.AddIsNullCondition("meta_client_geo_autonomous_system_number")
		case *NullableUInt32Filter_IsNotNull:
			qb.AddIsNotNullCondition("meta_client_geo_autonomous_system_number")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_autonomous_system_organization
	if req.MetaClientGeoAutonomousSystemOrganization != nil {
		switch filter := req.MetaClientGeoAutonomousSystemOrganization.Filter.(type) {
		case *NullableStringFilter_Eq:
			qb.AddCondition("meta_client_geo_autonomous_system_organization", "=", filter.Eq)
		case *NullableStringFilter_Ne:
			qb.AddCondition("meta_client_geo_autonomous_system_organization", "!=", filter.Ne)
		case *NullableStringFilter_Contains:
			qb.AddLikeCondition("meta_client_geo_autonomous_system_organization", "%" + filter.Contains + "%")
		case *NullableStringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_geo_autonomous_system_organization", filter.StartsWith + "%")
		case *NullableStringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_geo_autonomous_system_organization", "%" + filter.EndsWith)
		case *NullableStringFilter_Like:
			qb.AddLikeCondition("meta_client_geo_autonomous_system_organization", filter.Like)
		case *NullableStringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_geo_autonomous_system_organization", filter.NotLike)
		case *NullableStringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_autonomous_system_organization", StringSliceToInterface(filter.In.Values))
			}
		case *NullableStringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_autonomous_system_organization", StringSliceToInterface(filter.NotIn.Values))
			}
		case *NullableStringFilter_IsNull:
			qb.AddIsNullCondition("meta_client_geo_autonomous_system_organization")
		case *NullableStringFilter_IsNotNull:
			qb.AddIsNotNullCondition("meta_client_geo_autonomous_system_organization")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_network_id
	if req.MetaNetworkId != nil {
		switch filter := req.MetaNetworkId.Filter.(type) {
		case *Int32Filter_Eq:
			qb.AddCondition("meta_network_id", "=", filter.Eq)
		case *Int32Filter_Ne:
			qb.AddCondition("meta_network_id", "!=", filter.Ne)
		case *Int32Filter_Lt:
			qb.AddCondition("meta_network_id", "<", filter.Lt)
		case *Int32Filter_Lte:
			qb.AddCondition("meta_network_id", "<=", filter.Lte)
		case *Int32Filter_Gt:
			qb.AddCondition("meta_network_id", ">", filter.Gt)
		case *Int32Filter_Gte:
			qb.AddCondition("meta_network_id", ">=", filter.Gte)
		case *Int32Filter_Between:
			qb.AddBetweenCondition("meta_network_id", filter.Between.Min, filter.Between.Max.GetValue())
		case *Int32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_network_id", Int32SliceToInterface(filter.In.Values))
			}
		case *Int32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_network_id", Int32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_network_name
	if req.MetaNetworkName != nil {
		switch filter := req.MetaNetworkName.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_network_name", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_network_name", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_network_name", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_network_name", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_network_name", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_network_name", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_network_name", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_network_name", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_network_name", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_consensus_version
	if req.MetaConsensusVersion != nil {
		switch filter := req.MetaConsensusVersion.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_consensus_version", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_consensus_version", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_consensus_version", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_consensus_version", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_consensus_version", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_consensus_version", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_consensus_version", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_consensus_version", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_consensus_version", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_consensus_version_major
	if req.MetaConsensusVersionMajor != nil {
		switch filter := req.MetaConsensusVersionMajor.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_consensus_version_major", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_consensus_version_major", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_consensus_version_major", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_consensus_version_major", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_consensus_version_major", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_consensus_version_major", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_consensus_version_major", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_consensus_version_major", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_consensus_version_major", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_consensus_version_minor
	if req.MetaConsensusVersionMinor != nil {
		switch filter := req.MetaConsensusVersionMinor.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_consensus_version_minor", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_consensus_version_minor", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_consensus_version_minor", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_consensus_version_minor", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_consensus_version_minor", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_consensus_version_minor", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_consensus_version_minor", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_consensus_version_minor", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_consensus_version_minor", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_consensus_version_patch
	if req.MetaConsensusVersionPatch != nil {
		switch filter := req.MetaConsensusVersionPatch.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_consensus_version_patch", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_consensus_version_patch", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_consensus_version_patch", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_consensus_version_patch", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_consensus_version_patch", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_consensus_version_patch", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_consensus_version_patch", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_consensus_version_patch", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_consensus_version_patch", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_consensus_implementation
	if req.MetaConsensusImplementation != nil {
		switch filter := req.MetaConsensusImplementation.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_consensus_implementation", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_consensus_implementation", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_consensus_implementation", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_consensus_implementation", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_consensus_implementation", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_consensus_implementation", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_consensus_implementation", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_consensus_implementation", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_consensus_implementation", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_labels
	if req.MetaLabels != nil {
		switch filter := req.MetaLabels.Filter.(type) {
		case *MapStringStringFilter_KeyValue:
			// Handle key-value filter with string values
			switch kvFilter := filter.KeyValue.ValueFilter.Filter.(type) {
			case *StringFilter_Eq:
				qb.AddMapKeyCondition("meta_labels", filter.KeyValue.Key, "=", kvFilter.Eq)
			case *StringFilter_Ne:
				qb.AddMapKeyCondition("meta_labels", filter.KeyValue.Key, "!=", kvFilter.Ne)
			case *StringFilter_Like:
				qb.AddMapKeyLikeCondition("meta_labels", filter.KeyValue.Key, kvFilter.Like)
			case *StringFilter_StartsWith:
				qb.AddMapKeyLikeCondition("meta_labels", filter.KeyValue.Key, kvFilter.StartsWith + "%")
			case *StringFilter_EndsWith:
				qb.AddMapKeyLikeCondition("meta_labels", filter.KeyValue.Key, "%" + kvFilter.EndsWith)
			case *StringFilter_Contains:
				qb.AddMapKeyLikeCondition("meta_labels", filter.KeyValue.Key, "%" + kvFilter.Contains + "%")
			}
		case *MapStringStringFilter_HasKey:
			qb.AddMapContainsCondition("meta_labels", filter.HasKey)
		case *MapStringStringFilter_NotHasKey:
			qb.AddNotMapContainsCondition("meta_labels", filter.NotHasKey)
		case *MapStringStringFilter_HasAnyKey:
			if len(filter.HasAnyKey.Values) > 0 {
				qb.AddMapContainsAnyCondition("meta_labels", filter.HasAnyKey.Values)
			}
		case *MapStringStringFilter_HasAllKeys:
			if len(filter.HasAllKeys.Values) > 0 {
				for _, key := range filter.HasAllKeys.Values {
					qb.AddMapContainsCondition("meta_labels", key)
				}
			}
		default:
			// Unsupported filter type
		}
	}

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "slot", "slot_start_date_time", "epoch", "epoch_start_date_time", "block_root", "block_version", "builder_index", "block_hash", "parent_block_hash", "parent_block_root", "value", "execution_payment", "fee_recipient", "gas_limit", "prev_randao", "blob_kzg_commitment_count", "meta_client_name", "meta_client_id", "meta_client_version", "meta_client_implementation", "meta_client_os", "meta_client_ip", "meta_client_geo_city", "meta_client_geo_country", "meta_client_geo_country_code", "meta_client_geo_continent_code", "meta_client_geo_longitude", "meta_client_geo_latitude", "meta_client_geo_autonomous_system_number", "meta_client_geo_autonomous_system_organization", "meta_network_id", "meta_network_name", "meta_consensus_version", "meta_consensus_version_major", "meta_consensus_version_minor", "meta_consensus_version_patch", "meta_consensus_implementation", "meta_labels"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY slot_start_date_time" + ", meta_network_name" + ", block_root"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "slot", "toUnixTimestamp(`slot_start_date_time`) AS `slot_start_date_time`", "epoch", "toUnixTimestamp(`epoch_start_date_time`) AS `epoch_start_date_time`", "NULLIF(`block_root`, repeat('\x00', 66)) AS `block_root`", "block_version", "builder_index", "NULLIF(`block_hash`, repeat('\x00', 66)) AS `block_hash`", "NULLIF(`parent_block_hash`, repeat('\x00', 66)) AS `parent_block_hash`", "NULLIF(`parent_block_root`, repeat('\x00', 66)) AS `parent_block_root`", "value", "execution_payment", "NULLIF(`fee_recipient`, repeat('\x00', 42)) AS `fee_recipient`", "gas_limit", "NULLIF(`prev_randao`, repeat('\x00', 66)) AS `prev_randao`", "blob_kzg_commitment_count", "meta_client_name", "meta_client_id", "meta_client_version", "meta_client_implementation", "meta_client_os", "meta_client_ip", "meta_client_geo_city", "meta_client_geo_country", "meta_client_geo_country_code", "meta_client_geo_continent_code", "meta_client_geo_longitude", "meta_client_geo_latitude", "meta_client_geo_autonomous_system_number", "meta_client_geo_autonomous_system_organization", "meta_network_id", "meta_network_name", "meta_consensus_version", "meta_consensus_version_major", "meta_consensus_version_minor", "meta_consensus_version_patch", "meta_consensus_implementation", "meta_labels"}

	return BuildParameterizedQuery("canonical_beacon_block_execution_payload_bid", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetCanonicalBeaconBlockExecutionPayloadBidQuery constructs a parameterized SQL query from a GetCanonicalBeaconBlockExecutionPayloadBidRequest
func BuildGetCanonicalBeaconBlockExecutionPayloadBidQuery(req *GetCanonicalBeaconBlockExecutionPayloadBidRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.SlotStartDateTime == 0 {
		return SQLQuery{}, fmt.Errorf("primary key field slot_start_date_time is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("slot_start_date_time", "=", req.SlotStartDateTime)

	// Build ORDER BY clause
	orderByClause := " ORDER BY slot_start_date_time, meta_network_name, block_root"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "slot", "toUnixTimestamp(`slot_start_date_time`) AS `slot_start_date_time`", "epoch", "toUnixTimestamp(`epoch_start_date_time`) AS `epoch_start_date_time`", "NULLIF(`block_root`, repeat('\x00', 66)) AS `block_root`", "block_version", "builder_index", "NULLIF(`block_hash`, repeat('\x00', 66)) AS `block_hash`", "NULLIF(`parent_block_hash`, repeat('\x00', 66)) AS `parent_block_hash`", "NULLIF(`parent_block_root`, repeat('\x00', 66)) AS `parent_block_root`", "value", "execution_payment", "NULLIF(`fee_recipient`, repeat('\x00', 42)) AS `fee_recipient`", "gas_limit", "NULLIF(`prev_randao`, repeat('\x00', 66)) AS `prev_randao`", "blob_kzg_commitment_count", "meta_client_name", "meta_client_id", "meta_client_version", "meta_client_implementation", "meta_client_os", "meta_client_ip", "meta_client_geo_city", "meta_client_geo_country", "meta_client_geo_country_code", "meta_client_geo_continent_code", "meta_client_geo_longitude", "meta_client_geo_latitude", "meta_client_geo_autonomous_system_number", "meta_client_geo_autonomous_system_organization", "meta_network_id", "meta_network_name", "meta_consensus_version", "meta_consensus_version_major", "meta_consensus_version_minor", "meta_consensus_version_patch", "meta_consensus_implementation", "meta_labels"}

	// Return single record
	return BuildParameterizedQuery("canonical_beacon_block_execution_payload_bid", columns, qb, orderByClause, 1, 0, options...)
}
