// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for canonical_beacon_block_withdrawal

package clickhouse

// CanonicalBeaconBlockWithdrawalRow is a ClickHouse-scannable result row for the canonical_beacon_block_withdrawal table.
// Field types match the SELECT column expressions produced by
// BuildListCanonicalBeaconBlockWithdrawalQuery and BuildGetCanonicalBeaconBlockWithdrawalQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type CanonicalBeaconBlockWithdrawalRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	Slot uint32 `ch:"slot" json:"slot"`
	SlotStartDateTime uint32 `ch:"slot_start_date_time" json:"slot_start_date_time"`
	Epoch uint32 `ch:"epoch" json:"epoch"`
	EpochStartDateTime uint32 `ch:"epoch_start_date_time" json:"epoch_start_date_time"`
	BlockRoot *string `ch:"block_root" json:"block_root"`
	BlockVersion string `ch:"block_version" json:"block_version"`
	WithdrawalIndex uint32 `ch:"withdrawal_index" json:"withdrawal_index"`
	WithdrawalValidatorIndex uint32 `ch:"withdrawal_validator_index" json:"withdrawal_validator_index"`
	WithdrawalAddress *string `ch:"withdrawal_address" json:"withdrawal_address"`
	WithdrawalAmount string `ch:"withdrawal_amount" json:"withdrawal_amount"`
	MetaNetworkName string `ch:"meta_network_name" json:"meta_network_name"`
}

// TableName returns the ClickHouse table this row maps to.
func (CanonicalBeaconBlockWithdrawalRow) TableName() string {
	return "canonical_beacon_block_withdrawal"
}

// ToProto converts the row to its protobuf message.
func (r *CanonicalBeaconBlockWithdrawalRow) ToProto() *CanonicalBeaconBlockWithdrawal {
	p := &CanonicalBeaconBlockWithdrawal{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.Slot = r.Slot
	p.SlotStartDateTime = r.SlotStartDateTime
	p.Epoch = r.Epoch
	p.EpochStartDateTime = r.EpochStartDateTime
	if r.BlockRoot != nil {
		p.BlockRoot = *r.BlockRoot
	}
	p.BlockVersion = r.BlockVersion
	p.WithdrawalIndex = r.WithdrawalIndex
	p.WithdrawalValidatorIndex = r.WithdrawalValidatorIndex
	if r.WithdrawalAddress != nil {
		p.WithdrawalAddress = *r.WithdrawalAddress
	}
	p.WithdrawalAmount = r.WithdrawalAmount
	p.MetaNetworkName = r.MetaNetworkName
	return p
}
