// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for canonical_beacon_block_deposit

package clickhouse

// CanonicalBeaconBlockDepositRow is a ClickHouse-scannable result row for the canonical_beacon_block_deposit table.
// Field types match the SELECT column expressions produced by
// BuildListCanonicalBeaconBlockDepositQuery and BuildGetCanonicalBeaconBlockDepositQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type CanonicalBeaconBlockDepositRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	Slot uint32 `ch:"slot" json:"slot"`
	SlotStartDateTime uint32 `ch:"slot_start_date_time" json:"slot_start_date_time"`
	Epoch uint32 `ch:"epoch" json:"epoch"`
	EpochStartDateTime uint32 `ch:"epoch_start_date_time" json:"epoch_start_date_time"`
	BlockRoot *string `ch:"block_root" json:"block_root"`
	BlockVersion string `ch:"block_version" json:"block_version"`
	DepositProof []string `ch:"deposit_proof" json:"deposit_proof"`
	DepositDataPubkey string `ch:"deposit_data_pubkey" json:"deposit_data_pubkey"`
	DepositDataWithdrawalCredentials *string `ch:"deposit_data_withdrawal_credentials" json:"deposit_data_withdrawal_credentials"`
	DepositDataAmount string `ch:"deposit_data_amount" json:"deposit_data_amount"`
	DepositDataSignature string `ch:"deposit_data_signature" json:"deposit_data_signature"`
	MetaNetworkName string `ch:"meta_network_name" json:"meta_network_name"`
}

// TableName returns the ClickHouse table this row maps to.
func (CanonicalBeaconBlockDepositRow) TableName() string {
	return "canonical_beacon_block_deposit"
}

// ToProto converts the row to its protobuf message.
func (r *CanonicalBeaconBlockDepositRow) ToProto() *CanonicalBeaconBlockDeposit {
	p := &CanonicalBeaconBlockDeposit{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.Slot = r.Slot
	p.SlotStartDateTime = r.SlotStartDateTime
	p.Epoch = r.Epoch
	p.EpochStartDateTime = r.EpochStartDateTime
	if r.BlockRoot != nil {
		p.BlockRoot = *r.BlockRoot
	}
	p.BlockVersion = r.BlockVersion
	p.DepositProof = r.DepositProof
	p.DepositDataPubkey = r.DepositDataPubkey
	if r.DepositDataWithdrawalCredentials != nil {
		p.DepositDataWithdrawalCredentials = *r.DepositDataWithdrawalCredentials
	}
	p.DepositDataAmount = r.DepositDataAmount
	p.DepositDataSignature = r.DepositDataSignature
	p.MetaNetworkName = r.MetaNetworkName
	return p
}
