// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for canonical_beacon_sync_committee

package clickhouse

import (
	"fmt"
)

// BuildListCanonicalBeaconSyncCommitteeQuery constructs a parameterized SQL query from a ListCanonicalBeaconSyncCommitteeRequest
func BuildListCanonicalBeaconSyncCommitteeQuery(req *ListCanonicalBeaconSyncCommitteeRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.MetaNetworkName == nil {
		return SQLQuery{}, fmt.Errorf("primary key field meta_network_name is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.MetaNetworkName.Filter.(type) {
	case *StringFilter_Eq:
		qb.AddCondition("meta_network_name", "=", filter.Eq)
	case *StringFilter_Ne:
		qb.AddCondition("meta_network_name", "!=", filter.Ne)
	case *StringFilter_Contains:
		qb.AddLikeCondition("meta_network_name", "%" + filter.Contains + "%")
	case *StringFilter_StartsWith:
		qb.AddLikeCondition("meta_network_name", filter.StartsWith + "%")
	case *StringFilter_EndsWith:
		qb.AddLikeCondition("meta_network_name", "%" + filter.EndsWith)
	case *StringFilter_Like:
		qb.AddLikeCondition("meta_network_name", filter.Like)
	case *StringFilter_NotLike:
		qb.AddNotLikeCondition("meta_network_name", filter.NotLike)
	case *StringFilter_In:
		if len(filter.In.Values) > 0 {
			qb.AddInCondition("meta_network_name", StringSliceToInterface(filter.In.Values))
		}
	case *StringFilter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			qb.AddNotInCondition("meta_network_name", StringSliceToInterface(filter.NotIn.Values))
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: event_date_time
	if req.EventDateTime != nil {
		switch filter := req.EventDateTime.Filter.(type) {
		case *Int64Filter_Eq:
			qb.AddCondition("event_date_time", "=", DateTime64Value{uint64(filter.Eq)})
		case *Int64Filter_Ne:
			qb.AddCondition("event_date_time", "!=", DateTime64Value{uint64(filter.Ne)})
		case *Int64Filter_Lt:
			qb.AddCondition("event_date_time", "<", DateTime64Value{uint64(filter.Lt)})
		case *Int64Filter_Lte:
			qb.AddCondition("event_date_time", "<=", DateTime64Value{uint64(filter.Lte)})
		case *Int64Filter_Gt:
			qb.AddCondition("event_date_time", ">", DateTime64Value{uint64(filter.Gt)})
		case *Int64Filter_Gte:
			qb.AddCondition("event_date_time", ">=", DateTime64Value{uint64(filter.Gte)})
		case *Int64Filter_Between:
			qb.AddBetweenCondition("event_date_time", DateTime64Value{uint64(filter.Between.Min)}, DateTime64Value{uint64(filter.Between.Max.GetValue())})
		case *Int64Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTime64Value{uint64(v)}
				}
				qb.AddInCondition("event_date_time", converted)
			}
		case *Int64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTime64Value{uint64(v)}
				}
				qb.AddNotInCondition("event_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: epoch
	if req.Epoch != nil {
		switch filter := req.Epoch.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("epoch", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("epoch", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("epoch", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("epoch", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("epoch", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("epoch", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("epoch", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("epoch", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("epoch", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: epoch_start_date_time
	if req.EpochStartDateTime != nil {
		switch filter := req.EpochStartDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("epoch_start_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("epoch_start_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("epoch_start_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("epoch_start_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("epoch_start_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("epoch_start_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("epoch_start_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("epoch_start_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("epoch_start_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: sync_committee_period
	if req.SyncCommitteePeriod != nil {
		switch filter := req.SyncCommitteePeriod.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("sync_committee_period", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("sync_committee_period", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("sync_committee_period", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("sync_committee_period", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("sync_committee_period", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("sync_committee_period", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("sync_committee_period", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("sync_committee_period", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("sync_committee_period", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: validator_aggregates
	if req.ValidatorAggregates != nil {
		switch filter := req.ValidatorAggregates.Filter.(type) {
		case *ArrayUInt32Filter_Has:
			qb.AddArrayHasCondition("validator_aggregates", filter.Has)
		case *ArrayUInt32Filter_HasAll:
			if len(filter.HasAll.Values) > 0 {
				qb.AddArrayHasAllCondition("validator_aggregates", UInt32SliceToInterface(filter.HasAll.Values))
			}
		case *ArrayUInt32Filter_HasAny:
			if len(filter.HasAny.Values) > 0 {
				qb.AddArrayHasAnyCondition("validator_aggregates", UInt32SliceToInterface(filter.HasAny.Values))
			}
		case *ArrayUInt32Filter_LengthEq:
			qb.AddArrayLengthCondition("validator_aggregates", "=", filter.LengthEq)
		case *ArrayUInt32Filter_LengthGt:
			qb.AddArrayLengthCondition("validator_aggregates", ">", filter.LengthGt)
		case *ArrayUInt32Filter_LengthGte:
			qb.AddArrayLengthCondition("validator_aggregates", ">=", filter.LengthGte)
		case *ArrayUInt32Filter_LengthLt:
			qb.AddArrayLengthCondition("validator_aggregates", "<", filter.LengthLt)
		case *ArrayUInt32Filter_LengthLte:
			qb.AddArrayLengthCondition("validator_aggregates", "<=", filter.LengthLte)
		case *ArrayUInt32Filter_IsEmpty:
			qb.AddArrayIsEmptyCondition("validator_aggregates")
		case *ArrayUInt32Filter_IsNotEmpty:
			qb.AddArrayIsNotEmptyCondition("validator_aggregates")
		default:
			// Unsupported filter type
		}
	}

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "event_date_time", "epoch", "epoch_start_date_time", "sync_committee_period", "validator_aggregates", "meta_network_name"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY meta_network_name" + ", epoch_start_date_time" + ", sync_committee_period"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "toUnixTimestamp64Micro(`event_date_time`) AS `event_date_time`", "epoch", "toUnixTimestamp(`epoch_start_date_time`) AS `epoch_start_date_time`", "sync_committee_period", "validator_aggregates", "meta_network_name"}

	return BuildParameterizedQuery("canonical_beacon_sync_committee", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetCanonicalBeaconSyncCommitteeQuery constructs a parameterized SQL query from a GetCanonicalBeaconSyncCommitteeRequest
func BuildGetCanonicalBeaconSyncCommitteeQuery(req *GetCanonicalBeaconSyncCommitteeRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.MetaNetworkName == "" {
		return SQLQuery{}, fmt.Errorf("primary key field meta_network_name is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("meta_network_name", "=", req.MetaNetworkName)

	// Build ORDER BY clause
	orderByClause := " ORDER BY meta_network_name, epoch_start_date_time, sync_committee_period"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "toUnixTimestamp64Micro(`event_date_time`) AS `event_date_time`", "epoch", "toUnixTimestamp(`epoch_start_date_time`) AS `epoch_start_date_time`", "sync_committee_period", "validator_aggregates", "meta_network_name"}

	// Return single record
	return BuildParameterizedQuery("canonical_beacon_sync_committee", columns, qb, orderByClause, 1, 0, options...)
}
