// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for canonical_beacon_state_pending_consolidation

package clickhouse

import (
	"fmt"
)

// BuildListCanonicalBeaconStatePendingConsolidationQuery constructs a parameterized SQL query from a ListCanonicalBeaconStatePendingConsolidationRequest
func BuildListCanonicalBeaconStatePendingConsolidationQuery(req *ListCanonicalBeaconStatePendingConsolidationRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.MetaNetworkName == nil {
		return SQLQuery{}, fmt.Errorf("primary key field meta_network_name is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.MetaNetworkName.Filter.(type) {
	case *StringFilter_Eq:
		qb.AddCondition("meta_network_name", "=", filter.Eq)
	case *StringFilter_Ne:
		qb.AddCondition("meta_network_name", "!=", filter.Ne)
	case *StringFilter_Contains:
		qb.AddLikeCondition("meta_network_name", "%" + filter.Contains + "%")
	case *StringFilter_StartsWith:
		qb.AddLikeCondition("meta_network_name", filter.StartsWith + "%")
	case *StringFilter_EndsWith:
		qb.AddLikeCondition("meta_network_name", "%" + filter.EndsWith)
	case *StringFilter_Like:
		qb.AddLikeCondition("meta_network_name", filter.Like)
	case *StringFilter_NotLike:
		qb.AddNotLikeCondition("meta_network_name", filter.NotLike)
	case *StringFilter_In:
		if len(filter.In.Values) > 0 {
			qb.AddInCondition("meta_network_name", StringSliceToInterface(filter.In.Values))
		}
	case *StringFilter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			qb.AddNotInCondition("meta_network_name", StringSliceToInterface(filter.NotIn.Values))
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: epoch
	if req.Epoch != nil {
		switch filter := req.Epoch.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("epoch", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("epoch", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("epoch", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("epoch", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("epoch", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("epoch", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("epoch", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("epoch", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("epoch", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: epoch_start_date_time
	if req.EpochStartDateTime != nil {
		switch filter := req.EpochStartDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("epoch_start_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("epoch_start_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("epoch_start_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("epoch_start_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("epoch_start_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("epoch_start_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("epoch_start_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("epoch_start_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("epoch_start_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: state_id
	if req.StateId != nil {
		switch filter := req.StateId.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("state_id", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("state_id", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("state_id", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("state_id", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("state_id", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("state_id", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("state_id", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("state_id", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("state_id", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: position_in_queue
	if req.PositionInQueue != nil {
		switch filter := req.PositionInQueue.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("position_in_queue", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("position_in_queue", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("position_in_queue", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("position_in_queue", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("position_in_queue", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("position_in_queue", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("position_in_queue", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("position_in_queue", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("position_in_queue", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: source_index
	if req.SourceIndex != nil {
		switch filter := req.SourceIndex.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("source_index", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("source_index", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("source_index", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("source_index", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("source_index", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("source_index", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("source_index", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("source_index", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("source_index", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: target_index
	if req.TargetIndex != nil {
		switch filter := req.TargetIndex.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("target_index", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("target_index", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("target_index", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("target_index", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("target_index", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("target_index", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("target_index", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("target_index", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("target_index", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "epoch", "epoch_start_date_time", "state_id", "position_in_queue", "source_index", "target_index", "meta_network_name"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY meta_network_name" + ", epoch_start_date_time" + ", epoch" + ", position_in_queue"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "epoch", "toUnixTimestamp(`epoch_start_date_time`) AS `epoch_start_date_time`", "state_id", "position_in_queue", "source_index", "target_index", "meta_network_name"}

	return BuildParameterizedQuery("canonical_beacon_state_pending_consolidation", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetCanonicalBeaconStatePendingConsolidationQuery constructs a parameterized SQL query from a GetCanonicalBeaconStatePendingConsolidationRequest
func BuildGetCanonicalBeaconStatePendingConsolidationQuery(req *GetCanonicalBeaconStatePendingConsolidationRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.MetaNetworkName == "" {
		return SQLQuery{}, fmt.Errorf("primary key field meta_network_name is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("meta_network_name", "=", req.MetaNetworkName)

	// Build ORDER BY clause
	orderByClause := " ORDER BY meta_network_name, epoch_start_date_time, epoch, position_in_queue"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "epoch", "toUnixTimestamp(`epoch_start_date_time`) AS `epoch_start_date_time`", "state_id", "position_in_queue", "source_index", "target_index", "meta_network_name"}

	// Return single record
	return BuildParameterizedQuery("canonical_beacon_state_pending_consolidation", columns, qb, orderByClause, 1, 0, options...)
}
