// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for execution_transaction

package clickhouse

import (
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// ExecutionTransactionRow is a ClickHouse-scannable result row for the execution_transaction table.
// Field types match the SELECT column expressions produced by
// BuildListExecutionTransactionQuery and BuildGetExecutionTransactionQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type ExecutionTransactionRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	BlockNumber uint64 `ch:"block_number" json:"block_number"`
	BlockHash *string `ch:"block_hash" json:"block_hash"`
	ParentHash *string `ch:"parent_hash" json:"parent_hash"`
	Position uint32 `ch:"position" json:"position"`
	Hash *string `ch:"hash" json:"hash"`
	From *string `ch:"from" json:"from"`
	To *string `ch:"to" json:"to"`
	Nonce uint64 `ch:"nonce" json:"nonce"`
	GasPrice string `ch:"gas_price" json:"gas_price"`
	Gas uint64 `ch:"gas" json:"gas"`
	GasTipCap *string `ch:"gas_tip_cap" json:"gas_tip_cap"`
	GasFeeCap *string `ch:"gas_fee_cap" json:"gas_fee_cap"`
	Value string `ch:"value" json:"value"`
	Type uint32 `ch:"type" json:"type"`
	Size uint32 `ch:"size" json:"size"`
	CallDataSize uint32 `ch:"call_data_size" json:"call_data_size"`
	BlobGas *uint64 `ch:"blob_gas" json:"blob_gas"`
	BlobGasFeeCap *string `ch:"blob_gas_fee_cap" json:"blob_gas_fee_cap"`
	BlobHashes []string `ch:"blob_hashes" json:"blob_hashes"`
	Success bool `ch:"success" json:"success"`
	NInputBytes uint32 `ch:"n_input_bytes" json:"n_input_bytes"`
	NInputZeroBytes uint32 `ch:"n_input_zero_bytes" json:"n_input_zero_bytes"`
	NInputNonzeroBytes uint32 `ch:"n_input_nonzero_bytes" json:"n_input_nonzero_bytes"`
	MetaNetworkName string `ch:"meta_network_name" json:"meta_network_name"`
}

// TableName returns the ClickHouse table this row maps to.
func (ExecutionTransactionRow) TableName() string {
	return "execution_transaction"
}

// ToProto converts the row to its protobuf message.
func (r *ExecutionTransactionRow) ToProto() *ExecutionTransaction {
	p := &ExecutionTransaction{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.BlockNumber = r.BlockNumber
	if r.BlockHash != nil {
		p.BlockHash = *r.BlockHash
	}
	if r.ParentHash != nil {
		p.ParentHash = *r.ParentHash
	}
	p.Position = r.Position
	if r.Hash != nil {
		p.Hash = *r.Hash
	}
	if r.From != nil {
		p.From = *r.From
	}
	if r.To != nil {
		p.To = wrapperspb.String(*r.To)
	}
	p.Nonce = r.Nonce
	p.GasPrice = r.GasPrice
	p.Gas = r.Gas
	if r.GasTipCap != nil {
		p.GasTipCap = wrapperspb.String(*r.GasTipCap)
	}
	if r.GasFeeCap != nil {
		p.GasFeeCap = wrapperspb.String(*r.GasFeeCap)
	}
	p.Value = r.Value
	p.Type = r.Type
	p.Size = r.Size
	p.CallDataSize = r.CallDataSize
	if r.BlobGas != nil {
		p.BlobGas = wrapperspb.UInt64(*r.BlobGas)
	}
	if r.BlobGasFeeCap != nil {
		p.BlobGasFeeCap = wrapperspb.String(*r.BlobGasFeeCap)
	}
	p.BlobHashes = r.BlobHashes
	p.Success = r.Success
	p.NInputBytes = r.NInputBytes
	p.NInputZeroBytes = r.NInputZeroBytes
	p.NInputNonzeroBytes = r.NInputNonzeroBytes
	p.MetaNetworkName = r.MetaNetworkName
	return p
}
