// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for libp2p_connected

package clickhouse

import (
	"fmt"
)

// BuildListLibp2PConnectedQuery constructs a parameterized SQL query from a ListLibp2PConnectedRequest
func BuildListLibp2PConnectedQuery(req *ListLibp2PConnectedRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.MetaNetworkName == nil {
		return SQLQuery{}, fmt.Errorf("primary key field meta_network_name is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.MetaNetworkName.Filter.(type) {
	case *StringFilter_Eq:
		qb.AddCondition("meta_network_name", "=", filter.Eq)
	case *StringFilter_Ne:
		qb.AddCondition("meta_network_name", "!=", filter.Ne)
	case *StringFilter_Contains:
		qb.AddLikeCondition("meta_network_name", "%" + filter.Contains + "%")
	case *StringFilter_StartsWith:
		qb.AddLikeCondition("meta_network_name", filter.StartsWith + "%")
	case *StringFilter_EndsWith:
		qb.AddLikeCondition("meta_network_name", "%" + filter.EndsWith)
	case *StringFilter_Like:
		qb.AddLikeCondition("meta_network_name", filter.Like)
	case *StringFilter_NotLike:
		qb.AddNotLikeCondition("meta_network_name", filter.NotLike)
	case *StringFilter_In:
		if len(filter.In.Values) > 0 {
			qb.AddInCondition("meta_network_name", StringSliceToInterface(filter.In.Values))
		}
	case *StringFilter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			qb.AddNotInCondition("meta_network_name", StringSliceToInterface(filter.NotIn.Values))
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: event_date_time
	if req.EventDateTime != nil {
		switch filter := req.EventDateTime.Filter.(type) {
		case *Int64Filter_Eq:
			qb.AddCondition("event_date_time", "=", DateTime64Value{uint64(filter.Eq)})
		case *Int64Filter_Ne:
			qb.AddCondition("event_date_time", "!=", DateTime64Value{uint64(filter.Ne)})
		case *Int64Filter_Lt:
			qb.AddCondition("event_date_time", "<", DateTime64Value{uint64(filter.Lt)})
		case *Int64Filter_Lte:
			qb.AddCondition("event_date_time", "<=", DateTime64Value{uint64(filter.Lte)})
		case *Int64Filter_Gt:
			qb.AddCondition("event_date_time", ">", DateTime64Value{uint64(filter.Gt)})
		case *Int64Filter_Gte:
			qb.AddCondition("event_date_time", ">=", DateTime64Value{uint64(filter.Gte)})
		case *Int64Filter_Between:
			qb.AddBetweenCondition("event_date_time", DateTime64Value{uint64(filter.Between.Min)}, DateTime64Value{uint64(filter.Between.Max.GetValue())})
		case *Int64Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTime64Value{uint64(v)}
				}
				qb.AddInCondition("event_date_time", converted)
			}
		case *Int64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTime64Value{uint64(v)}
				}
				qb.AddNotInCondition("event_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: remote_peer_id_unique_key
	if req.RemotePeerIdUniqueKey != nil {
		switch filter := req.RemotePeerIdUniqueKey.Filter.(type) {
		case *Int64Filter_Eq:
			qb.AddCondition("remote_peer_id_unique_key", "=", filter.Eq)
		case *Int64Filter_Ne:
			qb.AddCondition("remote_peer_id_unique_key", "!=", filter.Ne)
		case *Int64Filter_Lt:
			qb.AddCondition("remote_peer_id_unique_key", "<", filter.Lt)
		case *Int64Filter_Lte:
			qb.AddCondition("remote_peer_id_unique_key", "<=", filter.Lte)
		case *Int64Filter_Gt:
			qb.AddCondition("remote_peer_id_unique_key", ">", filter.Gt)
		case *Int64Filter_Gte:
			qb.AddCondition("remote_peer_id_unique_key", ">=", filter.Gte)
		case *Int64Filter_Between:
			qb.AddBetweenCondition("remote_peer_id_unique_key", filter.Between.Min, filter.Between.Max.GetValue())
		case *Int64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("remote_peer_id_unique_key", Int64SliceToInterface(filter.In.Values))
			}
		case *Int64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("remote_peer_id_unique_key", Int64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: remote_protocol
	if req.RemoteProtocol != nil {
		switch filter := req.RemoteProtocol.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("remote_protocol", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("remote_protocol", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("remote_protocol", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("remote_protocol", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("remote_protocol", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("remote_protocol", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("remote_protocol", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("remote_protocol", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("remote_protocol", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: remote_transport_protocol
	if req.RemoteTransportProtocol != nil {
		switch filter := req.RemoteTransportProtocol.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("remote_transport_protocol", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("remote_transport_protocol", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("remote_transport_protocol", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("remote_transport_protocol", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("remote_transport_protocol", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("remote_transport_protocol", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("remote_transport_protocol", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("remote_transport_protocol", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("remote_transport_protocol", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: remote_port
	if req.RemotePort != nil {
		switch filter := req.RemotePort.Filter.(type) {
		case *NullableUInt32Filter_Eq:
			qb.AddCondition("remote_port", "=", filter.Eq)
		case *NullableUInt32Filter_Ne:
			qb.AddCondition("remote_port", "!=", filter.Ne)
		case *NullableUInt32Filter_Lt:
			qb.AddCondition("remote_port", "<", filter.Lt)
		case *NullableUInt32Filter_Lte:
			qb.AddCondition("remote_port", "<=", filter.Lte)
		case *NullableUInt32Filter_Gt:
			qb.AddCondition("remote_port", ">", filter.Gt)
		case *NullableUInt32Filter_Gte:
			qb.AddCondition("remote_port", ">=", filter.Gte)
		case *NullableUInt32Filter_Between:
			qb.AddBetweenCondition("remote_port", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("remote_port", UInt32SliceToInterface(filter.In.Values))
			}
		case *NullableUInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("remote_port", UInt32SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt32Filter_IsNull:
			qb.AddIsNullCondition("remote_port")
		case *NullableUInt32Filter_IsNotNull:
			qb.AddIsNotNullCondition("remote_port")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: remote_ip
	if req.RemoteIp != nil {
		switch filter := req.RemoteIp.Filter.(type) {
		case *NullableStringFilter_Eq:
			qb.AddCondition("remote_ip", "=", filter.Eq)
		case *NullableStringFilter_Ne:
			qb.AddCondition("remote_ip", "!=", filter.Ne)
		case *NullableStringFilter_Contains:
			qb.AddLikeCondition("remote_ip", "%" + filter.Contains + "%")
		case *NullableStringFilter_StartsWith:
			qb.AddLikeCondition("remote_ip", filter.StartsWith + "%")
		case *NullableStringFilter_EndsWith:
			qb.AddLikeCondition("remote_ip", "%" + filter.EndsWith)
		case *NullableStringFilter_Like:
			qb.AddLikeCondition("remote_ip", filter.Like)
		case *NullableStringFilter_NotLike:
			qb.AddNotLikeCondition("remote_ip", filter.NotLike)
		case *NullableStringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("remote_ip", StringSliceToInterface(filter.In.Values))
			}
		case *NullableStringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("remote_ip", StringSliceToInterface(filter.NotIn.Values))
			}
		case *NullableStringFilter_IsNull:
			qb.AddIsNullCondition("remote_ip")
		case *NullableStringFilter_IsNotNull:
			qb.AddIsNotNullCondition("remote_ip")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: remote_geo_city
	if req.RemoteGeoCity != nil {
		switch filter := req.RemoteGeoCity.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("remote_geo_city", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("remote_geo_city", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("remote_geo_city", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("remote_geo_city", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("remote_geo_city", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("remote_geo_city", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("remote_geo_city", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("remote_geo_city", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("remote_geo_city", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: remote_geo_country
	if req.RemoteGeoCountry != nil {
		switch filter := req.RemoteGeoCountry.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("remote_geo_country", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("remote_geo_country", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("remote_geo_country", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("remote_geo_country", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("remote_geo_country", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("remote_geo_country", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("remote_geo_country", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("remote_geo_country", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("remote_geo_country", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: remote_geo_country_code
	if req.RemoteGeoCountryCode != nil {
		switch filter := req.RemoteGeoCountryCode.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("remote_geo_country_code", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("remote_geo_country_code", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("remote_geo_country_code", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("remote_geo_country_code", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("remote_geo_country_code", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("remote_geo_country_code", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("remote_geo_country_code", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("remote_geo_country_code", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("remote_geo_country_code", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: remote_geo_continent_code
	if req.RemoteGeoContinentCode != nil {
		switch filter := req.RemoteGeoContinentCode.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("remote_geo_continent_code", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("remote_geo_continent_code", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("remote_geo_continent_code", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("remote_geo_continent_code", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("remote_geo_continent_code", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("remote_geo_continent_code", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("remote_geo_continent_code", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("remote_geo_continent_code", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("remote_geo_continent_code", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: remote_geo_longitude

	// Add filter for column: remote_geo_latitude

	// Add filter for column: remote_geo_autonomous_system_number
	if req.RemoteGeoAutonomousSystemNumber != nil {
		switch filter := req.RemoteGeoAutonomousSystemNumber.Filter.(type) {
		case *NullableUInt32Filter_Eq:
			qb.AddCondition("remote_geo_autonomous_system_number", "=", filter.Eq)
		case *NullableUInt32Filter_Ne:
			qb.AddCondition("remote_geo_autonomous_system_number", "!=", filter.Ne)
		case *NullableUInt32Filter_Lt:
			qb.AddCondition("remote_geo_autonomous_system_number", "<", filter.Lt)
		case *NullableUInt32Filter_Lte:
			qb.AddCondition("remote_geo_autonomous_system_number", "<=", filter.Lte)
		case *NullableUInt32Filter_Gt:
			qb.AddCondition("remote_geo_autonomous_system_number", ">", filter.Gt)
		case *NullableUInt32Filter_Gte:
			qb.AddCondition("remote_geo_autonomous_system_number", ">=", filter.Gte)
		case *NullableUInt32Filter_Between:
			qb.AddBetweenCondition("remote_geo_autonomous_system_number", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("remote_geo_autonomous_system_number", UInt32SliceToInterface(filter.In.Values))
			}
		case *NullableUInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("remote_geo_autonomous_system_number", UInt32SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt32Filter_IsNull:
			qb.AddIsNullCondition("remote_geo_autonomous_system_number")
		case *NullableUInt32Filter_IsNotNull:
			qb.AddIsNotNullCondition("remote_geo_autonomous_system_number")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: remote_geo_autonomous_system_organization
	if req.RemoteGeoAutonomousSystemOrganization != nil {
		switch filter := req.RemoteGeoAutonomousSystemOrganization.Filter.(type) {
		case *NullableStringFilter_Eq:
			qb.AddCondition("remote_geo_autonomous_system_organization", "=", filter.Eq)
		case *NullableStringFilter_Ne:
			qb.AddCondition("remote_geo_autonomous_system_organization", "!=", filter.Ne)
		case *NullableStringFilter_Contains:
			qb.AddLikeCondition("remote_geo_autonomous_system_organization", "%" + filter.Contains + "%")
		case *NullableStringFilter_StartsWith:
			qb.AddLikeCondition("remote_geo_autonomous_system_organization", filter.StartsWith + "%")
		case *NullableStringFilter_EndsWith:
			qb.AddLikeCondition("remote_geo_autonomous_system_organization", "%" + filter.EndsWith)
		case *NullableStringFilter_Like:
			qb.AddLikeCondition("remote_geo_autonomous_system_organization", filter.Like)
		case *NullableStringFilter_NotLike:
			qb.AddNotLikeCondition("remote_geo_autonomous_system_organization", filter.NotLike)
		case *NullableStringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("remote_geo_autonomous_system_organization", StringSliceToInterface(filter.In.Values))
			}
		case *NullableStringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("remote_geo_autonomous_system_organization", StringSliceToInterface(filter.NotIn.Values))
			}
		case *NullableStringFilter_IsNull:
			qb.AddIsNullCondition("remote_geo_autonomous_system_organization")
		case *NullableStringFilter_IsNotNull:
			qb.AddIsNotNullCondition("remote_geo_autonomous_system_organization")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: remote_agent_implementation
	if req.RemoteAgentImplementation != nil {
		switch filter := req.RemoteAgentImplementation.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("remote_agent_implementation", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("remote_agent_implementation", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("remote_agent_implementation", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("remote_agent_implementation", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("remote_agent_implementation", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("remote_agent_implementation", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("remote_agent_implementation", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("remote_agent_implementation", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("remote_agent_implementation", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: remote_agent_version
	if req.RemoteAgentVersion != nil {
		switch filter := req.RemoteAgentVersion.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("remote_agent_version", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("remote_agent_version", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("remote_agent_version", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("remote_agent_version", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("remote_agent_version", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("remote_agent_version", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("remote_agent_version", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("remote_agent_version", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("remote_agent_version", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: remote_agent_version_major
	if req.RemoteAgentVersionMajor != nil {
		switch filter := req.RemoteAgentVersionMajor.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("remote_agent_version_major", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("remote_agent_version_major", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("remote_agent_version_major", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("remote_agent_version_major", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("remote_agent_version_major", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("remote_agent_version_major", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("remote_agent_version_major", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("remote_agent_version_major", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("remote_agent_version_major", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: remote_agent_version_minor
	if req.RemoteAgentVersionMinor != nil {
		switch filter := req.RemoteAgentVersionMinor.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("remote_agent_version_minor", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("remote_agent_version_minor", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("remote_agent_version_minor", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("remote_agent_version_minor", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("remote_agent_version_minor", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("remote_agent_version_minor", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("remote_agent_version_minor", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("remote_agent_version_minor", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("remote_agent_version_minor", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: remote_agent_version_patch
	if req.RemoteAgentVersionPatch != nil {
		switch filter := req.RemoteAgentVersionPatch.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("remote_agent_version_patch", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("remote_agent_version_patch", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("remote_agent_version_patch", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("remote_agent_version_patch", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("remote_agent_version_patch", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("remote_agent_version_patch", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("remote_agent_version_patch", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("remote_agent_version_patch", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("remote_agent_version_patch", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: remote_agent_platform
	if req.RemoteAgentPlatform != nil {
		switch filter := req.RemoteAgentPlatform.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("remote_agent_platform", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("remote_agent_platform", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("remote_agent_platform", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("remote_agent_platform", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("remote_agent_platform", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("remote_agent_platform", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("remote_agent_platform", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("remote_agent_platform", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("remote_agent_platform", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: direction
	if req.Direction != nil {
		switch filter := req.Direction.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("direction", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("direction", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("direction", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("direction", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("direction", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("direction", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("direction", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("direction", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("direction", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: opened
	if req.Opened != nil {
		switch filter := req.Opened.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("opened", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("opened", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("opened", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("opened", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("opened", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("opened", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("opened", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("opened", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("opened", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: transient
	if req.Transient != nil {
		switch filter := req.Transient.Filter.(type) {
		case *BoolFilter_Eq:
			qb.AddCondition("transient", "=", filter.Eq)
		case *BoolFilter_Ne:
			qb.AddCondition("transient", "!=", filter.Ne)
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_name
	if req.MetaClientName != nil {
		switch filter := req.MetaClientName.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_name", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_name", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_name", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_name", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_name", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_name", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_name", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_name", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_name", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_version
	if req.MetaClientVersion != nil {
		switch filter := req.MetaClientVersion.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_version", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_version", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_version", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_version", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_version", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_version", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_version", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_version", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_version", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_implementation
	if req.MetaClientImplementation != nil {
		switch filter := req.MetaClientImplementation.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_implementation", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_implementation", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_implementation", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_implementation", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_implementation", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_implementation", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_implementation", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_implementation", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_implementation", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_os
	if req.MetaClientOs != nil {
		switch filter := req.MetaClientOs.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_os", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_os", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_os", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_os", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_os", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_os", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_os", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_os", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_os", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_ip
	if req.MetaClientIp != nil {
		switch filter := req.MetaClientIp.Filter.(type) {
		case *NullableStringFilter_Eq:
			qb.AddCondition("meta_client_ip", "=", filter.Eq)
		case *NullableStringFilter_Ne:
			qb.AddCondition("meta_client_ip", "!=", filter.Ne)
		case *NullableStringFilter_Contains:
			qb.AddLikeCondition("meta_client_ip", "%" + filter.Contains + "%")
		case *NullableStringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_ip", filter.StartsWith + "%")
		case *NullableStringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_ip", "%" + filter.EndsWith)
		case *NullableStringFilter_Like:
			qb.AddLikeCondition("meta_client_ip", filter.Like)
		case *NullableStringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_ip", filter.NotLike)
		case *NullableStringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_ip", StringSliceToInterface(filter.In.Values))
			}
		case *NullableStringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_ip", StringSliceToInterface(filter.NotIn.Values))
			}
		case *NullableStringFilter_IsNull:
			qb.AddIsNullCondition("meta_client_ip")
		case *NullableStringFilter_IsNotNull:
			qb.AddIsNotNullCondition("meta_client_ip")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_city
	if req.MetaClientGeoCity != nil {
		switch filter := req.MetaClientGeoCity.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_geo_city", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_geo_city", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_geo_city", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_geo_city", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_geo_city", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_geo_city", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_geo_city", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_city", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_city", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_country
	if req.MetaClientGeoCountry != nil {
		switch filter := req.MetaClientGeoCountry.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_geo_country", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_geo_country", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_geo_country", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_geo_country", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_geo_country", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_geo_country", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_geo_country", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_country", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_country", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_country_code
	if req.MetaClientGeoCountryCode != nil {
		switch filter := req.MetaClientGeoCountryCode.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_geo_country_code", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_geo_country_code", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_geo_country_code", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_geo_country_code", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_geo_country_code", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_geo_country_code", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_geo_country_code", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_country_code", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_country_code", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_continent_code
	if req.MetaClientGeoContinentCode != nil {
		switch filter := req.MetaClientGeoContinentCode.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_geo_continent_code", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_geo_continent_code", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_geo_continent_code", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_geo_continent_code", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_geo_continent_code", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_geo_continent_code", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_geo_continent_code", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_continent_code", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_continent_code", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_longitude

	// Add filter for column: meta_client_geo_latitude

	// Add filter for column: meta_client_geo_autonomous_system_number
	if req.MetaClientGeoAutonomousSystemNumber != nil {
		switch filter := req.MetaClientGeoAutonomousSystemNumber.Filter.(type) {
		case *NullableUInt32Filter_Eq:
			qb.AddCondition("meta_client_geo_autonomous_system_number", "=", filter.Eq)
		case *NullableUInt32Filter_Ne:
			qb.AddCondition("meta_client_geo_autonomous_system_number", "!=", filter.Ne)
		case *NullableUInt32Filter_Lt:
			qb.AddCondition("meta_client_geo_autonomous_system_number", "<", filter.Lt)
		case *NullableUInt32Filter_Lte:
			qb.AddCondition("meta_client_geo_autonomous_system_number", "<=", filter.Lte)
		case *NullableUInt32Filter_Gt:
			qb.AddCondition("meta_client_geo_autonomous_system_number", ">", filter.Gt)
		case *NullableUInt32Filter_Gte:
			qb.AddCondition("meta_client_geo_autonomous_system_number", ">=", filter.Gte)
		case *NullableUInt32Filter_Between:
			qb.AddBetweenCondition("meta_client_geo_autonomous_system_number", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_autonomous_system_number", UInt32SliceToInterface(filter.In.Values))
			}
		case *NullableUInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_autonomous_system_number", UInt32SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt32Filter_IsNull:
			qb.AddIsNullCondition("meta_client_geo_autonomous_system_number")
		case *NullableUInt32Filter_IsNotNull:
			qb.AddIsNotNullCondition("meta_client_geo_autonomous_system_number")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_autonomous_system_organization
	if req.MetaClientGeoAutonomousSystemOrganization != nil {
		switch filter := req.MetaClientGeoAutonomousSystemOrganization.Filter.(type) {
		case *NullableStringFilter_Eq:
			qb.AddCondition("meta_client_geo_autonomous_system_organization", "=", filter.Eq)
		case *NullableStringFilter_Ne:
			qb.AddCondition("meta_client_geo_autonomous_system_organization", "!=", filter.Ne)
		case *NullableStringFilter_Contains:
			qb.AddLikeCondition("meta_client_geo_autonomous_system_organization", "%" + filter.Contains + "%")
		case *NullableStringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_geo_autonomous_system_organization", filter.StartsWith + "%")
		case *NullableStringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_geo_autonomous_system_organization", "%" + filter.EndsWith)
		case *NullableStringFilter_Like:
			qb.AddLikeCondition("meta_client_geo_autonomous_system_organization", filter.Like)
		case *NullableStringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_geo_autonomous_system_organization", filter.NotLike)
		case *NullableStringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_autonomous_system_organization", StringSliceToInterface(filter.In.Values))
			}
		case *NullableStringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_autonomous_system_organization", StringSliceToInterface(filter.NotIn.Values))
			}
		case *NullableStringFilter_IsNull:
			qb.AddIsNullCondition("meta_client_geo_autonomous_system_organization")
		case *NullableStringFilter_IsNotNull:
			qb.AddIsNotNullCondition("meta_client_geo_autonomous_system_organization")
		default:
			// Unsupported filter type
		}
	}

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "event_date_time", "remote_peer_id_unique_key", "remote_protocol", "remote_transport_protocol", "remote_port", "remote_ip", "remote_geo_city", "remote_geo_country", "remote_geo_country_code", "remote_geo_continent_code", "remote_geo_longitude", "remote_geo_latitude", "remote_geo_autonomous_system_number", "remote_geo_autonomous_system_organization", "remote_agent_implementation", "remote_agent_version", "remote_agent_version_major", "remote_agent_version_minor", "remote_agent_version_patch", "remote_agent_platform", "direction", "opened", "transient", "meta_client_name", "meta_client_version", "meta_client_implementation", "meta_client_os", "meta_client_ip", "meta_client_geo_city", "meta_client_geo_country", "meta_client_geo_country_code", "meta_client_geo_continent_code", "meta_client_geo_longitude", "meta_client_geo_latitude", "meta_client_geo_autonomous_system_number", "meta_client_geo_autonomous_system_organization", "meta_network_name"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY meta_network_name" + ", event_date_time" + ", meta_client_name" + ", remote_peer_id_unique_key" + ", direction" + ", opened"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "toUnixTimestamp64Micro(`event_date_time`) AS `event_date_time`", "remote_peer_id_unique_key", "remote_protocol", "remote_transport_protocol", "toUInt32(`remote_port`) AS `remote_port`", "remote_ip", "remote_geo_city", "remote_geo_country", "remote_geo_country_code", "remote_geo_continent_code", "remote_geo_longitude", "remote_geo_latitude", "remote_geo_autonomous_system_number", "remote_geo_autonomous_system_organization", "remote_agent_implementation", "remote_agent_version", "remote_agent_version_major", "remote_agent_version_minor", "remote_agent_version_patch", "remote_agent_platform", "direction", "toUnixTimestamp(`opened`) AS `opened`", "transient", "meta_client_name", "meta_client_version", "meta_client_implementation", "meta_client_os", "meta_client_ip", "meta_client_geo_city", "meta_client_geo_country", "meta_client_geo_country_code", "meta_client_geo_continent_code", "meta_client_geo_longitude", "meta_client_geo_latitude", "meta_client_geo_autonomous_system_number", "meta_client_geo_autonomous_system_organization", "meta_network_name"}

	return BuildParameterizedQuery("libp2p_connected", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetLibp2PConnectedQuery constructs a parameterized SQL query from a GetLibp2PConnectedRequest
func BuildGetLibp2PConnectedQuery(req *GetLibp2PConnectedRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.MetaNetworkName == "" {
		return SQLQuery{}, fmt.Errorf("primary key field meta_network_name is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("meta_network_name", "=", req.MetaNetworkName)

	// Build ORDER BY clause
	orderByClause := " ORDER BY meta_network_name, event_date_time, meta_client_name, remote_peer_id_unique_key, direction, opened"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "toUnixTimestamp64Micro(`event_date_time`) AS `event_date_time`", "remote_peer_id_unique_key", "remote_protocol", "remote_transport_protocol", "toUInt32(`remote_port`) AS `remote_port`", "remote_ip", "remote_geo_city", "remote_geo_country", "remote_geo_country_code", "remote_geo_continent_code", "remote_geo_longitude", "remote_geo_latitude", "remote_geo_autonomous_system_number", "remote_geo_autonomous_system_organization", "remote_agent_implementation", "remote_agent_version", "remote_agent_version_major", "remote_agent_version_minor", "remote_agent_version_patch", "remote_agent_platform", "direction", "toUnixTimestamp(`opened`) AS `opened`", "transient", "meta_client_name", "meta_client_version", "meta_client_implementation", "meta_client_os", "meta_client_ip", "meta_client_geo_city", "meta_client_geo_country", "meta_client_geo_country_code", "meta_client_geo_continent_code", "meta_client_geo_longitude", "meta_client_geo_latitude", "meta_client_geo_autonomous_system_number", "meta_client_geo_autonomous_system_organization", "meta_network_name"}

	// Return single record
	return BuildParameterizedQuery("libp2p_connected", columns, qb, orderByClause, 1, 0, options...)
}
