// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: libp2p_peer.proto

package clickhouse

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Libp2PPeer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique identifier for each record, seahash of peer_id + meta_network_name
	UniqueKey int64 `protobuf:"varint,11,opt,name=unique_key,json=uniqueKey,proto3" json:"unique_key,omitempty"`
	// Timestamp when the record was last updated
	UpdatedDateTime uint32 `protobuf:"varint,12,opt,name=updated_date_time,json=updatedDateTime,proto3" json:"updated_date_time,omitempty"`
	// Peer ID
	PeerId string `protobuf:"bytes,13,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// Ethereum network name
	MetaNetworkName string `protobuf:"bytes,14,opt,name=meta_network_name,json=metaNetworkName,proto3" json:"meta_network_name,omitempty"`
}

func (x *Libp2PPeer) Reset() {
	*x = Libp2PPeer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libp2p_peer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Libp2PPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Libp2PPeer) ProtoMessage() {}

func (x *Libp2PPeer) ProtoReflect() protoreflect.Message {
	mi := &file_libp2p_peer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Libp2PPeer.ProtoReflect.Descriptor instead.
func (*Libp2PPeer) Descriptor() ([]byte, []int) {
	return file_libp2p_peer_proto_rawDescGZIP(), []int{0}
}

func (x *Libp2PPeer) GetUniqueKey() int64 {
	if x != nil {
		return x.UniqueKey
	}
	return 0
}

func (x *Libp2PPeer) GetUpdatedDateTime() uint32 {
	if x != nil {
		return x.UpdatedDateTime
	}
	return 0
}

func (x *Libp2PPeer) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Libp2PPeer) GetMetaNetworkName() string {
	if x != nil {
		return x.MetaNetworkName
	}
	return ""
}

// Request for listing libp2p_peer records
type ListLibp2PPeerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Filter by unique_key - Unique identifier for each record, seahash of peer_id + meta_network_name (PRIMARY KEY - required)
	UniqueKey *Int64Filter `protobuf:"bytes,1,opt,name=unique_key,json=uniqueKey,proto3" json:"unique_key,omitempty"`
	// Filter by updated_date_time - Timestamp when the record was last updated (optional)
	UpdatedDateTime *UInt32Filter `protobuf:"bytes,2,opt,name=updated_date_time,json=updatedDateTime,proto3" json:"updated_date_time,omitempty"`
	// Filter by peer_id - Peer ID (optional)
	PeerId *StringFilter `protobuf:"bytes,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// Filter by meta_network_name - Ethereum network name (optional)
	MetaNetworkName *StringFilter `protobuf:"bytes,4,opt,name=meta_network_name,json=metaNetworkName,proto3" json:"meta_network_name,omitempty"`
	// The maximum number of libp2p_peer to return.
	// If unspecified, at most 100 items will be returned.
	// The maximum value is 10000; values above 10000 will be coerced to 10000.
	PageSize int32 `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token, received from a previous `ListLibp2pPeer` call.
	// Provide this to retrieve the subsequent page.
	PageToken string `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// The order of results. Format: comma-separated list of fields.
	// Example: "foo,bar" or "foo desc,bar" for descending order on foo.
	// If unspecified, results will be returned in the default order.
	OrderBy string `protobuf:"bytes,7,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
}

func (x *ListLibp2PPeerRequest) Reset() {
	*x = ListLibp2PPeerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libp2p_peer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLibp2PPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLibp2PPeerRequest) ProtoMessage() {}

func (x *ListLibp2PPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libp2p_peer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLibp2PPeerRequest.ProtoReflect.Descriptor instead.
func (*ListLibp2PPeerRequest) Descriptor() ([]byte, []int) {
	return file_libp2p_peer_proto_rawDescGZIP(), []int{1}
}

func (x *ListLibp2PPeerRequest) GetUniqueKey() *Int64Filter {
	if x != nil {
		return x.UniqueKey
	}
	return nil
}

func (x *ListLibp2PPeerRequest) GetUpdatedDateTime() *UInt32Filter {
	if x != nil {
		return x.UpdatedDateTime
	}
	return nil
}

func (x *ListLibp2PPeerRequest) GetPeerId() *StringFilter {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *ListLibp2PPeerRequest) GetMetaNetworkName() *StringFilter {
	if x != nil {
		return x.MetaNetworkName
	}
	return nil
}

func (x *ListLibp2PPeerRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLibp2PPeerRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListLibp2PPeerRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

// Response for listing libp2p_peer records
type ListLibp2PPeerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The list of libp2p_peer.
	Libp2PPeer []*Libp2PPeer `protobuf:"bytes,1,rep,name=libp2p_peer,json=libp2pPeer,proto3" json:"libp2p_peer,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page.
	// If this field is omitted, there are no subsequent pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
}

func (x *ListLibp2PPeerResponse) Reset() {
	*x = ListLibp2PPeerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libp2p_peer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLibp2PPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLibp2PPeerResponse) ProtoMessage() {}

func (x *ListLibp2PPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libp2p_peer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLibp2PPeerResponse.ProtoReflect.Descriptor instead.
func (*ListLibp2PPeerResponse) Descriptor() ([]byte, []int) {
	return file_libp2p_peer_proto_rawDescGZIP(), []int{2}
}

func (x *ListLibp2PPeerResponse) GetLibp2PPeer() []*Libp2PPeer {
	if x != nil {
		return x.Libp2PPeer
	}
	return nil
}

func (x *ListLibp2PPeerResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Request for getting a single libp2p_peer record by primary key
type GetLibp2PPeerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique identifier for each record, seahash of peer_id + meta_network_name
	UniqueKey int64 `protobuf:"varint,1,opt,name=unique_key,json=uniqueKey,proto3" json:"unique_key,omitempty"` // Primary key (required)
}

func (x *GetLibp2PPeerRequest) Reset() {
	*x = GetLibp2PPeerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libp2p_peer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLibp2PPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLibp2PPeerRequest) ProtoMessage() {}

func (x *GetLibp2PPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libp2p_peer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLibp2PPeerRequest.ProtoReflect.Descriptor instead.
func (*GetLibp2PPeerRequest) Descriptor() ([]byte, []int) {
	return file_libp2p_peer_proto_rawDescGZIP(), []int{3}
}

func (x *GetLibp2PPeerRequest) GetUniqueKey() int64 {
	if x != nil {
		return x.UniqueKey
	}
	return 0
}

// Response for getting a single libp2p_peer record
type GetLibp2PPeerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Libp2PPeer `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *GetLibp2PPeerResponse) Reset() {
	*x = GetLibp2PPeerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libp2p_peer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLibp2PPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLibp2PPeerResponse) ProtoMessage() {}

func (x *GetLibp2PPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libp2p_peer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLibp2PPeerResponse.ProtoReflect.Descriptor instead.
func (*GetLibp2PPeerResponse) Descriptor() ([]byte, []int) {
	return file_libp2p_peer_proto_rawDescGZIP(), []int{4}
}

func (x *GetLibp2PPeerResponse) GetItem() *Libp2PPeer {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_libp2p_peer_proto protoreflect.FileDescriptor

var file_libp2p_peer_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6c, 0x69, 0x62, 0x70, 0x32, 0x70, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e,
	0x76, 0x31, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x9c, 0x01, 0x0a, 0x0a, 0x4c, 0x69, 0x62, 0x70, 0x32, 0x70, 0x50, 0x65, 0x65, 0x72, 0x12,
	0x1d, 0x0a, 0x0a, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x2a,
	0x0a, 0x11, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x6d, 0x65, 0x74, 0x61, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0xf1, 0x02, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x69, 0x62, 0x70, 0x32, 0x70, 0x50, 0x65,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x63, 0x6c, 0x69, 0x63, 0x6b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e,
	0x74, 0x36, 0x34, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x09, 0x75, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x4b, 0x65, 0x79, 0x12, 0x47, 0x0a, 0x11, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x0f, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x34, 0x0a,
	0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x70, 0x65, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x47, 0x0a, 0x11, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x0f, 0x6d, 0x65, 0x74,
	0x61, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x67,
	0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x5f, 0x62, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x42, 0x79, 0x22, 0x7c, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x69, 0x62, 0x70, 0x32,
	0x70, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a,
	0x0b, 0x6c, 0x69, 0x62, 0x70, 0x32, 0x70, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x62, 0x70, 0x32, 0x70, 0x50, 0x65, 0x65, 0x72, 0x52, 0x0a, 0x6c,
	0x69, 0x62, 0x70, 0x32, 0x70, 0x50, 0x65, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x65, 0x78,
	0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x35, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x62, 0x70, 0x32, 0x70, 0x50, 0x65,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x46, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x62, 0x70, 0x32, 0x70, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2d, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x62, 0x70, 0x32, 0x70, 0x50, 0x65, 0x65, 0x72, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d,
	0x32, 0xba, 0x01, 0x0a, 0x11, 0x4c, 0x69, 0x62, 0x70, 0x32, 0x70, 0x50, 0x65, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24,
	0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x4c, 0x69, 0x62, 0x70, 0x32, 0x70, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x69, 0x62, 0x70, 0x32, 0x70, 0x50,
	0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x03, 0x47,
	0x65, 0x74, 0x12, 0x23, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x62, 0x70, 0x32, 0x70, 0x50, 0x65, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x68,
	0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x62, 0x70, 0x32,
	0x70, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x32, 0x5a,
	0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x74, 0x68, 0x70,
	0x61, 0x6e, 0x64, 0x61, 0x6f, 0x70, 0x73, 0x2f, 0x78, 0x61, 0x74, 0x75, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x63, 0x6b, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_libp2p_peer_proto_rawDescOnce sync.Once
	file_libp2p_peer_proto_rawDescData = file_libp2p_peer_proto_rawDesc
)

func file_libp2p_peer_proto_rawDescGZIP() []byte {
	file_libp2p_peer_proto_rawDescOnce.Do(func() {
		file_libp2p_peer_proto_rawDescData = protoimpl.X.CompressGZIP(file_libp2p_peer_proto_rawDescData)
	})
	return file_libp2p_peer_proto_rawDescData
}

var file_libp2p_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_libp2p_peer_proto_goTypes = []any{
	(*Libp2PPeer)(nil),             // 0: clickhouse.v1.Libp2pPeer
	(*ListLibp2PPeerRequest)(nil),  // 1: clickhouse.v1.ListLibp2pPeerRequest
	(*ListLibp2PPeerResponse)(nil), // 2: clickhouse.v1.ListLibp2pPeerResponse
	(*GetLibp2PPeerRequest)(nil),   // 3: clickhouse.v1.GetLibp2pPeerRequest
	(*GetLibp2PPeerResponse)(nil),  // 4: clickhouse.v1.GetLibp2pPeerResponse
	(*Int64Filter)(nil),            // 5: clickhouse.v1.Int64Filter
	(*UInt32Filter)(nil),           // 6: clickhouse.v1.UInt32Filter
	(*StringFilter)(nil),           // 7: clickhouse.v1.StringFilter
}
var file_libp2p_peer_proto_depIdxs = []int32{
	5, // 0: clickhouse.v1.ListLibp2pPeerRequest.unique_key:type_name -> clickhouse.v1.Int64Filter
	6, // 1: clickhouse.v1.ListLibp2pPeerRequest.updated_date_time:type_name -> clickhouse.v1.UInt32Filter
	7, // 2: clickhouse.v1.ListLibp2pPeerRequest.peer_id:type_name -> clickhouse.v1.StringFilter
	7, // 3: clickhouse.v1.ListLibp2pPeerRequest.meta_network_name:type_name -> clickhouse.v1.StringFilter
	0, // 4: clickhouse.v1.ListLibp2pPeerResponse.libp2p_peer:type_name -> clickhouse.v1.Libp2pPeer
	0, // 5: clickhouse.v1.GetLibp2pPeerResponse.item:type_name -> clickhouse.v1.Libp2pPeer
	1, // 6: clickhouse.v1.Libp2pPeerService.List:input_type -> clickhouse.v1.ListLibp2pPeerRequest
	3, // 7: clickhouse.v1.Libp2pPeerService.Get:input_type -> clickhouse.v1.GetLibp2pPeerRequest
	2, // 8: clickhouse.v1.Libp2pPeerService.List:output_type -> clickhouse.v1.ListLibp2pPeerResponse
	4, // 9: clickhouse.v1.Libp2pPeerService.Get:output_type -> clickhouse.v1.GetLibp2pPeerResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_libp2p_peer_proto_init() }
func file_libp2p_peer_proto_init() {
	if File_libp2p_peer_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_libp2p_peer_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Libp2PPeer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libp2p_peer_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ListLibp2PPeerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libp2p_peer_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListLibp2PPeerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libp2p_peer_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetLibp2PPeerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libp2p_peer_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetLibp2PPeerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_libp2p_peer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_libp2p_peer_proto_goTypes,
		DependencyIndexes: file_libp2p_peer_proto_depIdxs,
		MessageInfos:      file_libp2p_peer_proto_msgTypes,
	}.Build()
	File_libp2p_peer_proto = out.File
	file_libp2p_peer_proto_rawDesc = nil
	file_libp2p_peer_proto_goTypes = nil
	file_libp2p_peer_proto_depIdxs = nil
}
