syntax = "proto3";

package clickhouse.v1;

import "common.proto";
import "google/protobuf/wrappers.proto";

option go_package = "github.com/ethpandaops/xatu/pkg/proto/clickhouse";
// Contains the details of the "Graft" control messages from the peer.

message Libp2pRpcMetaControlGraft {
  // Unique identifier for each "Graft" control record
  int64 unique_key = 11;
  // Timestamp when the "Graft" control record was last updated
  uint32 updated_date_time = 12;
  // Timestamp of the "Graft" control event
  int64 event_date_time = 13;
  // Position in the RPC meta control GRAFT array
  int32 control_index = 14;
  // Unique key associated with the "Graft" control metadata
  int64 rpc_meta_unique_key = 15;
  // Layer of the topic
  string topic_layer = 16;
  // Fork digest value of the topic
  string topic_fork_digest_value = 17;
  // Name of the topic
  string topic_name = 18;
  // Encoding of the topic
  string topic_encoding = 19;
  // Unique key associated with the identifier of the peer involved in the Graft control
  int64 peer_id_unique_key = 20;
  // Name of the client that generated the event
  string meta_client_name = 21;
  // Version of the client that generated the event
  string meta_client_version = 22;
  // Implementation of the client that generated the event
  string meta_client_implementation = 23;
  // Operating system of the client that generated the event
  string meta_client_os = 24;
  // IP address of the client that generated the event
  google.protobuf.StringValue meta_client_ip = 25;
  // City of the client that generated the event
  string meta_client_geo_city = 26;
  // Country of the client that generated the event
  string meta_client_geo_country = 27;
  // Country code of the client that generated the event
  string meta_client_geo_country_code = 28;
  // Continent code of the client that generated the event
  string meta_client_geo_continent_code = 29;
  // Longitude of the client that generated the event
  google.protobuf.DoubleValue meta_client_geo_longitude = 30;
  // Latitude of the client that generated the event
  google.protobuf.DoubleValue meta_client_geo_latitude = 31;
  // Autonomous system number of the client that generated the event
  google.protobuf.UInt32Value meta_client_geo_autonomous_system_number = 32;
  // Autonomous system organization of the client that generated the event
  google.protobuf.StringValue meta_client_geo_autonomous_system_organization = 33;
  // Ethereum network name
  string meta_network_name = 34;
}

// Request for listing libp2p_rpc_meta_control_graft records
message ListLibp2pRpcMetaControlGraftRequest {
  // Filter by meta_network_name - Ethereum network name (PRIMARY KEY - required)
  StringFilter meta_network_name = 1;

  // Filter by event_date_time - Timestamp of the "Graft" control event (ORDER BY column 2 - optional)
  Int64Filter event_date_time = 2;

  // Filter by unique_key - Unique identifier for each "Graft" control record (ORDER BY column 3 - optional)
  Int64Filter unique_key = 3;

  // Filter by control_index - Position in the RPC meta control GRAFT array (ORDER BY column 4 - optional)
  Int32Filter control_index = 4;

  // Filter by meta_client_name - Name of the client that generated the event (ORDER BY column 5 - optional)
  StringFilter meta_client_name = 5;

  // Filter by updated_date_time - Timestamp when the "Graft" control record was last updated (optional)
  UInt32Filter updated_date_time = 6;
  // Filter by rpc_meta_unique_key - Unique key associated with the "Graft" control metadata (optional)
  Int64Filter rpc_meta_unique_key = 7;
  // Filter by topic_layer - Layer of the topic (optional)
  StringFilter topic_layer = 8;
  // Filter by topic_fork_digest_value - Fork digest value of the topic (optional)
  StringFilter topic_fork_digest_value = 9;
  // Filter by topic_name - Name of the topic (optional)
  StringFilter topic_name = 10;
  // Filter by topic_encoding - Encoding of the topic (optional)
  StringFilter topic_encoding = 11;
  // Filter by peer_id_unique_key - Unique key associated with the identifier of the peer involved in the Graft control (optional)
  Int64Filter peer_id_unique_key = 12;
  // Filter by meta_client_version - Version of the client that generated the event (optional)
  StringFilter meta_client_version = 13;
  // Filter by meta_client_implementation - Implementation of the client that generated the event (optional)
  StringFilter meta_client_implementation = 14;
  // Filter by meta_client_os - Operating system of the client that generated the event (optional)
  StringFilter meta_client_os = 15;
  // Filter by meta_client_ip - IP address of the client that generated the event (optional)
  NullableStringFilter meta_client_ip = 16;
  // Filter by meta_client_geo_city - City of the client that generated the event (optional)
  StringFilter meta_client_geo_city = 17;
  // Filter by meta_client_geo_country - Country of the client that generated the event (optional)
  StringFilter meta_client_geo_country = 18;
  // Filter by meta_client_geo_country_code - Country code of the client that generated the event (optional)
  StringFilter meta_client_geo_country_code = 19;
  // Filter by meta_client_geo_continent_code - Continent code of the client that generated the event (optional)
  StringFilter meta_client_geo_continent_code = 20;
  // Filter by meta_client_geo_longitude - Longitude of the client that generated the event (optional)
  google.protobuf.DoubleValue meta_client_geo_longitude = 21;
  // Filter by meta_client_geo_latitude - Latitude of the client that generated the event (optional)
  google.protobuf.DoubleValue meta_client_geo_latitude = 22;
  // Filter by meta_client_geo_autonomous_system_number - Autonomous system number of the client that generated the event (optional)
  NullableUInt32Filter meta_client_geo_autonomous_system_number = 23;
  // Filter by meta_client_geo_autonomous_system_organization - Autonomous system organization of the client that generated the event (optional)
  NullableStringFilter meta_client_geo_autonomous_system_organization = 24;

  // The maximum number of libp2p_rpc_meta_control_graft to return.
  // If unspecified, at most 100 items will be returned.
  // The maximum value is 10000; values above 10000 will be coerced to 10000.
  int32 page_size = 25;
  // A page token, received from a previous `ListLibp2pRpcMetaControlGraft` call.
  // Provide this to retrieve the subsequent page.
  string page_token = 26;
  // The order of results. Format: comma-separated list of fields.
  // Example: "foo,bar" or "foo desc,bar" for descending order on foo.
  // If unspecified, results will be returned in the default order.
  string order_by = 27;
}

// Response for listing libp2p_rpc_meta_control_graft records
message ListLibp2pRpcMetaControlGraftResponse {
  // The list of libp2p_rpc_meta_control_graft.
  repeated Libp2pRpcMetaControlGraft libp2p_rpc_meta_control_graft = 1;
  // A token, which can be sent as `page_token` to retrieve the next page.
  // If this field is omitted, there are no subsequent pages.
  string next_page_token = 2;
}

// Request for getting a single libp2p_rpc_meta_control_graft record by primary key
message GetLibp2pRpcMetaControlGraftRequest {
  // Ethereum network name
  string meta_network_name = 1; // Primary key (required)
}

// Response for getting a single libp2p_rpc_meta_control_graft record
message GetLibp2pRpcMetaControlGraftResponse {
  Libp2pRpcMetaControlGraft item = 1;
}

// Query libp2p_rpc_meta_control_graft data
service Libp2pRpcMetaControlGraftService {
  // List records | Retrieve paginated results with optional filtering
  rpc List(ListLibp2pRpcMetaControlGraftRequest) returns (ListLibp2pRpcMetaControlGraftResponse);
  // Get record | Retrieve a single record by primary key
  rpc Get(GetLibp2pRpcMetaControlGraftRequest) returns (GetLibp2pRpcMetaControlGraftResponse);
}
