// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for libp2p_connected

package clickhouse

import (
	"net"

	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// Libp2PConnectedRow is a ClickHouse-scannable result row for the libp2p_connected table.
// Field types match the SELECT column expressions produced by
// BuildListLibp2PConnectedQuery and BuildGetLibp2PConnectedQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type Libp2PConnectedRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	EventDateTime int64 `ch:"event_date_time" json:"event_date_time"`
	RemotePeerIdUniqueKey int64 `ch:"remote_peer_id_unique_key" json:"remote_peer_id_unique_key"`
	RemoteProtocol string `ch:"remote_protocol" json:"remote_protocol"`
	RemoteTransportProtocol string `ch:"remote_transport_protocol" json:"remote_transport_protocol"`
	RemotePort *uint32 `ch:"remote_port" json:"remote_port"`
	RemoteIp *net.IP `ch:"remote_ip" json:"remote_ip"`
	RemoteGeoCity string `ch:"remote_geo_city" json:"remote_geo_city"`
	RemoteGeoCountry string `ch:"remote_geo_country" json:"remote_geo_country"`
	RemoteGeoCountryCode string `ch:"remote_geo_country_code" json:"remote_geo_country_code"`
	RemoteGeoContinentCode string `ch:"remote_geo_continent_code" json:"remote_geo_continent_code"`
	RemoteGeoLongitude *float64 `ch:"remote_geo_longitude" json:"remote_geo_longitude"`
	RemoteGeoLatitude *float64 `ch:"remote_geo_latitude" json:"remote_geo_latitude"`
	RemoteGeoAutonomousSystemNumber *uint32 `ch:"remote_geo_autonomous_system_number" json:"remote_geo_autonomous_system_number"`
	RemoteGeoAutonomousSystemOrganization *string `ch:"remote_geo_autonomous_system_organization" json:"remote_geo_autonomous_system_organization"`
	RemoteAgentImplementation string `ch:"remote_agent_implementation" json:"remote_agent_implementation"`
	RemoteAgentVersion string `ch:"remote_agent_version" json:"remote_agent_version"`
	RemoteAgentVersionMajor string `ch:"remote_agent_version_major" json:"remote_agent_version_major"`
	RemoteAgentVersionMinor string `ch:"remote_agent_version_minor" json:"remote_agent_version_minor"`
	RemoteAgentVersionPatch string `ch:"remote_agent_version_patch" json:"remote_agent_version_patch"`
	RemoteAgentPlatform string `ch:"remote_agent_platform" json:"remote_agent_platform"`
	Direction string `ch:"direction" json:"direction"`
	Opened uint32 `ch:"opened" json:"opened"`
	Transient bool `ch:"transient" json:"transient"`
	MetaClientName string `ch:"meta_client_name" json:"meta_client_name"`
	MetaClientVersion string `ch:"meta_client_version" json:"meta_client_version"`
	MetaClientImplementation string `ch:"meta_client_implementation" json:"meta_client_implementation"`
	MetaClientOs string `ch:"meta_client_os" json:"meta_client_os"`
	MetaClientIp *net.IP `ch:"meta_client_ip" json:"meta_client_ip"`
	MetaClientGeoCity string `ch:"meta_client_geo_city" json:"meta_client_geo_city"`
	MetaClientGeoCountry string `ch:"meta_client_geo_country" json:"meta_client_geo_country"`
	MetaClientGeoCountryCode string `ch:"meta_client_geo_country_code" json:"meta_client_geo_country_code"`
	MetaClientGeoContinentCode string `ch:"meta_client_geo_continent_code" json:"meta_client_geo_continent_code"`
	MetaClientGeoLongitude *float64 `ch:"meta_client_geo_longitude" json:"meta_client_geo_longitude"`
	MetaClientGeoLatitude *float64 `ch:"meta_client_geo_latitude" json:"meta_client_geo_latitude"`
	MetaClientGeoAutonomousSystemNumber *uint32 `ch:"meta_client_geo_autonomous_system_number" json:"meta_client_geo_autonomous_system_number"`
	MetaClientGeoAutonomousSystemOrganization *string `ch:"meta_client_geo_autonomous_system_organization" json:"meta_client_geo_autonomous_system_organization"`
	MetaNetworkName string `ch:"meta_network_name" json:"meta_network_name"`
}

// TableName returns the ClickHouse table this row maps to.
func (Libp2PConnectedRow) TableName() string {
	return "libp2p_connected"
}

// ToProto converts the row to its protobuf message.
func (r *Libp2PConnectedRow) ToProto() *Libp2PConnected {
	p := &Libp2PConnected{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.EventDateTime = r.EventDateTime
	p.RemotePeerIdUniqueKey = r.RemotePeerIdUniqueKey
	p.RemoteProtocol = r.RemoteProtocol
	p.RemoteTransportProtocol = r.RemoteTransportProtocol
	if r.RemotePort != nil {
		p.RemotePort = wrapperspb.UInt32(*r.RemotePort)
	}
	if r.RemoteIp != nil {
		p.RemoteIp = wrapperspb.String(r.RemoteIp.String())
	}
	p.RemoteGeoCity = r.RemoteGeoCity
	p.RemoteGeoCountry = r.RemoteGeoCountry
	p.RemoteGeoCountryCode = r.RemoteGeoCountryCode
	p.RemoteGeoContinentCode = r.RemoteGeoContinentCode
	if r.RemoteGeoLongitude != nil {
		p.RemoteGeoLongitude = wrapperspb.Double(*r.RemoteGeoLongitude)
	}
	if r.RemoteGeoLatitude != nil {
		p.RemoteGeoLatitude = wrapperspb.Double(*r.RemoteGeoLatitude)
	}
	if r.RemoteGeoAutonomousSystemNumber != nil {
		p.RemoteGeoAutonomousSystemNumber = wrapperspb.UInt32(*r.RemoteGeoAutonomousSystemNumber)
	}
	if r.RemoteGeoAutonomousSystemOrganization != nil {
		p.RemoteGeoAutonomousSystemOrganization = wrapperspb.String(*r.RemoteGeoAutonomousSystemOrganization)
	}
	p.RemoteAgentImplementation = r.RemoteAgentImplementation
	p.RemoteAgentVersion = r.RemoteAgentVersion
	p.RemoteAgentVersionMajor = r.RemoteAgentVersionMajor
	p.RemoteAgentVersionMinor = r.RemoteAgentVersionMinor
	p.RemoteAgentVersionPatch = r.RemoteAgentVersionPatch
	p.RemoteAgentPlatform = r.RemoteAgentPlatform
	p.Direction = r.Direction
	p.Opened = r.Opened
	p.Transient = r.Transient
	p.MetaClientName = r.MetaClientName
	p.MetaClientVersion = r.MetaClientVersion
	p.MetaClientImplementation = r.MetaClientImplementation
	p.MetaClientOs = r.MetaClientOs
	if r.MetaClientIp != nil {
		p.MetaClientIp = wrapperspb.String(r.MetaClientIp.String())
	}
	p.MetaClientGeoCity = r.MetaClientGeoCity
	p.MetaClientGeoCountry = r.MetaClientGeoCountry
	p.MetaClientGeoCountryCode = r.MetaClientGeoCountryCode
	p.MetaClientGeoContinentCode = r.MetaClientGeoContinentCode
	if r.MetaClientGeoLongitude != nil {
		p.MetaClientGeoLongitude = wrapperspb.Double(*r.MetaClientGeoLongitude)
	}
	if r.MetaClientGeoLatitude != nil {
		p.MetaClientGeoLatitude = wrapperspb.Double(*r.MetaClientGeoLatitude)
	}
	if r.MetaClientGeoAutonomousSystemNumber != nil {
		p.MetaClientGeoAutonomousSystemNumber = wrapperspb.UInt32(*r.MetaClientGeoAutonomousSystemNumber)
	}
	if r.MetaClientGeoAutonomousSystemOrganization != nil {
		p.MetaClientGeoAutonomousSystemOrganization = wrapperspb.String(*r.MetaClientGeoAutonomousSystemOrganization)
	}
	p.MetaNetworkName = r.MetaNetworkName
	return p
}
