// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for mempool_transaction

package clickhouse

import (
	"net"

	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// MempoolTransactionRow is a ClickHouse-scannable result row for the mempool_transaction table.
// Field types match the SELECT column expressions produced by
// BuildListMempoolTransactionQuery and BuildGetMempoolTransactionQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type MempoolTransactionRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	EventDateTime int64 `ch:"event_date_time" json:"event_date_time"`
	Hash *string `ch:"hash" json:"hash"`
	From *string `ch:"from" json:"from"`
	To *string `ch:"to" json:"to"`
	Nonce uint64 `ch:"nonce" json:"nonce"`
	GasPrice string `ch:"gas_price" json:"gas_price"`
	Gas uint64 `ch:"gas" json:"gas"`
	GasTipCap *string `ch:"gas_tip_cap" json:"gas_tip_cap"`
	GasFeeCap *string `ch:"gas_fee_cap" json:"gas_fee_cap"`
	Value string `ch:"value" json:"value"`
	Type *uint32 `ch:"type" json:"type"`
	Size uint32 `ch:"size" json:"size"`
	CallDataSize uint32 `ch:"call_data_size" json:"call_data_size"`
	BlobGas *uint64 `ch:"blob_gas" json:"blob_gas"`
	BlobGasFeeCap *string `ch:"blob_gas_fee_cap" json:"blob_gas_fee_cap"`
	BlobHashes []string `ch:"blob_hashes" json:"blob_hashes"`
	BlobSidecarsSize *uint32 `ch:"blob_sidecars_size" json:"blob_sidecars_size"`
	BlobSidecarsEmptySize *uint32 `ch:"blob_sidecars_empty_size" json:"blob_sidecars_empty_size"`
	MetaClientName string `ch:"meta_client_name" json:"meta_client_name"`
	MetaClientVersion string `ch:"meta_client_version" json:"meta_client_version"`
	MetaClientImplementation string `ch:"meta_client_implementation" json:"meta_client_implementation"`
	MetaClientOs string `ch:"meta_client_os" json:"meta_client_os"`
	MetaClientIp *net.IP `ch:"meta_client_ip" json:"meta_client_ip"`
	MetaClientGeoCity string `ch:"meta_client_geo_city" json:"meta_client_geo_city"`
	MetaClientGeoCountry string `ch:"meta_client_geo_country" json:"meta_client_geo_country"`
	MetaClientGeoCountryCode string `ch:"meta_client_geo_country_code" json:"meta_client_geo_country_code"`
	MetaClientGeoContinentCode string `ch:"meta_client_geo_continent_code" json:"meta_client_geo_continent_code"`
	MetaClientGeoLongitude *float64 `ch:"meta_client_geo_longitude" json:"meta_client_geo_longitude"`
	MetaClientGeoLatitude *float64 `ch:"meta_client_geo_latitude" json:"meta_client_geo_latitude"`
	MetaClientGeoAutonomousSystemNumber *uint32 `ch:"meta_client_geo_autonomous_system_number" json:"meta_client_geo_autonomous_system_number"`
	MetaClientGeoAutonomousSystemOrganization *string `ch:"meta_client_geo_autonomous_system_organization" json:"meta_client_geo_autonomous_system_organization"`
	MetaNetworkName string `ch:"meta_network_name" json:"meta_network_name"`
	MetaExecutionForkIdHash string `ch:"meta_execution_fork_id_hash" json:"meta_execution_fork_id_hash"`
	MetaExecutionForkIdNext string `ch:"meta_execution_fork_id_next" json:"meta_execution_fork_id_next"`
}

// TableName returns the ClickHouse table this row maps to.
func (MempoolTransactionRow) TableName() string {
	return "mempool_transaction"
}

// ToProto converts the row to its protobuf message.
func (r *MempoolTransactionRow) ToProto() *MempoolTransaction {
	p := &MempoolTransaction{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.EventDateTime = r.EventDateTime
	if r.Hash != nil {
		p.Hash = *r.Hash
	}
	if r.From != nil {
		p.From = *r.From
	}
	if r.To != nil {
		p.To = wrapperspb.String(*r.To)
	}
	p.Nonce = r.Nonce
	p.GasPrice = r.GasPrice
	p.Gas = r.Gas
	if r.GasTipCap != nil {
		p.GasTipCap = wrapperspb.String(*r.GasTipCap)
	}
	if r.GasFeeCap != nil {
		p.GasFeeCap = wrapperspb.String(*r.GasFeeCap)
	}
	p.Value = r.Value
	if r.Type != nil {
		p.Type = wrapperspb.UInt32(*r.Type)
	}
	p.Size = r.Size
	p.CallDataSize = r.CallDataSize
	if r.BlobGas != nil {
		p.BlobGas = wrapperspb.UInt64(*r.BlobGas)
	}
	if r.BlobGasFeeCap != nil {
		p.BlobGasFeeCap = wrapperspb.String(*r.BlobGasFeeCap)
	}
	p.BlobHashes = r.BlobHashes
	if r.BlobSidecarsSize != nil {
		p.BlobSidecarsSize = wrapperspb.UInt32(*r.BlobSidecarsSize)
	}
	if r.BlobSidecarsEmptySize != nil {
		p.BlobSidecarsEmptySize = wrapperspb.UInt32(*r.BlobSidecarsEmptySize)
	}
	p.MetaClientName = r.MetaClientName
	p.MetaClientVersion = r.MetaClientVersion
	p.MetaClientImplementation = r.MetaClientImplementation
	p.MetaClientOs = r.MetaClientOs
	if r.MetaClientIp != nil {
		p.MetaClientIp = wrapperspb.String(r.MetaClientIp.String())
	}
	p.MetaClientGeoCity = r.MetaClientGeoCity
	p.MetaClientGeoCountry = r.MetaClientGeoCountry
	p.MetaClientGeoCountryCode = r.MetaClientGeoCountryCode
	p.MetaClientGeoContinentCode = r.MetaClientGeoContinentCode
	if r.MetaClientGeoLongitude != nil {
		p.MetaClientGeoLongitude = wrapperspb.Double(*r.MetaClientGeoLongitude)
	}
	if r.MetaClientGeoLatitude != nil {
		p.MetaClientGeoLatitude = wrapperspb.Double(*r.MetaClientGeoLatitude)
	}
	if r.MetaClientGeoAutonomousSystemNumber != nil {
		p.MetaClientGeoAutonomousSystemNumber = wrapperspb.UInt32(*r.MetaClientGeoAutonomousSystemNumber)
	}
	if r.MetaClientGeoAutonomousSystemOrganization != nil {
		p.MetaClientGeoAutonomousSystemOrganization = wrapperspb.String(*r.MetaClientGeoAutonomousSystemOrganization)
	}
	p.MetaNetworkName = r.MetaNetworkName
	p.MetaExecutionForkIdHash = r.MetaExecutionForkIdHash
	p.MetaExecutionForkIdNext = r.MetaExecutionForkIdNext
	return p
}
