syntax = "proto3";

package clickhouse.v1;

import "common.proto";
import "google/protobuf/wrappers.proto";

option go_package = "github.com/ethpandaops/xatu/pkg/proto/clickhouse";
// Contains MEV relay validator registrations data.

message MevRelayValidatorRegistration {
  // Timestamp when the record was last updated
  uint32 updated_date_time = 11;
  // When the registration was fetched
  int64 event_date_time = 12;
  // The timestamp of the registration
  int64 timestamp = 13;
  // The relay that the registration was fetched from
  string relay_name = 14;
  // The validator index of the validator registration
  uint32 validator_index = 15;
  // The gas limit of the validator registration
  uint64 gas_limit = 16;
  // The fee recipient of the validator registration
  string fee_recipient = 17;
  // Slot number derived from the validator registration `timestamp` field
  uint32 slot = 18;
  // The slot start time derived from the validator registration `timestamp` field
  uint32 slot_start_date_time = 19;
  // Epoch number derived from the validator registration `timestamp` field
  uint32 epoch = 20;
  // The epoch start time derived from the validator registration `timestamp` field
  uint32 epoch_start_date_time = 21;
  // The wallclock slot when the request was sent
  uint32 wallclock_slot = 22;
  // The start time for the slot when the request was sent
  uint32 wallclock_slot_start_date_time = 23;
  // The wallclock epoch when the request was sent
  uint32 wallclock_epoch = 24;
  // The start time for the wallclock epoch when the request was sent
  uint32 wallclock_epoch_start_date_time = 25;
  // Name of the client that generated the event
  string meta_client_name = 26;
  // Version of the client that generated the event
  string meta_client_version = 27;
  // Implementation of the client that generated the event
  string meta_client_implementation = 28;
  // Operating system of the client that generated the event
  string meta_client_os = 29;
  // IP address of the client that generated the event
  google.protobuf.StringValue meta_client_ip = 30;
  // City of the client that generated the event
  string meta_client_geo_city = 31;
  // Country of the client that generated the event
  string meta_client_geo_country = 32;
  // Country code of the client that generated the event
  string meta_client_geo_country_code = 33;
  // Continent code of the client that generated the event
  string meta_client_geo_continent_code = 34;
  // Longitude of the client that generated the event
  google.protobuf.DoubleValue meta_client_geo_longitude = 35;
  // Latitude of the client that generated the event
  google.protobuf.DoubleValue meta_client_geo_latitude = 36;
  // Autonomous system number of the client that generated the event
  google.protobuf.UInt32Value meta_client_geo_autonomous_system_number = 37;
  // Autonomous system organization of the client that generated the event
  google.protobuf.StringValue meta_client_geo_autonomous_system_organization = 38;
  // Ethereum network name
  string meta_network_name = 39;
}

// Request for listing mev_relay_validator_registration records
message ListMevRelayValidatorRegistrationRequest {
  // Filter by meta_network_name - Ethereum network name (PRIMARY KEY - required)
  StringFilter meta_network_name = 1;

  // Filter by event_date_time - When the registration was fetched (ORDER BY column 2 - optional)
  Int64Filter event_date_time = 2;

  // Filter by meta_client_name - Name of the client that generated the event (ORDER BY column 3 - optional)
  StringFilter meta_client_name = 3;

  // Filter by relay_name - The relay that the registration was fetched from (ORDER BY column 4 - optional)
  StringFilter relay_name = 4;

  // Filter by validator_index - The validator index of the validator registration (ORDER BY column 5 - optional)
  UInt32Filter validator_index = 5;

  // Filter by timestamp - The timestamp of the registration (ORDER BY column 6 - optional)
  Int64Filter timestamp = 6;

  // Filter by updated_date_time - Timestamp when the record was last updated (optional)
  UInt32Filter updated_date_time = 7;
  // Filter by gas_limit - The gas limit of the validator registration (optional)
  UInt64Filter gas_limit = 8;
  // Filter by fee_recipient - The fee recipient of the validator registration (optional)
  StringFilter fee_recipient = 9;
  // Filter by slot - Slot number derived from the validator registration `timestamp` field (optional)
  UInt32Filter slot = 10;
  // Filter by slot_start_date_time - The slot start time derived from the validator registration `timestamp` field (optional)
  UInt32Filter slot_start_date_time = 11;
  // Filter by epoch - Epoch number derived from the validator registration `timestamp` field (optional)
  UInt32Filter epoch = 12;
  // Filter by epoch_start_date_time - The epoch start time derived from the validator registration `timestamp` field (optional)
  UInt32Filter epoch_start_date_time = 13;
  // Filter by wallclock_slot - The wallclock slot when the request was sent (optional)
  UInt32Filter wallclock_slot = 14;
  // Filter by wallclock_slot_start_date_time - The start time for the slot when the request was sent (optional)
  UInt32Filter wallclock_slot_start_date_time = 15;
  // Filter by wallclock_epoch - The wallclock epoch when the request was sent (optional)
  UInt32Filter wallclock_epoch = 16;
  // Filter by wallclock_epoch_start_date_time - The start time for the wallclock epoch when the request was sent (optional)
  UInt32Filter wallclock_epoch_start_date_time = 17;
  // Filter by meta_client_version - Version of the client that generated the event (optional)
  StringFilter meta_client_version = 18;
  // Filter by meta_client_implementation - Implementation of the client that generated the event (optional)
  StringFilter meta_client_implementation = 19;
  // Filter by meta_client_os - Operating system of the client that generated the event (optional)
  StringFilter meta_client_os = 20;
  // Filter by meta_client_ip - IP address of the client that generated the event (optional)
  NullableStringFilter meta_client_ip = 21;
  // Filter by meta_client_geo_city - City of the client that generated the event (optional)
  StringFilter meta_client_geo_city = 22;
  // Filter by meta_client_geo_country - Country of the client that generated the event (optional)
  StringFilter meta_client_geo_country = 23;
  // Filter by meta_client_geo_country_code - Country code of the client that generated the event (optional)
  StringFilter meta_client_geo_country_code = 24;
  // Filter by meta_client_geo_continent_code - Continent code of the client that generated the event (optional)
  StringFilter meta_client_geo_continent_code = 25;
  // Filter by meta_client_geo_longitude - Longitude of the client that generated the event (optional)
  google.protobuf.DoubleValue meta_client_geo_longitude = 26;
  // Filter by meta_client_geo_latitude - Latitude of the client that generated the event (optional)
  google.protobuf.DoubleValue meta_client_geo_latitude = 27;
  // Filter by meta_client_geo_autonomous_system_number - Autonomous system number of the client that generated the event (optional)
  NullableUInt32Filter meta_client_geo_autonomous_system_number = 28;
  // Filter by meta_client_geo_autonomous_system_organization - Autonomous system organization of the client that generated the event (optional)
  NullableStringFilter meta_client_geo_autonomous_system_organization = 29;

  // The maximum number of mev_relay_validator_registration to return.
  // If unspecified, at most 100 items will be returned.
  // The maximum value is 10000; values above 10000 will be coerced to 10000.
  int32 page_size = 30;
  // A page token, received from a previous `ListMevRelayValidatorRegistration` call.
  // Provide this to retrieve the subsequent page.
  string page_token = 31;
  // The order of results. Format: comma-separated list of fields.
  // Example: "foo,bar" or "foo desc,bar" for descending order on foo.
  // If unspecified, results will be returned in the default order.
  string order_by = 32;
}

// Response for listing mev_relay_validator_registration records
message ListMevRelayValidatorRegistrationResponse {
  // The list of mev_relay_validator_registration.
  repeated MevRelayValidatorRegistration mev_relay_validator_registration = 1;
  // A token, which can be sent as `page_token` to retrieve the next page.
  // If this field is omitted, there are no subsequent pages.
  string next_page_token = 2;
}

// Request for getting a single mev_relay_validator_registration record by primary key
message GetMevRelayValidatorRegistrationRequest {
  // Ethereum network name
  string meta_network_name = 1; // Primary key (required)
}

// Response for getting a single mev_relay_validator_registration record
message GetMevRelayValidatorRegistrationResponse {
  MevRelayValidatorRegistration item = 1;
}

// Query mev_relay_validator_registration data
service MevRelayValidatorRegistrationService {
  // List records | Retrieve paginated results with optional filtering
  rpc List(ListMevRelayValidatorRegistrationRequest) returns (ListMevRelayValidatorRegistrationResponse);
  // Get record | Retrieve a single record by primary key
  rpc Get(GetMevRelayValidatorRegistrationRequest) returns (GetMevRelayValidatorRegistrationResponse);
}
