// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// SQL query builder for mev_relay_bid_trace

package clickhouse

import (
	"fmt"
)

// BuildListMevRelayBidTraceQuery constructs a parameterized SQL query from a ListMevRelayBidTraceRequest
func BuildListMevRelayBidTraceQuery(req *ListMevRelayBidTraceRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate that at least one primary key is provided
	// Primary keys can come from base table or projections
	if req.MetaNetworkName == nil {
		return SQLQuery{}, fmt.Errorf("primary key field meta_network_name is required")
	}

	// Build query using QueryBuilder
	qb := NewQueryBuilder()

	// Add primary key filter
	switch filter := req.MetaNetworkName.Filter.(type) {
	case *StringFilter_Eq:
		qb.AddCondition("meta_network_name", "=", filter.Eq)
	case *StringFilter_Ne:
		qb.AddCondition("meta_network_name", "!=", filter.Ne)
	case *StringFilter_Contains:
		qb.AddLikeCondition("meta_network_name", "%" + filter.Contains + "%")
	case *StringFilter_StartsWith:
		qb.AddLikeCondition("meta_network_name", filter.StartsWith + "%")
	case *StringFilter_EndsWith:
		qb.AddLikeCondition("meta_network_name", "%" + filter.EndsWith)
	case *StringFilter_Like:
		qb.AddLikeCondition("meta_network_name", filter.Like)
	case *StringFilter_NotLike:
		qb.AddNotLikeCondition("meta_network_name", filter.NotLike)
	case *StringFilter_In:
		if len(filter.In.Values) > 0 {
			qb.AddInCondition("meta_network_name", StringSliceToInterface(filter.In.Values))
		}
	case *StringFilter_NotIn:
		if len(filter.NotIn.Values) > 0 {
			qb.AddNotInCondition("meta_network_name", StringSliceToInterface(filter.NotIn.Values))
		}
	default:
		// Unsupported filter type
	}

	// Add filter for column: updated_date_time
	if req.UpdatedDateTime != nil {
		switch filter := req.UpdatedDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("updated_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("updated_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("updated_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("updated_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("updated_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("updated_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("updated_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("updated_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("updated_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: event_date_time
	if req.EventDateTime != nil {
		switch filter := req.EventDateTime.Filter.(type) {
		case *Int64Filter_Eq:
			qb.AddCondition("event_date_time", "=", DateTime64Value{uint64(filter.Eq)})
		case *Int64Filter_Ne:
			qb.AddCondition("event_date_time", "!=", DateTime64Value{uint64(filter.Ne)})
		case *Int64Filter_Lt:
			qb.AddCondition("event_date_time", "<", DateTime64Value{uint64(filter.Lt)})
		case *Int64Filter_Lte:
			qb.AddCondition("event_date_time", "<=", DateTime64Value{uint64(filter.Lte)})
		case *Int64Filter_Gt:
			qb.AddCondition("event_date_time", ">", DateTime64Value{uint64(filter.Gt)})
		case *Int64Filter_Gte:
			qb.AddCondition("event_date_time", ">=", DateTime64Value{uint64(filter.Gte)})
		case *Int64Filter_Between:
			qb.AddBetweenCondition("event_date_time", DateTime64Value{uint64(filter.Between.Min)}, DateTime64Value{uint64(filter.Between.Max.GetValue())})
		case *Int64Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTime64Value{uint64(v)}
				}
				qb.AddInCondition("event_date_time", converted)
			}
		case *Int64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTime64Value{uint64(v)}
				}
				qb.AddNotInCondition("event_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: slot
	if req.Slot != nil {
		switch filter := req.Slot.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("slot", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("slot", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("slot", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("slot", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("slot", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("slot", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("slot", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("slot", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("slot", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: slot_start_date_time
	if req.SlotStartDateTime != nil {
		switch filter := req.SlotStartDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("slot_start_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("slot_start_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("slot_start_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("slot_start_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("slot_start_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("slot_start_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("slot_start_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("slot_start_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("slot_start_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: epoch
	if req.Epoch != nil {
		switch filter := req.Epoch.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("epoch", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("epoch", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("epoch", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("epoch", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("epoch", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("epoch", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("epoch", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("epoch", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("epoch", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: epoch_start_date_time
	if req.EpochStartDateTime != nil {
		switch filter := req.EpochStartDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("epoch_start_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("epoch_start_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("epoch_start_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("epoch_start_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("epoch_start_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("epoch_start_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("epoch_start_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("epoch_start_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("epoch_start_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: wallclock_request_slot
	if req.WallclockRequestSlot != nil {
		switch filter := req.WallclockRequestSlot.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("wallclock_request_slot", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("wallclock_request_slot", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("wallclock_request_slot", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("wallclock_request_slot", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("wallclock_request_slot", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("wallclock_request_slot", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("wallclock_request_slot", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("wallclock_request_slot", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("wallclock_request_slot", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: wallclock_request_slot_start_date_time
	if req.WallclockRequestSlotStartDateTime != nil {
		switch filter := req.WallclockRequestSlotStartDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("wallclock_request_slot_start_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("wallclock_request_slot_start_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("wallclock_request_slot_start_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("wallclock_request_slot_start_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("wallclock_request_slot_start_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("wallclock_request_slot_start_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("wallclock_request_slot_start_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("wallclock_request_slot_start_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("wallclock_request_slot_start_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: wallclock_request_epoch
	if req.WallclockRequestEpoch != nil {
		switch filter := req.WallclockRequestEpoch.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("wallclock_request_epoch", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("wallclock_request_epoch", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("wallclock_request_epoch", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("wallclock_request_epoch", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("wallclock_request_epoch", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("wallclock_request_epoch", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("wallclock_request_epoch", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("wallclock_request_epoch", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("wallclock_request_epoch", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: wallclock_request_epoch_start_date_time
	if req.WallclockRequestEpochStartDateTime != nil {
		switch filter := req.WallclockRequestEpochStartDateTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("wallclock_request_epoch_start_date_time", "=", DateTimeValue{filter.Eq})
		case *UInt32Filter_Ne:
			qb.AddCondition("wallclock_request_epoch_start_date_time", "!=", DateTimeValue{filter.Ne})
		case *UInt32Filter_Lt:
			qb.AddCondition("wallclock_request_epoch_start_date_time", "<", DateTimeValue{filter.Lt})
		case *UInt32Filter_Lte:
			qb.AddCondition("wallclock_request_epoch_start_date_time", "<=", DateTimeValue{filter.Lte})
		case *UInt32Filter_Gt:
			qb.AddCondition("wallclock_request_epoch_start_date_time", ">", DateTimeValue{filter.Gt})
		case *UInt32Filter_Gte:
			qb.AddCondition("wallclock_request_epoch_start_date_time", ">=", DateTimeValue{filter.Gte})
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("wallclock_request_epoch_start_date_time", DateTimeValue{filter.Between.Min}, DateTimeValue{filter.Between.Max.GetValue()})
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				converted := make([]interface{}, len(filter.In.Values))
				for i, v := range filter.In.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddInCondition("wallclock_request_epoch_start_date_time", converted)
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				converted := make([]interface{}, len(filter.NotIn.Values))
				for i, v := range filter.NotIn.Values {
					converted[i] = DateTimeValue{v}
				}
				qb.AddNotInCondition("wallclock_request_epoch_start_date_time", converted)
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: requested_at_slot_time
	if req.RequestedAtSlotTime != nil {
		switch filter := req.RequestedAtSlotTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("requested_at_slot_time", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("requested_at_slot_time", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("requested_at_slot_time", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("requested_at_slot_time", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("requested_at_slot_time", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("requested_at_slot_time", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("requested_at_slot_time", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("requested_at_slot_time", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("requested_at_slot_time", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: response_at_slot_time
	if req.ResponseAtSlotTime != nil {
		switch filter := req.ResponseAtSlotTime.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("response_at_slot_time", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("response_at_slot_time", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("response_at_slot_time", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("response_at_slot_time", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("response_at_slot_time", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("response_at_slot_time", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("response_at_slot_time", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("response_at_slot_time", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("response_at_slot_time", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: relay_name
	if req.RelayName != nil {
		switch filter := req.RelayName.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("relay_name", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("relay_name", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("relay_name", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("relay_name", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("relay_name", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("relay_name", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("relay_name", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("relay_name", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("relay_name", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: parent_hash
	if req.ParentHash != nil {
		switch filter := req.ParentHash.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("parent_hash", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("parent_hash", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("parent_hash", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("parent_hash", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("parent_hash", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("parent_hash", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("parent_hash", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("parent_hash", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("parent_hash", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: block_number
	if req.BlockNumber != nil {
		switch filter := req.BlockNumber.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("block_number", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("block_number", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("block_number", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("block_number", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("block_number", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("block_number", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("block_number", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("block_number", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("block_number", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: block_hash
	if req.BlockHash != nil {
		switch filter := req.BlockHash.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("block_hash", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("block_hash", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("block_hash", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("block_hash", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("block_hash", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("block_hash", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("block_hash", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("block_hash", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("block_hash", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: builder_pubkey
	if req.BuilderPubkey != nil {
		switch filter := req.BuilderPubkey.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("builder_pubkey", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("builder_pubkey", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("builder_pubkey", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("builder_pubkey", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("builder_pubkey", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("builder_pubkey", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("builder_pubkey", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("builder_pubkey", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("builder_pubkey", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: proposer_pubkey
	if req.ProposerPubkey != nil {
		switch filter := req.ProposerPubkey.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("proposer_pubkey", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("proposer_pubkey", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("proposer_pubkey", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("proposer_pubkey", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("proposer_pubkey", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("proposer_pubkey", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("proposer_pubkey", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("proposer_pubkey", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("proposer_pubkey", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: proposer_fee_recipient
	if req.ProposerFeeRecipient != nil {
		switch filter := req.ProposerFeeRecipient.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("proposer_fee_recipient", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("proposer_fee_recipient", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("proposer_fee_recipient", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("proposer_fee_recipient", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("proposer_fee_recipient", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("proposer_fee_recipient", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("proposer_fee_recipient", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("proposer_fee_recipient", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("proposer_fee_recipient", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: gas_limit
	if req.GasLimit != nil {
		switch filter := req.GasLimit.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("gas_limit", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("gas_limit", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("gas_limit", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("gas_limit", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("gas_limit", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("gas_limit", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("gas_limit", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("gas_limit", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("gas_limit", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: gas_used
	if req.GasUsed != nil {
		switch filter := req.GasUsed.Filter.(type) {
		case *UInt64Filter_Eq:
			qb.AddCondition("gas_used", "=", filter.Eq)
		case *UInt64Filter_Ne:
			qb.AddCondition("gas_used", "!=", filter.Ne)
		case *UInt64Filter_Lt:
			qb.AddCondition("gas_used", "<", filter.Lt)
		case *UInt64Filter_Lte:
			qb.AddCondition("gas_used", "<=", filter.Lte)
		case *UInt64Filter_Gt:
			qb.AddCondition("gas_used", ">", filter.Gt)
		case *UInt64Filter_Gte:
			qb.AddCondition("gas_used", ">=", filter.Gte)
		case *UInt64Filter_Between:
			qb.AddBetweenCondition("gas_used", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("gas_used", UInt64SliceToInterface(filter.In.Values))
			}
		case *UInt64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("gas_used", UInt64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: value
	if req.Value != nil {
		switch filter := req.Value.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("value", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("value", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("value", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("value", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("value", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("value", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("value", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("value", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("value", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: num_tx
	if req.NumTx != nil {
		switch filter := req.NumTx.Filter.(type) {
		case *UInt32Filter_Eq:
			qb.AddCondition("num_tx", "=", filter.Eq)
		case *UInt32Filter_Ne:
			qb.AddCondition("num_tx", "!=", filter.Ne)
		case *UInt32Filter_Lt:
			qb.AddCondition("num_tx", "<", filter.Lt)
		case *UInt32Filter_Lte:
			qb.AddCondition("num_tx", "<=", filter.Lte)
		case *UInt32Filter_Gt:
			qb.AddCondition("num_tx", ">", filter.Gt)
		case *UInt32Filter_Gte:
			qb.AddCondition("num_tx", ">=", filter.Gte)
		case *UInt32Filter_Between:
			qb.AddBetweenCondition("num_tx", filter.Between.Min, filter.Between.Max.GetValue())
		case *UInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("num_tx", UInt32SliceToInterface(filter.In.Values))
			}
		case *UInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("num_tx", UInt32SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: timestamp
	if req.Timestamp != nil {
		switch filter := req.Timestamp.Filter.(type) {
		case *Int64Filter_Eq:
			qb.AddCondition("timestamp", "=", filter.Eq)
		case *Int64Filter_Ne:
			qb.AddCondition("timestamp", "!=", filter.Ne)
		case *Int64Filter_Lt:
			qb.AddCondition("timestamp", "<", filter.Lt)
		case *Int64Filter_Lte:
			qb.AddCondition("timestamp", "<=", filter.Lte)
		case *Int64Filter_Gt:
			qb.AddCondition("timestamp", ">", filter.Gt)
		case *Int64Filter_Gte:
			qb.AddCondition("timestamp", ">=", filter.Gte)
		case *Int64Filter_Between:
			qb.AddBetweenCondition("timestamp", filter.Between.Min, filter.Between.Max.GetValue())
		case *Int64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("timestamp", Int64SliceToInterface(filter.In.Values))
			}
		case *Int64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("timestamp", Int64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: timestamp_ms
	if req.TimestampMs != nil {
		switch filter := req.TimestampMs.Filter.(type) {
		case *Int64Filter_Eq:
			qb.AddCondition("timestamp_ms", "=", filter.Eq)
		case *Int64Filter_Ne:
			qb.AddCondition("timestamp_ms", "!=", filter.Ne)
		case *Int64Filter_Lt:
			qb.AddCondition("timestamp_ms", "<", filter.Lt)
		case *Int64Filter_Lte:
			qb.AddCondition("timestamp_ms", "<=", filter.Lte)
		case *Int64Filter_Gt:
			qb.AddCondition("timestamp_ms", ">", filter.Gt)
		case *Int64Filter_Gte:
			qb.AddCondition("timestamp_ms", ">=", filter.Gte)
		case *Int64Filter_Between:
			qb.AddBetweenCondition("timestamp_ms", filter.Between.Min, filter.Between.Max.GetValue())
		case *Int64Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("timestamp_ms", Int64SliceToInterface(filter.In.Values))
			}
		case *Int64Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("timestamp_ms", Int64SliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: optimistic_submission
	if req.OptimisticSubmission != nil {
		switch filter := req.OptimisticSubmission.Filter.(type) {
		case *BoolFilter_Eq:
			qb.AddCondition("optimistic_submission", "=", filter.Eq)
		case *BoolFilter_Ne:
			qb.AddCondition("optimistic_submission", "!=", filter.Ne)
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_name
	if req.MetaClientName != nil {
		switch filter := req.MetaClientName.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_name", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_name", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_name", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_name", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_name", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_name", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_name", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_name", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_name", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_version
	if req.MetaClientVersion != nil {
		switch filter := req.MetaClientVersion.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_version", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_version", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_version", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_version", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_version", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_version", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_version", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_version", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_version", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_implementation
	if req.MetaClientImplementation != nil {
		switch filter := req.MetaClientImplementation.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_implementation", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_implementation", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_implementation", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_implementation", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_implementation", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_implementation", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_implementation", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_implementation", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_implementation", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_os
	if req.MetaClientOs != nil {
		switch filter := req.MetaClientOs.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_os", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_os", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_os", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_os", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_os", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_os", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_os", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_os", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_os", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_ip
	if req.MetaClientIp != nil {
		switch filter := req.MetaClientIp.Filter.(type) {
		case *NullableStringFilter_Eq:
			qb.AddCondition("meta_client_ip", "=", filter.Eq)
		case *NullableStringFilter_Ne:
			qb.AddCondition("meta_client_ip", "!=", filter.Ne)
		case *NullableStringFilter_Contains:
			qb.AddLikeCondition("meta_client_ip", "%" + filter.Contains + "%")
		case *NullableStringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_ip", filter.StartsWith + "%")
		case *NullableStringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_ip", "%" + filter.EndsWith)
		case *NullableStringFilter_Like:
			qb.AddLikeCondition("meta_client_ip", filter.Like)
		case *NullableStringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_ip", filter.NotLike)
		case *NullableStringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_ip", StringSliceToInterface(filter.In.Values))
			}
		case *NullableStringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_ip", StringSliceToInterface(filter.NotIn.Values))
			}
		case *NullableStringFilter_IsNull:
			qb.AddIsNullCondition("meta_client_ip")
		case *NullableStringFilter_IsNotNull:
			qb.AddIsNotNullCondition("meta_client_ip")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_city
	if req.MetaClientGeoCity != nil {
		switch filter := req.MetaClientGeoCity.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_geo_city", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_geo_city", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_geo_city", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_geo_city", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_geo_city", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_geo_city", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_geo_city", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_city", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_city", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_country
	if req.MetaClientGeoCountry != nil {
		switch filter := req.MetaClientGeoCountry.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_geo_country", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_geo_country", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_geo_country", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_geo_country", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_geo_country", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_geo_country", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_geo_country", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_country", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_country", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_country_code
	if req.MetaClientGeoCountryCode != nil {
		switch filter := req.MetaClientGeoCountryCode.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_geo_country_code", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_geo_country_code", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_geo_country_code", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_geo_country_code", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_geo_country_code", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_geo_country_code", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_geo_country_code", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_country_code", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_country_code", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_continent_code
	if req.MetaClientGeoContinentCode != nil {
		switch filter := req.MetaClientGeoContinentCode.Filter.(type) {
		case *StringFilter_Eq:
			qb.AddCondition("meta_client_geo_continent_code", "=", filter.Eq)
		case *StringFilter_Ne:
			qb.AddCondition("meta_client_geo_continent_code", "!=", filter.Ne)
		case *StringFilter_Contains:
			qb.AddLikeCondition("meta_client_geo_continent_code", "%" + filter.Contains + "%")
		case *StringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_geo_continent_code", filter.StartsWith + "%")
		case *StringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_geo_continent_code", "%" + filter.EndsWith)
		case *StringFilter_Like:
			qb.AddLikeCondition("meta_client_geo_continent_code", filter.Like)
		case *StringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_geo_continent_code", filter.NotLike)
		case *StringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_continent_code", StringSliceToInterface(filter.In.Values))
			}
		case *StringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_continent_code", StringSliceToInterface(filter.NotIn.Values))
			}
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_longitude

	// Add filter for column: meta_client_geo_latitude

	// Add filter for column: meta_client_geo_autonomous_system_number
	if req.MetaClientGeoAutonomousSystemNumber != nil {
		switch filter := req.MetaClientGeoAutonomousSystemNumber.Filter.(type) {
		case *NullableUInt32Filter_Eq:
			qb.AddCondition("meta_client_geo_autonomous_system_number", "=", filter.Eq)
		case *NullableUInt32Filter_Ne:
			qb.AddCondition("meta_client_geo_autonomous_system_number", "!=", filter.Ne)
		case *NullableUInt32Filter_Lt:
			qb.AddCondition("meta_client_geo_autonomous_system_number", "<", filter.Lt)
		case *NullableUInt32Filter_Lte:
			qb.AddCondition("meta_client_geo_autonomous_system_number", "<=", filter.Lte)
		case *NullableUInt32Filter_Gt:
			qb.AddCondition("meta_client_geo_autonomous_system_number", ">", filter.Gt)
		case *NullableUInt32Filter_Gte:
			qb.AddCondition("meta_client_geo_autonomous_system_number", ">=", filter.Gte)
		case *NullableUInt32Filter_Between:
			qb.AddBetweenCondition("meta_client_geo_autonomous_system_number", filter.Between.Min, filter.Between.Max.GetValue())
		case *NullableUInt32Filter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_autonomous_system_number", UInt32SliceToInterface(filter.In.Values))
			}
		case *NullableUInt32Filter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_autonomous_system_number", UInt32SliceToInterface(filter.NotIn.Values))
			}
		case *NullableUInt32Filter_IsNull:
			qb.AddIsNullCondition("meta_client_geo_autonomous_system_number")
		case *NullableUInt32Filter_IsNotNull:
			qb.AddIsNotNullCondition("meta_client_geo_autonomous_system_number")
		default:
			// Unsupported filter type
		}
	}

	// Add filter for column: meta_client_geo_autonomous_system_organization
	if req.MetaClientGeoAutonomousSystemOrganization != nil {
		switch filter := req.MetaClientGeoAutonomousSystemOrganization.Filter.(type) {
		case *NullableStringFilter_Eq:
			qb.AddCondition("meta_client_geo_autonomous_system_organization", "=", filter.Eq)
		case *NullableStringFilter_Ne:
			qb.AddCondition("meta_client_geo_autonomous_system_organization", "!=", filter.Ne)
		case *NullableStringFilter_Contains:
			qb.AddLikeCondition("meta_client_geo_autonomous_system_organization", "%" + filter.Contains + "%")
		case *NullableStringFilter_StartsWith:
			qb.AddLikeCondition("meta_client_geo_autonomous_system_organization", filter.StartsWith + "%")
		case *NullableStringFilter_EndsWith:
			qb.AddLikeCondition("meta_client_geo_autonomous_system_organization", "%" + filter.EndsWith)
		case *NullableStringFilter_Like:
			qb.AddLikeCondition("meta_client_geo_autonomous_system_organization", filter.Like)
		case *NullableStringFilter_NotLike:
			qb.AddNotLikeCondition("meta_client_geo_autonomous_system_organization", filter.NotLike)
		case *NullableStringFilter_In:
			if len(filter.In.Values) > 0 {
				qb.AddInCondition("meta_client_geo_autonomous_system_organization", StringSliceToInterface(filter.In.Values))
			}
		case *NullableStringFilter_NotIn:
			if len(filter.NotIn.Values) > 0 {
				qb.AddNotInCondition("meta_client_geo_autonomous_system_organization", StringSliceToInterface(filter.NotIn.Values))
			}
		case *NullableStringFilter_IsNull:
			qb.AddIsNullCondition("meta_client_geo_autonomous_system_organization")
		case *NullableStringFilter_IsNotNull:
			qb.AddIsNotNullCondition("meta_client_geo_autonomous_system_organization")
		default:
			// Unsupported filter type
		}
	}

	// Handle pagination per AIP-132
	// Validate page size
	if req.PageSize < 0 {
		return SQLQuery{}, fmt.Errorf("page_size must be non-negative, got %d", req.PageSize)
	}
	if req.PageSize > 10000 {
		return SQLQuery{}, fmt.Errorf("page_size must not exceed %d, got %d", 10000, req.PageSize)
	}

	var limit, offset uint32
	limit = 100 // Default page size
	if req.PageSize > 0 {
		limit = uint32(req.PageSize)
	}
	if req.PageToken != "" {
		decodedOffset, err := DecodePageToken(req.PageToken)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid page_token: %w", err)
		}
		offset = decodedOffset
	}

	// Handle custom ordering if provided
	var orderByClause string
	if req.OrderBy != "" {
		validFields := []string{"updated_date_time", "event_date_time", "slot", "slot_start_date_time", "epoch", "epoch_start_date_time", "wallclock_request_slot", "wallclock_request_slot_start_date_time", "wallclock_request_epoch", "wallclock_request_epoch_start_date_time", "requested_at_slot_time", "response_at_slot_time", "relay_name", "parent_hash", "block_number", "block_hash", "builder_pubkey", "proposer_pubkey", "proposer_fee_recipient", "gas_limit", "gas_used", "value", "num_tx", "timestamp", "timestamp_ms", "optimistic_submission", "meta_client_name", "meta_client_version", "meta_client_implementation", "meta_client_os", "meta_client_ip", "meta_client_geo_city", "meta_client_geo_country", "meta_client_geo_country_code", "meta_client_geo_continent_code", "meta_client_geo_longitude", "meta_client_geo_latitude", "meta_client_geo_autonomous_system_number", "meta_client_geo_autonomous_system_organization", "meta_network_name"}
		orderFields, err := ParseOrderBy(req.OrderBy, validFields)
		if err != nil {
			return SQLQuery{}, fmt.Errorf("invalid order_by: %w", err)
		}
		orderByClause = BuildOrderByClause(orderFields)
	} else {
		// Default sorting by primary key
		orderByClause = " ORDER BY meta_network_name" + ", slot_start_date_time" + ", relay_name" + ", block_hash" + ", meta_client_name" + ", builder_pubkey" + ", proposer_pubkey"
	}

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "toUnixTimestamp64Micro(`event_date_time`) AS `event_date_time`", "slot", "toUnixTimestamp(`slot_start_date_time`) AS `slot_start_date_time`", "epoch", "toUnixTimestamp(`epoch_start_date_time`) AS `epoch_start_date_time`", "wallclock_request_slot", "toUnixTimestamp(`wallclock_request_slot_start_date_time`) AS `wallclock_request_slot_start_date_time`", "wallclock_request_epoch", "toUnixTimestamp(`wallclock_request_epoch_start_date_time`) AS `wallclock_request_epoch_start_date_time`", "requested_at_slot_time", "response_at_slot_time", "relay_name", "NULLIF(`parent_hash`, repeat('\x00', 66)) AS `parent_hash`", "block_number", "NULLIF(`block_hash`, repeat('\x00', 66)) AS `block_hash`", "builder_pubkey", "proposer_pubkey", "NULLIF(`proposer_fee_recipient`, repeat('\x00', 42)) AS `proposer_fee_recipient`", "gas_limit", "gas_used", "toString(`value`) AS `value`", "num_tx", "timestamp", "timestamp_ms", "optimistic_submission", "meta_client_name", "meta_client_version", "meta_client_implementation", "meta_client_os", "meta_client_ip", "meta_client_geo_city", "meta_client_geo_country", "meta_client_geo_country_code", "meta_client_geo_continent_code", "meta_client_geo_longitude", "meta_client_geo_latitude", "meta_client_geo_autonomous_system_number", "meta_client_geo_autonomous_system_organization", "meta_network_name"}

	return BuildParameterizedQuery("mev_relay_bid_trace", columns, qb, orderByClause, limit, offset, options...)
}

// BuildGetMevRelayBidTraceQuery constructs a parameterized SQL query from a GetMevRelayBidTraceRequest
func BuildGetMevRelayBidTraceQuery(req *GetMevRelayBidTraceRequest, options ...QueryOption) (SQLQuery, error) {
	// Validate primary key is provided
	if req.MetaNetworkName == "" {
		return SQLQuery{}, fmt.Errorf("primary key field meta_network_name is required")
	}

	// Build query with primary key condition
	qb := NewQueryBuilder()
	qb.AddCondition("meta_network_name", "=", req.MetaNetworkName)

	// Build ORDER BY clause
	orderByClause := " ORDER BY meta_network_name, slot_start_date_time, relay_name, block_hash, meta_client_name, builder_pubkey, proposer_pubkey"

	// Build column list
	columns := []string{"toUnixTimestamp(`updated_date_time`) AS `updated_date_time`", "toUnixTimestamp64Micro(`event_date_time`) AS `event_date_time`", "slot", "toUnixTimestamp(`slot_start_date_time`) AS `slot_start_date_time`", "epoch", "toUnixTimestamp(`epoch_start_date_time`) AS `epoch_start_date_time`", "wallclock_request_slot", "toUnixTimestamp(`wallclock_request_slot_start_date_time`) AS `wallclock_request_slot_start_date_time`", "wallclock_request_epoch", "toUnixTimestamp(`wallclock_request_epoch_start_date_time`) AS `wallclock_request_epoch_start_date_time`", "requested_at_slot_time", "response_at_slot_time", "relay_name", "NULLIF(`parent_hash`, repeat('\x00', 66)) AS `parent_hash`", "block_number", "NULLIF(`block_hash`, repeat('\x00', 66)) AS `block_hash`", "builder_pubkey", "proposer_pubkey", "NULLIF(`proposer_fee_recipient`, repeat('\x00', 42)) AS `proposer_fee_recipient`", "gas_limit", "gas_used", "toString(`value`) AS `value`", "num_tx", "timestamp", "timestamp_ms", "optimistic_submission", "meta_client_name", "meta_client_version", "meta_client_implementation", "meta_client_os", "meta_client_ip", "meta_client_geo_city", "meta_client_geo_country", "meta_client_geo_country_code", "meta_client_geo_continent_code", "meta_client_geo_longitude", "meta_client_geo_latitude", "meta_client_geo_autonomous_system_number", "meta_client_geo_autonomous_system_organization", "meta_network_name"}

	// Return single record
	return BuildParameterizedQuery("mev_relay_bid_trace", columns, qb, orderByClause, 1, 0, options...)
}
