// Code generated by clickhouse-proto-gen. DO NOT EDIT.
// Scannable result row for mev_relay_proposer_payload_delivered

package clickhouse

import (
	"net"

	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// MevRelayProposerPayloadDeliveredRow is a ClickHouse-scannable result row for the mev_relay_proposer_payload_delivered table.
// Field types match the SELECT column expressions produced by
// BuildListMevRelayProposerPayloadDeliveredQuery and BuildGetMevRelayProposerPayloadDeliveredQuery: DateTime columns are unix
// timestamps, DateTime64 columns are unix microseconds, Date and large
// integer and decimal columns are strings, and FixedString columns are
// nullable. Scan rows with clickhouse-go's ScanStruct.
type MevRelayProposerPayloadDeliveredRow struct {
	UpdatedDateTime uint32 `ch:"updated_date_time" json:"updated_date_time"`
	EventDateTime int64 `ch:"event_date_time" json:"event_date_time"`
	Slot uint32 `ch:"slot" json:"slot"`
	SlotStartDateTime uint32 `ch:"slot_start_date_time" json:"slot_start_date_time"`
	Epoch uint32 `ch:"epoch" json:"epoch"`
	EpochStartDateTime uint32 `ch:"epoch_start_date_time" json:"epoch_start_date_time"`
	WallclockSlot uint32 `ch:"wallclock_slot" json:"wallclock_slot"`
	WallclockSlotStartDateTime uint32 `ch:"wallclock_slot_start_date_time" json:"wallclock_slot_start_date_time"`
	WallclockEpoch uint32 `ch:"wallclock_epoch" json:"wallclock_epoch"`
	WallclockEpochStartDateTime uint32 `ch:"wallclock_epoch_start_date_time" json:"wallclock_epoch_start_date_time"`
	BlockNumber uint64 `ch:"block_number" json:"block_number"`
	RelayName string `ch:"relay_name" json:"relay_name"`
	BlockHash *string `ch:"block_hash" json:"block_hash"`
	ProposerPubkey string `ch:"proposer_pubkey" json:"proposer_pubkey"`
	BuilderPubkey string `ch:"builder_pubkey" json:"builder_pubkey"`
	ProposerFeeRecipient *string `ch:"proposer_fee_recipient" json:"proposer_fee_recipient"`
	GasLimit uint64 `ch:"gas_limit" json:"gas_limit"`
	GasUsed uint64 `ch:"gas_used" json:"gas_used"`
	Value string `ch:"value" json:"value"`
	NumTx uint32 `ch:"num_tx" json:"num_tx"`
	MetaClientName string `ch:"meta_client_name" json:"meta_client_name"`
	MetaClientVersion string `ch:"meta_client_version" json:"meta_client_version"`
	MetaClientImplementation string `ch:"meta_client_implementation" json:"meta_client_implementation"`
	MetaClientOs string `ch:"meta_client_os" json:"meta_client_os"`
	MetaClientIp *net.IP `ch:"meta_client_ip" json:"meta_client_ip"`
	MetaClientGeoCity string `ch:"meta_client_geo_city" json:"meta_client_geo_city"`
	MetaClientGeoCountry string `ch:"meta_client_geo_country" json:"meta_client_geo_country"`
	MetaClientGeoCountryCode string `ch:"meta_client_geo_country_code" json:"meta_client_geo_country_code"`
	MetaClientGeoContinentCode string `ch:"meta_client_geo_continent_code" json:"meta_client_geo_continent_code"`
	MetaClientGeoLongitude *float64 `ch:"meta_client_geo_longitude" json:"meta_client_geo_longitude"`
	MetaClientGeoLatitude *float64 `ch:"meta_client_geo_latitude" json:"meta_client_geo_latitude"`
	MetaClientGeoAutonomousSystemNumber *uint32 `ch:"meta_client_geo_autonomous_system_number" json:"meta_client_geo_autonomous_system_number"`
	MetaClientGeoAutonomousSystemOrganization *string `ch:"meta_client_geo_autonomous_system_organization" json:"meta_client_geo_autonomous_system_organization"`
	MetaNetworkName string `ch:"meta_network_name" json:"meta_network_name"`
}

// TableName returns the ClickHouse table this row maps to.
func (MevRelayProposerPayloadDeliveredRow) TableName() string {
	return "mev_relay_proposer_payload_delivered"
}

// ToProto converts the row to its protobuf message.
func (r *MevRelayProposerPayloadDeliveredRow) ToProto() *MevRelayProposerPayloadDelivered {
	p := &MevRelayProposerPayloadDelivered{}

	p.UpdatedDateTime = r.UpdatedDateTime
	p.EventDateTime = r.EventDateTime
	p.Slot = r.Slot
	p.SlotStartDateTime = r.SlotStartDateTime
	p.Epoch = r.Epoch
	p.EpochStartDateTime = r.EpochStartDateTime
	p.WallclockSlot = r.WallclockSlot
	p.WallclockSlotStartDateTime = r.WallclockSlotStartDateTime
	p.WallclockEpoch = r.WallclockEpoch
	p.WallclockEpochStartDateTime = r.WallclockEpochStartDateTime
	p.BlockNumber = r.BlockNumber
	p.RelayName = r.RelayName
	if r.BlockHash != nil {
		p.BlockHash = *r.BlockHash
	}
	p.ProposerPubkey = r.ProposerPubkey
	p.BuilderPubkey = r.BuilderPubkey
	if r.ProposerFeeRecipient != nil {
		p.ProposerFeeRecipient = *r.ProposerFeeRecipient
	}
	p.GasLimit = r.GasLimit
	p.GasUsed = r.GasUsed
	p.Value = r.Value
	p.NumTx = r.NumTx
	p.MetaClientName = r.MetaClientName
	p.MetaClientVersion = r.MetaClientVersion
	p.MetaClientImplementation = r.MetaClientImplementation
	p.MetaClientOs = r.MetaClientOs
	if r.MetaClientIp != nil {
		p.MetaClientIp = wrapperspb.String(r.MetaClientIp.String())
	}
	p.MetaClientGeoCity = r.MetaClientGeoCity
	p.MetaClientGeoCountry = r.MetaClientGeoCountry
	p.MetaClientGeoCountryCode = r.MetaClientGeoCountryCode
	p.MetaClientGeoContinentCode = r.MetaClientGeoContinentCode
	if r.MetaClientGeoLongitude != nil {
		p.MetaClientGeoLongitude = wrapperspb.Double(*r.MetaClientGeoLongitude)
	}
	if r.MetaClientGeoLatitude != nil {
		p.MetaClientGeoLatitude = wrapperspb.Double(*r.MetaClientGeoLatitude)
	}
	if r.MetaClientGeoAutonomousSystemNumber != nil {
		p.MetaClientGeoAutonomousSystemNumber = wrapperspb.UInt32(*r.MetaClientGeoAutonomousSystemNumber)
	}
	if r.MetaClientGeoAutonomousSystemOrganization != nil {
		p.MetaClientGeoAutonomousSystemOrganization = wrapperspb.String(*r.MetaClientGeoAutonomousSystemOrganization)
	}
	p.MetaNetworkName = r.MetaNetworkName
	return p
}
