// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: schema_migrations_xatu.proto

package clickhouse

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SchemaMigrationsXatu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version  int64  `protobuf:"varint,11,opt,name=version,proto3" json:"version,omitempty"`
	Dirty    uint32 `protobuf:"varint,12,opt,name=dirty,proto3" json:"dirty,omitempty"`
	Sequence uint64 `protobuf:"varint,13,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (x *SchemaMigrationsXatu) Reset() {
	*x = SchemaMigrationsXatu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_migrations_xatu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SchemaMigrationsXatu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaMigrationsXatu) ProtoMessage() {}

func (x *SchemaMigrationsXatu) ProtoReflect() protoreflect.Message {
	mi := &file_schema_migrations_xatu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaMigrationsXatu.ProtoReflect.Descriptor instead.
func (*SchemaMigrationsXatu) Descriptor() ([]byte, []int) {
	return file_schema_migrations_xatu_proto_rawDescGZIP(), []int{0}
}

func (x *SchemaMigrationsXatu) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SchemaMigrationsXatu) GetDirty() uint32 {
	if x != nil {
		return x.Dirty
	}
	return 0
}

func (x *SchemaMigrationsXatu) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

var File_schema_migrations_xatu_proto protoreflect.FileDescriptor

var file_schema_migrations_xatu_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x6d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x5f, 0x78, 0x61, 0x74, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x63, 0x6c, 0x69, 0x63, 0x6b, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x62, 0x0a,
	0x14, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x4d, 0x69, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x58, 0x61, 0x74, 0x75, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x64, 0x69, 0x72, 0x74, 0x79, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x64, 0x69, 0x72, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x65, 0x74, 0x68, 0x70, 0x61, 0x6e, 0x64, 0x61, 0x6f, 0x70, 0x73, 0x2f, 0x78, 0x61, 0x74, 0x75,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x63, 0x6b,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schema_migrations_xatu_proto_rawDescOnce sync.Once
	file_schema_migrations_xatu_proto_rawDescData = file_schema_migrations_xatu_proto_rawDesc
)

func file_schema_migrations_xatu_proto_rawDescGZIP() []byte {
	file_schema_migrations_xatu_proto_rawDescOnce.Do(func() {
		file_schema_migrations_xatu_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_migrations_xatu_proto_rawDescData)
	})
	return file_schema_migrations_xatu_proto_rawDescData
}

var file_schema_migrations_xatu_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schema_migrations_xatu_proto_goTypes = []any{
	(*SchemaMigrationsXatu)(nil), // 0: clickhouse.v1.SchemaMigrationsXatu
}
var file_schema_migrations_xatu_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schema_migrations_xatu_proto_init() }
func file_schema_migrations_xatu_proto_init() {
	if File_schema_migrations_xatu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schema_migrations_xatu_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SchemaMigrationsXatu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_migrations_xatu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_migrations_xatu_proto_goTypes,
		DependencyIndexes: file_schema_migrations_xatu_proto_depIdxs,
		MessageInfos:      file_schema_migrations_xatu_proto_msgTypes,
	}.Build()
	File_schema_migrations_xatu_proto = out.File
	file_schema_migrations_xatu_proto_rawDesc = nil
	file_schema_migrations_xatu_proto_goTypes = nil
	file_schema_migrations_xatu_proto_depIdxs = nil
}
