// Code generated by chgo-rowgen; DO NOT EDIT.

package canonical

import (
	"github.com/ClickHouse/ch-go/proto"

	"github.com/ethpandaops/xatu/pkg/clickhouse/route"
	"github.com/ethpandaops/xatu/pkg/proto/xatu"
)

const canonicalBeaconValidatorsTableName route.TableName = "canonical_beacon_validators"

type canonicalBeaconValidatorsBatch struct {
	UpdatedDateTime            proto.ColDateTime
	Epoch                      proto.ColUInt32
	EpochStartDateTime         proto.ColDateTime
	Index                      proto.ColUInt32
	Balance                    *proto.ColNullable[uint64]
	Status                     proto.ColStr
	EffectiveBalance           *proto.ColNullable[uint64]
	Slashed                    proto.ColBool
	ActivationEpoch            *proto.ColNullable[uint64]
	ActivationEligibilityEpoch *proto.ColNullable[uint64]
	ExitEpoch                  *proto.ColNullable[uint64]
	WithdrawableEpoch          *proto.ColNullable[uint64]
	MetaNetworkName            proto.ColStr
	rows                       int
}

func newcanonicalBeaconValidatorsBatch() *canonicalBeaconValidatorsBatch {
	return &canonicalBeaconValidatorsBatch{
		Balance:                    new(proto.ColUInt64).Nullable(),
		EffectiveBalance:           new(proto.ColUInt64).Nullable(),
		ActivationEpoch:            new(proto.ColUInt64).Nullable(),
		ActivationEligibilityEpoch: new(proto.ColUInt64).Nullable(),
		ExitEpoch:                  new(proto.ColUInt64).Nullable(),
		WithdrawableEpoch:          new(proto.ColUInt64).Nullable(),
	}
}

func (b *canonicalBeaconValidatorsBatch) Rows() int {
	return b.rows
}

func (b *canonicalBeaconValidatorsBatch) appendMetadata(event *xatu.DecoratedEvent) {
	if event == nil || event.GetMeta() == nil {
		b.MetaNetworkName.Append("")
		return
	}

	b.MetaNetworkName.Append(event.GetMeta().GetClient().GetEthereum().GetNetwork().GetName())
}

func (b *canonicalBeaconValidatorsBatch) Input() proto.Input {
	return proto.Input{
		{Name: "updated_date_time", Data: &b.UpdatedDateTime},
		{Name: "epoch", Data: &b.Epoch},
		{Name: "epoch_start_date_time", Data: &b.EpochStartDateTime},
		{Name: "index", Data: &b.Index},
		{Name: "balance", Data: b.Balance},
		{Name: "status", Data: &b.Status},
		{Name: "effective_balance", Data: b.EffectiveBalance},
		{Name: "slashed", Data: &b.Slashed},
		{Name: "activation_epoch", Data: b.ActivationEpoch},
		{Name: "activation_eligibility_epoch", Data: b.ActivationEligibilityEpoch},
		{Name: "exit_epoch", Data: b.ExitEpoch},
		{Name: "withdrawable_epoch", Data: b.WithdrawableEpoch},
		{Name: "meta_network_name", Data: &b.MetaNetworkName},
	}
}

func (b *canonicalBeaconValidatorsBatch) Reset() {
	b.UpdatedDateTime.Reset()
	b.Epoch.Reset()
	b.EpochStartDateTime.Reset()
	b.Index.Reset()
	b.Balance.Reset()
	b.Status.Reset()
	b.EffectiveBalance.Reset()
	b.Slashed.Reset()
	b.ActivationEpoch.Reset()
	b.ActivationEligibilityEpoch.Reset()
	b.ExitEpoch.Reset()
	b.WithdrawableEpoch.Reset()
	b.MetaNetworkName.Reset()
	b.rows = 0
}

func (b *canonicalBeaconValidatorsBatch) Snapshot() []map[string]any {
	n := b.rows
	out := make([]map[string]any, n)

	for i := 0; i < n; i++ {
		row := make(map[string]any, 13)
		row["updated_date_time"] = b.UpdatedDateTime.Row(i).Unix()
		row["epoch"] = b.Epoch.Row(i)
		row["epoch_start_date_time"] = b.EpochStartDateTime.Row(i).Unix()
		row["index"] = b.Index.Row(i)
		if v := b.Balance.Row(i); v.Set {
			row["balance"] = v.Value
		} else {
			row["balance"] = nil
		}
		row["status"] = b.Status.Row(i)
		if v := b.EffectiveBalance.Row(i); v.Set {
			row["effective_balance"] = v.Value
		} else {
			row["effective_balance"] = nil
		}
		row["slashed"] = b.Slashed.Row(i)
		if v := b.ActivationEpoch.Row(i); v.Set {
			row["activation_epoch"] = v.Value
		} else {
			row["activation_epoch"] = nil
		}
		if v := b.ActivationEligibilityEpoch.Row(i); v.Set {
			row["activation_eligibility_epoch"] = v.Value
		} else {
			row["activation_eligibility_epoch"] = nil
		}
		if v := b.ExitEpoch.Row(i); v.Set {
			row["exit_epoch"] = v.Value
		} else {
			row["exit_epoch"] = nil
		}
		if v := b.WithdrawableEpoch.Row(i); v.Set {
			row["withdrawable_epoch"] = v.Value
		} else {
			row["withdrawable_epoch"] = nil
		}
		row["meta_network_name"] = b.MetaNetworkName.Row(i)
		out[i] = row
	}

	return out
}
