# Cannon smoke test configuration
#
# This config defines which event types to test in the cannon smoke test.
# The test dynamically fetches the current finalized epoch from the beacon node
# and seeds cannon to start processing from (finalized_epoch - epoch_offset).
#
# Only event types that are GUARANTEED to exist in every epoch should be tested
# to avoid flaky tests. Rare events like slashings and deposits are excluded.
#
# The assertions verify that data flows through the entire pipeline:
# Beacon Node -> Cannon -> Xatu Server -> Kafka -> Vector -> ClickHouse

network:
  name: mainnet
  id: 1

# How many epochs back from finalized to start processing
# Lower = faster test, but needs recent data available on beacon node
epoch_offset: 3

# Event types to test - these must exist in every epoch
# Each type needs a corresponding ClickHouse table for assertions
event_types:
  - name: BEACON_API_ETH_V2_BEACON_BLOCK
    table: canonical_beacon_block
    description: "Beacon blocks - one per slot"

  - name: BEACON_API_ETH_V2_BEACON_BLOCK_WITHDRAWAL
    table: canonical_beacon_block_withdrawal
    description: "Withdrawals - multiple per block post-Capella"

  - name: BEACON_API_ETH_V2_BEACON_BLOCK_EXECUTION_TRANSACTION
    table: canonical_beacon_block_execution_transaction
    description: "Execution transactions - multiple per block"

  - name: BEACON_API_ETH_V1_PROPOSER_DUTY
    table: canonical_beacon_proposer_duty
    description: "Proposer duties - 32 per epoch"

  - name: BEACON_API_ETH_V1_BEACON_COMMITTEE
    table: canonical_beacon_committee
    description: "Beacon committees - many per epoch"
