ALTER TABLE default.beacon_api_eth_v1_events_head  ON CLUSTER '{cluster}'
MODIFY COMMENT '',
COMMENT COLUMN event_date_time '',
COMMENT COLUMN slot '',
COMMENT COLUMN slot_start_date_time '',
COMMENT COLUMN propagation_slot_start_diff '',
COMMENT COLUMN block '',
COMMENT COLUMN epoch '',
COMMENT COLUMN epoch_start_date_time '',
COMMENT COLUMN epoch_transition '',
COMMENT COLUMN execution_optimistic '',
COMMENT COLUMN previous_duty_dependent_root '',
COMMENT COLUMN current_duty_dependent_root '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_client_id '',
COMMENT COLUMN meta_client_version '',
COMMENT COLUMN meta_client_implementation '',
COMMENT COLUMN meta_client_os '',
COMMENT COLUMN meta_client_ip '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_country '',
COMMENT COLUMN meta_client_geo_country_code '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_client_geo_autonomous_system_number '',
COMMENT COLUMN meta_client_geo_autonomous_system_organization '',
COMMENT COLUMN meta_network_id '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_consensus_version '',
COMMENT COLUMN meta_consensus_version_major '',
COMMENT COLUMN meta_consensus_version_minor '',
COMMENT COLUMN meta_consensus_version_patch '',
COMMENT COLUMN meta_consensus_implementation '',
COMMENT COLUMN meta_labels '';

ALTER TABLE default.beacon_api_eth_v1_events_head_local  ON CLUSTER '{cluster}'
MODIFY COMMENT '',
COMMENT COLUMN event_date_time '',
COMMENT COLUMN slot '',
COMMENT COLUMN slot_start_date_time '',
COMMENT COLUMN propagation_slot_start_diff '',
COMMENT COLUMN block '',
COMMENT COLUMN epoch '',
COMMENT COLUMN epoch_start_date_time '',
COMMENT COLUMN epoch_transition '',
COMMENT COLUMN execution_optimistic '',
COMMENT COLUMN previous_duty_dependent_root '',
COMMENT COLUMN current_duty_dependent_root '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_client_id '',
COMMENT COLUMN meta_client_version '',
COMMENT COLUMN meta_client_implementation '',
COMMENT COLUMN meta_client_os '',
COMMENT COLUMN meta_client_ip '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_country '',
COMMENT COLUMN meta_client_geo_country_code '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_client_geo_autonomous_system_number '',
COMMENT COLUMN meta_client_geo_autonomous_system_organization '',
COMMENT COLUMN meta_network_id '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_consensus_version '',
COMMENT COLUMN meta_consensus_version_major '',
COMMENT COLUMN meta_consensus_version_minor '',
COMMENT COLUMN meta_consensus_version_patch '',
COMMENT COLUMN meta_consensus_implementation '',
COMMENT COLUMN meta_labels '';

ALTER TABLE default.beacon_api_eth_v1_events_block  ON CLUSTER '{cluster}'
MODIFY COMMENT '',
COMMENT COLUMN event_date_time '',
COMMENT COLUMN slot '',
COMMENT COLUMN slot_start_date_time '',
COMMENT COLUMN propagation_slot_start_diff '',
COMMENT COLUMN block '',
COMMENT COLUMN epoch '',
COMMENT COLUMN epoch_start_date_time '',
COMMENT COLUMN execution_optimistic '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_client_id '',
COMMENT COLUMN meta_client_version '',
COMMENT COLUMN meta_client_implementation '',
COMMENT COLUMN meta_client_os '',
COMMENT COLUMN meta_client_ip '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_country '',
COMMENT COLUMN meta_client_geo_country_code '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_client_geo_autonomous_system_number '',
COMMENT COLUMN meta_client_geo_autonomous_system_organization '',
COMMENT COLUMN meta_network_id '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_consensus_version '',
COMMENT COLUMN meta_consensus_version_major '',
COMMENT COLUMN meta_consensus_version_minor '',
COMMENT COLUMN meta_consensus_version_patch '',
COMMENT COLUMN meta_consensus_implementation '',
COMMENT COLUMN meta_labels '';

ALTER TABLE default.beacon_api_eth_v1_events_block_local  ON CLUSTER '{cluster}'
MODIFY COMMENT '',
COMMENT COLUMN event_date_time '',
COMMENT COLUMN slot '',
COMMENT COLUMN slot_start_date_time '',
COMMENT COLUMN propagation_slot_start_diff '',
COMMENT COLUMN block '',
COMMENT COLUMN epoch '',
COMMENT COLUMN epoch_start_date_time '',
COMMENT COLUMN execution_optimistic '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_client_id '',
COMMENT COLUMN meta_client_version '',
COMMENT COLUMN meta_client_implementation '',
COMMENT COLUMN meta_client_os '',
COMMENT COLUMN meta_client_ip '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_country '',
COMMENT COLUMN meta_client_geo_country_code '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_client_geo_autonomous_system_number '',
COMMENT COLUMN meta_client_geo_autonomous_system_organization '',
COMMENT COLUMN meta_network_id '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_consensus_version '',
COMMENT COLUMN meta_consensus_version_major '',
COMMENT COLUMN meta_consensus_version_minor '',
COMMENT COLUMN meta_consensus_version_patch '',
COMMENT COLUMN meta_consensus_implementation '',
COMMENT COLUMN meta_labels '';

ALTER TABLE default.beacon_api_eth_v1_events_attestation  ON CLUSTER '{cluster}'
MODIFY COMMENT '',
COMMENT COLUMN event_date_time '',
COMMENT COLUMN slot '',
COMMENT COLUMN slot_start_date_time '',
COMMENT COLUMN propagation_slot_start_diff '',
COMMENT COLUMN committee_index '',
COMMENT COLUMN attesting_validator_index '',
COMMENT COLUMN attesting_validator_committee_index '',
COMMENT COLUMN signature '',
COMMENT COLUMN aggregation_bits '',
COMMENT COLUMN beacon_block_root '',
COMMENT COLUMN epoch '',
COMMENT COLUMN epoch_start_date_time '',
COMMENT COLUMN source_epoch '',
COMMENT COLUMN source_epoch_start_date_time '',
COMMENT COLUMN source_root '',
COMMENT COLUMN target_epoch '',
COMMENT COLUMN target_epoch_start_date_time '',
COMMENT COLUMN target_root '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_client_id '',
COMMENT COLUMN meta_client_version '',
COMMENT COLUMN meta_client_implementation '',
COMMENT COLUMN meta_client_os '',
COMMENT COLUMN meta_client_ip '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_country '',
COMMENT COLUMN meta_client_geo_country_code '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_client_geo_autonomous_system_number '',
COMMENT COLUMN meta_client_geo_autonomous_system_organization '',
COMMENT COLUMN meta_network_id '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_consensus_version '',
COMMENT COLUMN meta_consensus_version_major '',
COMMENT COLUMN meta_consensus_version_minor '',
COMMENT COLUMN meta_consensus_version_patch '',
COMMENT COLUMN meta_consensus_implementation '',
COMMENT COLUMN meta_labels '';

ALTER TABLE default.beacon_api_eth_v1_events_attestation_local  ON CLUSTER '{cluster}'
MODIFY COMMENT '',
COMMENT COLUMN event_date_time '',
COMMENT COLUMN slot '',
COMMENT COLUMN slot_start_date_time '',
COMMENT COLUMN propagation_slot_start_diff '',
COMMENT COLUMN committee_index '',
COMMENT COLUMN attesting_validator_index '',
COMMENT COLUMN attesting_validator_committee_index '',
COMMENT COLUMN signature '',
COMMENT COLUMN aggregation_bits '',
COMMENT COLUMN beacon_block_root '',
COMMENT COLUMN epoch '',
COMMENT COLUMN epoch_start_date_time '',
COMMENT COLUMN source_epoch '',
COMMENT COLUMN source_epoch_start_date_time '',
COMMENT COLUMN source_root '',
COMMENT COLUMN target_epoch '',
COMMENT COLUMN target_epoch_start_date_time '',
COMMENT COLUMN target_root '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_client_id '',
COMMENT COLUMN meta_client_version '',
COMMENT COLUMN meta_client_implementation '',
COMMENT COLUMN meta_client_os '',
COMMENT COLUMN meta_client_ip '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_country '',
COMMENT COLUMN meta_client_geo_country_code '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_client_geo_autonomous_system_number '',
COMMENT COLUMN meta_client_geo_autonomous_system_organization '',
COMMENT COLUMN meta_network_id '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_consensus_version '',
COMMENT COLUMN meta_consensus_version_major '',
COMMENT COLUMN meta_consensus_version_minor '',
COMMENT COLUMN meta_consensus_version_patch '',
COMMENT COLUMN meta_consensus_implementation '',
COMMENT COLUMN meta_labels '';

ALTER TABLE default.beacon_api_eth_v1_events_voluntary_exit  ON CLUSTER '{cluster}'
MODIFY COMMENT '',
COMMENT COLUMN event_date_time '',
COMMENT COLUMN epoch '',
COMMENT COLUMN epoch_start_date_time '',
COMMENT COLUMN validator_index '',
COMMENT COLUMN signature '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_client_id '',
COMMENT COLUMN meta_client_version '',
COMMENT COLUMN meta_client_implementation '',
COMMENT COLUMN meta_client_os '',
COMMENT COLUMN meta_client_ip '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_country '',
COMMENT COLUMN meta_client_geo_country_code '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_client_geo_autonomous_system_number '',
COMMENT COLUMN meta_client_geo_autonomous_system_organization '',
COMMENT COLUMN meta_network_id '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_consensus_version '',
COMMENT COLUMN meta_consensus_version_major '',
COMMENT COLUMN meta_consensus_version_minor '',
COMMENT COLUMN meta_consensus_version_patch '',
COMMENT COLUMN meta_consensus_implementation '',
COMMENT COLUMN meta_labels '';

ALTER TABLE default.beacon_api_eth_v1_events_voluntary_exit_local  ON CLUSTER '{cluster}'
MODIFY COMMENT '',
COMMENT COLUMN event_date_time '',
COMMENT COLUMN epoch '',
COMMENT COLUMN epoch_start_date_time '',
COMMENT COLUMN validator_index '',
COMMENT COLUMN signature '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_client_id '',
COMMENT COLUMN meta_client_version '',
COMMENT COLUMN meta_client_implementation '',
COMMENT COLUMN meta_client_os '',
COMMENT COLUMN meta_client_ip '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_country '',
COMMENT COLUMN meta_client_geo_country_code '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_client_geo_autonomous_system_number '',
COMMENT COLUMN meta_client_geo_autonomous_system_organization '',
COMMENT COLUMN meta_network_id '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_consensus_version '',
COMMENT COLUMN meta_consensus_version_major '',
COMMENT COLUMN meta_consensus_version_minor '',
COMMENT COLUMN meta_consensus_version_patch '',
COMMENT COLUMN meta_consensus_implementation '',
COMMENT COLUMN meta_labels '';

ALTER TABLE default.beacon_api_eth_v1_events_finalized_checkpoint ON CLUSTER '{cluster}'
MODIFY COMMENT '',
COMMENT COLUMN event_date_time '',
COMMENT COLUMN block '',
COMMENT COLUMN state '',
COMMENT COLUMN epoch '',
COMMENT COLUMN epoch_start_date_time '',
COMMENT COLUMN execution_optimistic '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_client_id '',
COMMENT COLUMN meta_client_version '',
COMMENT COLUMN meta_client_implementation '',
COMMENT COLUMN meta_client_os '',
COMMENT COLUMN meta_client_ip '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_country '',
COMMENT COLUMN meta_client_geo_country_code '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_client_geo_autonomous_system_number '',
COMMENT COLUMN meta_client_geo_autonomous_system_organization '',
COMMENT COLUMN meta_network_id '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_consensus_version '',
COMMENT COLUMN meta_consensus_version_major '',
COMMENT COLUMN meta_consensus_version_minor '',
COMMENT COLUMN meta_consensus_version_patch '',
COMMENT COLUMN meta_consensus_implementation '',
COMMENT COLUMN meta_labels '';

ALTER TABLE default.beacon_api_eth_v1_events_finalized_checkpoint_local ON CLUSTER '{cluster}'
MODIFY COMMENT '',
COMMENT COLUMN event_date_time '',
COMMENT COLUMN block '',
COMMENT COLUMN state '',
COMMENT COLUMN epoch '',
COMMENT COLUMN epoch_start_date_time '',
COMMENT COLUMN execution_optimistic '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_client_id '',
COMMENT COLUMN meta_client_version '',
COMMENT COLUMN meta_client_implementation '',
COMMENT COLUMN meta_client_os '',
COMMENT COLUMN meta_client_ip '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_country '',
COMMENT COLUMN meta_client_geo_country_code '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_client_geo_autonomous_system_number '',
COMMENT COLUMN meta_client_geo_autonomous_system_organization '',
COMMENT COLUMN meta_network_id '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_consensus_version '',
COMMENT COLUMN meta_consensus_version_major '',
COMMENT COLUMN meta_consensus_version_minor '',
COMMENT COLUMN meta_consensus_version_patch '',
COMMENT COLUMN meta_consensus_implementation '',
COMMENT COLUMN meta_labels '';

ALTER TABLE default.beacon_api_eth_v1_events_chain_reorg ON CLUSTER '{cluster}'
MODIFY COMMENT '',
COMMENT COLUMN event_date_time '',
COMMENT COLUMN slot '',
COMMENT COLUMN slot_start_date_time '',
COMMENT COLUMN propagation_slot_start_diff '',
COMMENT COLUMN depth '',
COMMENT COLUMN old_head_block '',
COMMENT COLUMN new_head_block '',
COMMENT COLUMN old_head_state '',
COMMENT COLUMN new_head_state '',
COMMENT COLUMN epoch '',
COMMENT COLUMN epoch_start_date_time '',
COMMENT COLUMN execution_optimistic '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_client_id '',
COMMENT COLUMN meta_client_version '',
COMMENT COLUMN meta_client_implementation '',
COMMENT COLUMN meta_client_os '',
COMMENT COLUMN meta_client_ip '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_country '',
COMMENT COLUMN meta_client_geo_country_code '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_client_geo_autonomous_system_number '',
COMMENT COLUMN meta_client_geo_autonomous_system_organization '',
COMMENT COLUMN meta_network_id '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_consensus_version '',
COMMENT COLUMN meta_consensus_version_major '',
COMMENT COLUMN meta_consensus_version_minor '',
COMMENT COLUMN meta_consensus_version_patch '',
COMMENT COLUMN meta_consensus_implementation '',
COMMENT COLUMN meta_labels '';

ALTER TABLE default.beacon_api_eth_v1_events_chain_reorg_local ON CLUSTER '{cluster}'
MODIFY COMMENT '',
COMMENT COLUMN event_date_time '',
COMMENT COLUMN slot '',
COMMENT COLUMN slot_start_date_time '',
COMMENT COLUMN propagation_slot_start_diff '',
COMMENT COLUMN depth '',
COMMENT COLUMN old_head_block '',
COMMENT COLUMN new_head_block '',
COMMENT COLUMN old_head_state '',
COMMENT COLUMN new_head_state '',
COMMENT COLUMN epoch '',
COMMENT COLUMN epoch_start_date_time '',
COMMENT COLUMN execution_optimistic '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_client_id '',
COMMENT COLUMN meta_client_version '',
COMMENT COLUMN meta_client_implementation '',
COMMENT COLUMN meta_client_os '',
COMMENT COLUMN meta_client_ip '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_country '',
COMMENT COLUMN meta_client_geo_country_code '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_client_geo_autonomous_system_number '',
COMMENT COLUMN meta_client_geo_autonomous_system_organization '',
COMMENT COLUMN meta_network_id '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_consensus_version '',
COMMENT COLUMN meta_consensus_version_major '',
COMMENT COLUMN meta_consensus_version_minor '',
COMMENT COLUMN meta_consensus_version_patch '',
COMMENT COLUMN meta_consensus_implementation '',
COMMENT COLUMN meta_labels '';

ALTER TABLE default.beacon_api_eth_v1_events_contribution_and_proof ON CLUSTER '{cluster}'
MODIFY COMMENT '',
COMMENT COLUMN event_date_time '',
COMMENT COLUMN aggregator_index '',
COMMENT COLUMN contribution_slot '',
COMMENT COLUMN contribution_slot_start_date_time '',
COMMENT COLUMN contribution_propagation_slot_start_diff '',
COMMENT COLUMN contribution_beacon_block_root '',
COMMENT COLUMN contribution_subcommittee_index '',
COMMENT COLUMN contribution_aggregation_bits '',
COMMENT COLUMN contribution_signature '',
COMMENT COLUMN contribution_epoch '',
COMMENT COLUMN contribution_epoch_start_date_time '',
COMMENT COLUMN selection_proof '',
COMMENT COLUMN signature '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_client_id '',
COMMENT COLUMN meta_client_version '',
COMMENT COLUMN meta_client_implementation '',
COMMENT COLUMN meta_client_os '',
COMMENT COLUMN meta_client_ip '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_country '',
COMMENT COLUMN meta_client_geo_country_code '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_client_geo_autonomous_system_number '',
COMMENT COLUMN meta_client_geo_autonomous_system_organization '',
COMMENT COLUMN meta_network_id '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_consensus_version '',
COMMENT COLUMN meta_consensus_version_major '',
COMMENT COLUMN meta_consensus_version_minor '',
COMMENT COLUMN meta_consensus_version_patch '',
COMMENT COLUMN meta_consensus_implementation '',
COMMENT COLUMN meta_labels '';

ALTER TABLE default.beacon_api_eth_v1_events_contribution_and_proof_local ON CLUSTER '{cluster}'
MODIFY COMMENT '',
COMMENT COLUMN event_date_time '',
COMMENT COLUMN aggregator_index '',
COMMENT COLUMN contribution_slot '',
COMMENT COLUMN contribution_slot_start_date_time '',
COMMENT COLUMN contribution_propagation_slot_start_diff '',
COMMENT COLUMN contribution_beacon_block_root '',
COMMENT COLUMN contribution_subcommittee_index '',
COMMENT COLUMN contribution_aggregation_bits '',
COMMENT COLUMN contribution_signature '',
COMMENT COLUMN contribution_epoch '',
COMMENT COLUMN contribution_epoch_start_date_time '',
COMMENT COLUMN selection_proof '',
COMMENT COLUMN signature '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_client_id '',
COMMENT COLUMN meta_client_version '',
COMMENT COLUMN meta_client_implementation '',
COMMENT COLUMN meta_client_os '',
COMMENT COLUMN meta_client_ip '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_country '',
COMMENT COLUMN meta_client_geo_country_code '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_client_geo_autonomous_system_number '',
COMMENT COLUMN meta_client_geo_autonomous_system_organization '',
COMMENT COLUMN meta_network_id '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_consensus_version '',
COMMENT COLUMN meta_consensus_version_major '',
COMMENT COLUMN meta_consensus_version_minor '',
COMMENT COLUMN meta_consensus_version_patch '',
COMMENT COLUMN meta_consensus_implementation '',
COMMENT COLUMN meta_labels '';

ALTER TABLE default.beacon_api_slot ON CLUSTER '{cluster}'
MODIFY COMMENT '',
COMMENT COLUMN slot '',
COMMENT COLUMN slot_start_date_time '',
COMMENT COLUMN epoch '',
COMMENT COLUMN epoch_start_date_time '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_consensus_implementation '',
COMMENT COLUMN meta_consensus_version '',
COMMENT COLUMN blocks'',
COMMENT COLUMN attestations'';

ALTER TABLE default.beacon_api_slot_local ON CLUSTER '{cluster}'
MODIFY COMMENT '',
COMMENT COLUMN slot '',
COMMENT COLUMN slot_start_date_time '',
COMMENT COLUMN epoch '',
COMMENT COLUMN epoch_start_date_time '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_consensus_implementation '',
COMMENT COLUMN meta_consensus_version '',
COMMENT COLUMN blocks'',
COMMENT COLUMN attestations'';

ALTER TABLE default.mempool_transaction ON CLUSTER '{cluster}'
MODIFY COMMENT '',
COMMENT COLUMN event_date_time '',
COMMENT COLUMN hash '',
COMMENT COLUMN from'',
COMMENT COLUMN to'',
COMMENT COLUMN nonce '',
COMMENT COLUMN gas_price '',
COMMENT COLUMN gas '',
COMMENT COLUMN value '',
COMMENT COLUMN size '',
COMMENT COLUMN call_data_size '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_client_id '',
COMMENT COLUMN meta_client_version '',
COMMENT COLUMN meta_client_implementation '',
COMMENT COLUMN meta_client_os '',
COMMENT COLUMN meta_client_ip '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_country '',
COMMENT COLUMN meta_client_geo_country_code '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_client_geo_autonomous_system_number '',
COMMENT COLUMN meta_client_geo_autonomous_system_organization '',
COMMENT COLUMN meta_network_id '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_execution_fork_id_hash '',
COMMENT COLUMN meta_execution_fork_id_next '',
COMMENT COLUMN meta_labels '';

ALTER TABLE default.mempool_transaction_local ON CLUSTER '{cluster}'
MODIFY COMMENT '',
COMMENT COLUMN event_date_time '',
COMMENT COLUMN hash '',
COMMENT COLUMN from'',
COMMENT COLUMN to'',
COMMENT COLUMN nonce '',
COMMENT COLUMN gas_price '',
COMMENT COLUMN gas '',
COMMENT COLUMN value '',
COMMENT COLUMN size '',
COMMENT COLUMN call_data_size '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_client_id '',
COMMENT COLUMN meta_client_version '',
COMMENT COLUMN meta_client_implementation '',
COMMENT COLUMN meta_client_os '',
COMMENT COLUMN meta_client_ip '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_country '',
COMMENT COLUMN meta_client_geo_country_code '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_client_geo_autonomous_system_number '',
COMMENT COLUMN meta_client_geo_autonomous_system_organization '',
COMMENT COLUMN meta_network_id '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_execution_fork_id_hash '',
COMMENT COLUMN meta_execution_fork_id_next '',
COMMENT COLUMN meta_labels '';

ALTER TABLE default.beacon_api_eth_v2_beacon_block ON CLUSTER '{cluster}'
MODIFY COMMENT '',
COMMENT COLUMN event_date_time '',
COMMENT COLUMN slot '',
COMMENT COLUMN slot_start_date_time '',
COMMENT COLUMN epoch '',
COMMENT COLUMN epoch_start_date_time '',
COMMENT COLUMN block_root '',
COMMENT COLUMN parent_root '',
COMMENT COLUMN state_root '',
COMMENT COLUMN proposer_index '',
COMMENT COLUMN eth1_data_block_hash '',
COMMENT COLUMN eth1_data_deposit_root '',
COMMENT COLUMN execution_payload_block_hash '',
COMMENT COLUMN execution_payload_block_number '',
COMMENT COLUMN execution_payload_fee_recipient '',
COMMENT COLUMN execution_payload_state_root '',
COMMENT COLUMN execution_payload_parent_hash '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_client_id '',
COMMENT COLUMN meta_client_version '',
COMMENT COLUMN meta_client_implementation '',
COMMENT COLUMN meta_client_os '',
COMMENT COLUMN meta_client_ip '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_country '',
COMMENT COLUMN meta_client_geo_country_code '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_client_geo_autonomous_system_number '',
COMMENT COLUMN meta_client_geo_autonomous_system_organization '',
COMMENT COLUMN meta_network_id '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_execution_fork_id_hash '',
COMMENT COLUMN meta_execution_fork_id_next '',
COMMENT COLUMN meta_labels '';

ALTER TABLE default.beacon_api_eth_v2_beacon_block_local ON CLUSTER '{cluster}'
MODIFY COMMENT '',
COMMENT COLUMN event_date_time '',
COMMENT COLUMN slot '',
COMMENT COLUMN slot_start_date_time '',
COMMENT COLUMN epoch '',
COMMENT COLUMN epoch_start_date_time '',
COMMENT COLUMN block_root '',
COMMENT COLUMN parent_root '',
COMMENT COLUMN state_root '',
COMMENT COLUMN proposer_index '',
COMMENT COLUMN eth1_data_block_hash '',
COMMENT COLUMN eth1_data_deposit_root '',
COMMENT COLUMN execution_payload_block_hash '',
COMMENT COLUMN execution_payload_block_number '',
COMMENT COLUMN execution_payload_fee_recipient '',
COMMENT COLUMN execution_payload_state_root '',
COMMENT COLUMN execution_payload_parent_hash '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_client_id '',
COMMENT COLUMN meta_client_version '',
COMMENT COLUMN meta_client_implementation '',
COMMENT COLUMN meta_client_os '',
COMMENT COLUMN meta_client_ip '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_country '',
COMMENT COLUMN meta_client_geo_country_code '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_client_geo_autonomous_system_number '',
COMMENT COLUMN meta_client_geo_autonomous_system_organization '',
COMMENT COLUMN meta_network_id '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_execution_fork_id_hash '',
COMMENT COLUMN meta_execution_fork_id_next '',
COMMENT COLUMN meta_labels '';
