CREATE TABLE default.beacon_p2p_attestation_local on cluster '{cluster}'
(
    unique_key Int64,
    updated_date_time DateTime CODEC(DoubleDelta, ZSTD(1)),
    event_date_time DateTime64(3) CODEC(DoubleDelta, ZSTD(1)),
    slot UInt32 Codec(DoubleDelta, ZSTD(1)),
    slot_start_date_time DateTime Codec(DoubleDelta, ZSTD(1)),
    propagation_slot_start_diff UInt32 Codec(ZSTD(1)),
    committee_index LowCardinality(String),
    attesting_validator_index Nullable(UInt32) Codec(ZSTD(1)),
    attesting_validator_committee_index LowCardinality(String),
    signature String Codec(ZSTD(1)),
    aggregation_bits String Codec(ZSTD(1)),
    beacon_block_root FixedString(66) Codec(ZSTD(1)),
    epoch UInt32 Codec(DoubleDelta, ZSTD(1)),
    epoch_start_date_time DateTime Codec(DoubleDelta, ZSTD(1)),
    source_epoch UInt32 Codec(DoubleDelta, ZSTD(1)),
    source_epoch_start_date_time DateTime Codec(DoubleDelta, ZSTD(1)),
    source_root FixedString(66) Codec(ZSTD(1)),
    target_epoch UInt32 Codec(DoubleDelta, ZSTD(1)),
    target_epoch_start_date_time DateTime Codec(DoubleDelta, ZSTD(1)),
    target_root FixedString(66) Codec(ZSTD(1)),
    attestation_subnet LowCardinality(String),
    validated Bool,
    peer_id String CODEC(ZSTD(1)),
    peer_latency UInt32 Codec(ZSTD(1)),
    peer_version LowCardinality(String),
    peer_version_major LowCardinality(String),
    peer_version_minor LowCardinality(String),
    peer_version_patch LowCardinality(String),
    peer_implementation LowCardinality(String),
    peer_ip Nullable(IPv6) CODEC(ZSTD(1)),
    peer_geo_city LowCardinality(String) CODEC(ZSTD(1)),
    peer_geo_country LowCardinality(String) CODEC(ZSTD(1)),
    peer_geo_country_code LowCardinality(String) CODEC(ZSTD(1)),
    peer_geo_continent_code LowCardinality(String)  CODEC(ZSTD(1)),
    peer_geo_longitude Nullable(Float64)  CODEC(ZSTD(1)),
    peer_geo_latitude Nullable(Float64) CODEC(ZSTD(1)),
    peer_geo_autonomous_system_number Nullable(UInt32) CODEC(ZSTD(1)),
    peer_geo_autonomous_system_organization Nullable(String) CODEC(ZSTD(1)),
    meta_client_name LowCardinality(String),
    meta_client_id String CODEC(ZSTD(1)),
    meta_client_version LowCardinality(String),
    meta_client_implementation LowCardinality(String),
    meta_client_os LowCardinality(String),
    meta_client_ip Nullable(IPv6) CODEC(ZSTD(1)),
    meta_client_geo_city LowCardinality(String) CODEC(ZSTD(1)),
    meta_client_geo_country LowCardinality(String) CODEC(ZSTD(1)),
    meta_client_geo_country_code LowCardinality(String) CODEC(ZSTD(1)),
    meta_client_geo_continent_code LowCardinality(String)  CODEC(ZSTD(1)),
    meta_client_geo_longitude Nullable(Float64)  CODEC(ZSTD(1)),
    meta_client_geo_latitude Nullable(Float64) CODEC(ZSTD(1)),
    meta_client_geo_autonomous_system_number Nullable(UInt32) CODEC(ZSTD(1)),
    meta_client_geo_autonomous_system_organization Nullable(String) CODEC(ZSTD(1)),
    meta_network_id Int32 CODEC(DoubleDelta, ZSTD(1)),
    meta_network_name LowCardinality(String),
    meta_consensus_version LowCardinality(String),
    meta_consensus_version_major LowCardinality(String),
    meta_consensus_version_minor LowCardinality(String),
    meta_consensus_version_patch LowCardinality(String),
    meta_consensus_implementation LowCardinality(String),
    meta_labels Map(String, String) CODEC(ZSTD(1))
) Engine = ReplicatedReplacingMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/{database}/{table}', '{replica}', updated_date_time)
PARTITION BY toStartOfMonth(slot_start_date_time)
ORDER BY (slot_start_date_time, unique_key, meta_network_name);

ALTER TABLE default.beacon_p2p_attestation_local ON CLUSTER '{cluster}'
MODIFY COMMENT 'Contains beacon chain P2P "attestation" data',
COMMENT COLUMN unique_key 'Unique key for the row generated from seahash',
COMMENT COLUMN updated_date_time 'When this row was last updated',
COMMENT COLUMN event_date_time 'When the client fetched the beacon block from a beacon node',
COMMENT COLUMN slot 'Slot number in the beacon P2P payload',
COMMENT COLUMN slot_start_date_time 'The wall clock time when the slot started',
COMMENT COLUMN propagation_slot_start_diff 'The difference between the event_date_time and the slot_start_date_time',
COMMENT COLUMN committee_index 'The committee index in the beacon P2P payload',
COMMENT COLUMN attesting_validator_index 'The index of the validator attesting to the event',
COMMENT COLUMN attesting_validator_committee_index 'The committee index of the attesting validator',
COMMENT COLUMN signature 'The signature of the event in the beacon P2P payload',
COMMENT COLUMN aggregation_bits 'The aggregation bits of the event in the beacon P2P payload',
COMMENT COLUMN beacon_block_root 'The beacon block root hash in the beacon P2P payload',
COMMENT COLUMN epoch 'The epoch number in the beacon P2P payload',
COMMENT COLUMN epoch_start_date_time 'The wall clock time when the epoch started',
COMMENT COLUMN source_epoch 'The source epoch number in the beacon P2P payload',
COMMENT COLUMN source_epoch_start_date_time 'The wall clock time when the source epoch started',
COMMENT COLUMN source_root 'The source beacon block root hash in the beacon P2P payload',
COMMENT COLUMN target_epoch 'The target epoch number in the beacon P2P payload',
COMMENT COLUMN target_epoch_start_date_time 'The wall clock time when the target epoch started',
COMMENT COLUMN target_root 'The target beacon block root hash in the beacon P2P payload',
COMMENT COLUMN attestation_subnet 'The attestation subnet the attestation was gossiped on',
COMMENT COLUMN validated 'Whether the attestation was validated by the client',
COMMENT COLUMN peer_id 'The originating peer ID for the gossiped data',
COMMENT COLUMN peer_latency 'The latency of the peer that gossiped the data',
COMMENT COLUMN peer_version 'Peer client version that gossiped the data',
COMMENT COLUMN peer_version_major 'Peer client major version that gossiped the data',
COMMENT COLUMN peer_version_minor 'Peer client minor version that gossiped the data',
COMMENT COLUMN peer_version_patch 'Peer client patch version that gossiped the data',
COMMENT COLUMN peer_implementation 'Peer client implementation that gossiped the data',
COMMENT COLUMN peer_ip 'IP address of the peer that gossiped the data',
COMMENT COLUMN peer_geo_city 'City of the peer that gossiped the data',
COMMENT COLUMN peer_geo_country 'Country of the peer that gossiped the data',
COMMENT COLUMN peer_geo_country_code 'Country code of the peer that gossiped the data',
COMMENT COLUMN peer_geo_continent_code 'Continent code of the peer that gossiped the data',
COMMENT COLUMN peer_geo_longitude 'Longitude of the peer that gossiped the data',
COMMENT COLUMN peer_geo_latitude 'Latitude of the peer that gossiped the data',
COMMENT COLUMN peer_geo_autonomous_system_number 'Autonomous system number of the peer that gossiped the data',
COMMENT COLUMN peer_geo_autonomous_system_organization 'Autonomous system organization of the peer that gossiped the data',
COMMENT COLUMN meta_client_name 'Name of the client that generated the event',
COMMENT COLUMN meta_client_id 'Unique Session ID of the client that generated the event. This changes every time the client is restarted.',
COMMENT COLUMN meta_client_version 'Version of the client that generated the event',
COMMENT COLUMN meta_client_implementation 'Implementation of the client that generated the event',
COMMENT COLUMN meta_client_os 'Operating system of the client that generated the event',
COMMENT COLUMN meta_client_ip 'IP address of the client that generated the event',
COMMENT COLUMN meta_client_geo_city 'City of the client that generated the event',
COMMENT COLUMN meta_client_geo_country 'Country of the client that generated the event',
COMMENT COLUMN meta_client_geo_country_code 'Country code of the client that generated the event',
COMMENT COLUMN meta_client_geo_continent_code 'Continent code of the client that generated the event',
COMMENT COLUMN meta_client_geo_longitude 'Longitude of the client that generated the event',
COMMENT COLUMN meta_client_geo_latitude 'Latitude of the client that generated the event',
COMMENT COLUMN meta_client_geo_autonomous_system_number 'Autonomous system number of the client that generated the event',
COMMENT COLUMN meta_client_geo_autonomous_system_organization 'Autonomous system organization of the client that generated the event',
COMMENT COLUMN meta_network_id 'Ethereum network ID',
COMMENT COLUMN meta_network_name 'Ethereum network name',
COMMENT COLUMN meta_consensus_version 'Ethereum consensus client version that generated the event',
COMMENT COLUMN meta_consensus_version_major 'Ethereum consensus client major version that generated the event',
COMMENT COLUMN meta_consensus_version_minor 'Ethereum consensus client minor version that generated the event',
COMMENT COLUMN meta_consensus_version_patch 'Ethereum consensus client patch version that generated the event',
COMMENT COLUMN meta_consensus_implementation 'Ethereum consensus client implementation that generated the event',
COMMENT COLUMN meta_labels 'Labels associated with the event';

CREATE TABLE beacon_p2p_attestation on cluster '{cluster}' AS beacon_p2p_attestation_local
ENGINE = Distributed('{cluster}', default, beacon_p2p_attestation_local, rand());
