ALTER TABLE mempool_transaction_local on cluster '{cluster}'
    DROP COLUMN gas_tip_cap,
    DROP COLUMN gas_fee_cap,
    DROP COLUMN blob_gas,
    DROP COLUMN blob_gas_fee_cap,
    DROP COLUMN blob_hashes,
    DROP COLUMN blob_sidecars_size,
    DROP COLUMN blob_sidecars_empty_size;

ALTER TABLE mempool_transaction on cluster '{cluster}'
    DROP COLUMN gas_tip_cap,
    DROP COLUMN gas_fee_cap,
    DROP COLUMN blob_gas,
    DROP COLUMN blob_gas_fee_cap,
    DROP COLUMN blob_hashes,
    DROP COLUMN blob_sidecars_size,
    DROP COLUMN blob_sidecars_empty_size;

ALTER TABLE canonical_beacon_block_execution_transaction_local on cluster '{cluster}'
    DROP COLUMN gas_tip_cap,
    DROP COLUMN gas_fee_cap,
    DROP COLUMN blob_gas,
    DROP COLUMN blob_gas_fee_cap,
    DROP COLUMN blob_hashes,
    DROP COLUMN blob_sidecars_size,
    DROP COLUMN blob_sidecars_empty_size;

ALTER TABLE canonical_beacon_block_execution_transaction on cluster '{cluster}'
    DROP COLUMN gas_tip_cap,
    DROP COLUMN gas_fee_cap,
    DROP COLUMN blob_gas,
    DROP COLUMN blob_gas_fee_cap,
    DROP COLUMN blob_hashes,
    DROP COLUMN blob_sidecars_size,
    DROP COLUMN blob_sidecars_empty_size;

ALTER TABLE canonical_beacon_blob_sidecar_local on cluster '{cluster}'
    DROP COLUMN blob_empty_size;

ALTER TABLE canonical_beacon_blob_sidecar on cluster '{cluster}'
    DROP COLUMN blob_empty_size;

ALTER TABLE block_native_mempool_transaction_local on cluster '{cluster}'
COMMENT COLUMN unique_key '',
COMMENT COLUMN updated_date_time '',
COMMENT COLUMN detecttime '',
COMMENT COLUMN hash '',
COMMENT COLUMN status '',
COMMENT COLUMN region '',
COMMENT COLUMN reorg '',
COMMENT COLUMN replace '',
COMMENT COLUMN curblocknumber '',
COMMENT COLUMN failurereason '',
COMMENT COLUMN blockspending '',
COMMENT COLUMN timepending '',
COMMENT COLUMN nonce '',
COMMENT COLUMN gas '',
COMMENT COLUMN gasprice '',
COMMENT COLUMN value '',
COMMENT COLUMN toaddress '',
COMMENT COLUMN fromaddress '',
COMMENT COLUMN datasize '',
COMMENT COLUMN data4bytes '',
COMMENT COLUMN network '',
COMMENT COLUMN type '',
COMMENT COLUMN maxpriorityfeepergas '',
COMMENT COLUMN maxfeepergas '',
COMMENT COLUMN basefeepergas '',
COMMENT COLUMN dropreason '',
COMMENT COLUMN rejectionreason '',
COMMENT COLUMN stuck '',
COMMENT COLUMN gasused '';

ALTER TABLE block_native_mempool_transaction on cluster '{cluster}'
COMMENT COLUMN unique_key '',
COMMENT COLUMN updated_date_time '',
COMMENT COLUMN detecttime '',
COMMENT COLUMN hash '',
COMMENT COLUMN status '',
COMMENT COLUMN region '',
COMMENT COLUMN reorg '',
COMMENT COLUMN replace '',
COMMENT COLUMN curblocknumber '',
COMMENT COLUMN failurereason '',
COMMENT COLUMN blockspending '',
COMMENT COLUMN timepending '',
COMMENT COLUMN nonce '',
COMMENT COLUMN gas '',
COMMENT COLUMN gasprice '',
COMMENT COLUMN value '',
COMMENT COLUMN toaddress '',
COMMENT COLUMN fromaddress '',
COMMENT COLUMN datasize '',
COMMENT COLUMN data4bytes '',
COMMENT COLUMN network '',
COMMENT COLUMN type '',
COMMENT COLUMN maxpriorityfeepergas '',
COMMENT COLUMN maxfeepergas '',
COMMENT COLUMN basefeepergas '',
COMMENT COLUMN dropreason '',
COMMENT COLUMN rejectionreason '',
COMMENT COLUMN stuck '',
COMMENT COLUMN gasused '';

ALTER TABLE canonical_beacon_proposer_duty_local on cluster '{cluster}'
COMMENT COLUMN unique_key '',
COMMENT COLUMN updated_date_time '',
COMMENT COLUMN event_date_time '',
COMMENT COLUMN slot '',
COMMENT COLUMN slot_start_date_time '',
COMMENT COLUMN epoch '',
COMMENT COLUMN epoch_start_date_time '',
COMMENT COLUMN proposer_validator_index '',
COMMENT COLUMN proposer_pubkey '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_client_id '',
COMMENT COLUMN meta_client_version '',
COMMENT COLUMN meta_client_implementation '',
COMMENT COLUMN meta_client_os '',
COMMENT COLUMN meta_client_ip '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_country '',
COMMENT COLUMN meta_client_geo_country_code '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_client_geo_autonomous_system_number '',
COMMENT COLUMN meta_client_geo_autonomous_system_organization '',
COMMENT COLUMN meta_network_id '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_consensus_version '',
COMMENT COLUMN meta_consensus_version_major '',
COMMENT COLUMN meta_consensus_version_minor '',
COMMENT COLUMN meta_consensus_version_patch '',
COMMENT COLUMN meta_consensus_implementation '',
COMMENT COLUMN meta_labels '';

ALTER TABLE canonical_beacon_proposer_duty on cluster '{cluster}'
COMMENT COLUMN unique_key '',
COMMENT COLUMN updated_date_time '',
COMMENT COLUMN event_date_time '',
COMMENT COLUMN slot '',
COMMENT COLUMN slot_start_date_time '',
COMMENT COLUMN epoch '',
COMMENT COLUMN epoch_start_date_time '',
COMMENT COLUMN proposer_validator_index '',
COMMENT COLUMN proposer_pubkey '',
COMMENT COLUMN meta_client_name '',
COMMENT COLUMN meta_client_id '',
COMMENT COLUMN meta_client_version '',
COMMENT COLUMN meta_client_implementation '',
COMMENT COLUMN meta_client_os '',
COMMENT COLUMN meta_client_ip '',
COMMENT COLUMN meta_client_geo_city '',
COMMENT COLUMN meta_client_geo_country '',
COMMENT COLUMN meta_client_geo_country_code '',
COMMENT COLUMN meta_client_geo_continent_code '',
COMMENT COLUMN meta_client_geo_longitude '',
COMMENT COLUMN meta_client_geo_latitude '',
COMMENT COLUMN meta_client_geo_autonomous_system_number '',
COMMENT COLUMN meta_client_geo_autonomous_system_organization '',
COMMENT COLUMN meta_network_id '',
COMMENT COLUMN meta_network_name '',
COMMENT COLUMN meta_consensus_version '',
COMMENT COLUMN meta_consensus_version_major '',
COMMENT COLUMN meta_consensus_version_minor '',
COMMENT COLUMN meta_consensus_version_patch '',
COMMENT COLUMN meta_consensus_implementation '',
COMMENT COLUMN meta_labels '';
