CREATE TABLE default.canonical_execution_trie_depth_local ON CLUSTER '{cluster}' (
    `updated_date_time` DateTime COMMENT 'Timestamp when the record was last updated' CODEC(DoubleDelta, ZSTD(1)),
    `block_number` UInt64 COMMENT 'The block number' CODEC(DoubleDelta, ZSTD(1)),
    `state_root` FixedString(66) COMMENT 'State root hash of the execution layer at this block' Codec(ZSTD(1)),
    `total_account_written_nodes` UInt64 COMMENT 'The total number of trie nodes written at all depths of account tries' Codec(DoubleDelta, ZSTD(1)),
    `total_account_deleted_nodes` UInt64 COMMENT 'The total number of trie nodes deleted at all depths of account tries' Codec(DoubleDelta, ZSTD(1)),
    `total_storage_written_nodes` UInt64 COMMENT 'The total number of trie nodes written at all depths of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `total_storage_deleted_nodes` UInt64 COMMENT 'The total number of trie nodes deleted at all depths of storage tries' Codec(DoubleDelta, ZSTD(1)),
    -- Account trie node counts (written)
    `account_written_depth_0` UInt64 COMMENT 'The number of nodes written at depth 0 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_1` UInt64 COMMENT 'The number of nodes written at depth 1 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_2` UInt64 COMMENT 'The number of nodes written at depth 2 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_3` UInt64 COMMENT 'The number of nodes written at depth 3 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_4` UInt64 COMMENT 'The number of nodes written at depth 4 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_5` UInt64 COMMENT 'The number of nodes written at depth 5 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_6` UInt64 COMMENT 'The number of nodes written at depth 6 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_7` UInt64 COMMENT 'The number of nodes written at depth 7 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_8` UInt64 COMMENT 'The number of nodes written at depth 8 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_9` UInt64 COMMENT 'The number of nodes written at depth 9 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_10` UInt64 COMMENT 'The number of nodes written at depth 10 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_11` UInt64 COMMENT 'The number of nodes written at depth 11 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_12` UInt64 COMMENT 'The number of nodes written at depth 12 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_13` UInt64 COMMENT 'The number of nodes written at depth 13 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_14` UInt64 COMMENT 'The number of nodes written at depth 14 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_15` UInt64 COMMENT 'The number of nodes written at depth 15 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_16` UInt64 COMMENT 'The number of nodes written at depth 16 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_17` UInt64 COMMENT 'The number of nodes written at depth 17 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_18` UInt64 COMMENT 'The number of nodes written at depth 18 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_19` UInt64 COMMENT 'The number of nodes written at depth 19 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_20` UInt64 COMMENT 'The number of nodes written at depth 20 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_21` UInt64 COMMENT 'The number of nodes written at depth 21 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_22` UInt64 COMMENT 'The number of nodes written at depth 22 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_23` UInt64 COMMENT 'The number of nodes written at depth 23 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_24` UInt64 COMMENT 'The number of nodes written at depth 24 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_25` UInt64 COMMENT 'The number of nodes written at depth 25 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_26` UInt64 COMMENT 'The number of nodes written at depth 26 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_27` UInt64 COMMENT 'The number of nodes written at depth 27 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_28` UInt64 COMMENT 'The number of nodes written at depth 28 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_29` UInt64 COMMENT 'The number of nodes written at depth 29 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_30` UInt64 COMMENT 'The number of nodes written at depth 30 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_31` UInt64 COMMENT 'The number of nodes written at depth 31 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_32` UInt64 COMMENT 'The number of nodes written at depth 32 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_33` UInt64 COMMENT 'The number of nodes written at depth 33 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_34` UInt64 COMMENT 'The number of nodes written at depth 34 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_35` UInt64 COMMENT 'The number of nodes written at depth 35 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_36` UInt64 COMMENT 'The number of nodes written at depth 36 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_37` UInt64 COMMENT 'The number of nodes written at depth 37 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_38` UInt64 COMMENT 'The number of nodes written at depth 38 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_39` UInt64 COMMENT 'The number of nodes written at depth 39 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_40` UInt64 COMMENT 'The number of nodes written at depth 40 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_41` UInt64 COMMENT 'The number of nodes written at depth 41 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_42` UInt64 COMMENT 'The number of nodes written at depth 42 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_43` UInt64 COMMENT 'The number of nodes written at depth 43 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_44` UInt64 COMMENT 'The number of nodes written at depth 44 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_45` UInt64 COMMENT 'The number of nodes written at depth 45 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_46` UInt64 COMMENT 'The number of nodes written at depth 46 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_47` UInt64 COMMENT 'The number of nodes written at depth 47 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_48` UInt64 COMMENT 'The number of nodes written at depth 48 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_49` UInt64 COMMENT 'The number of nodes written at depth 49 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_50` UInt64 COMMENT 'The number of nodes written at depth 50 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_51` UInt64 COMMENT 'The number of nodes written at depth 51 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_52` UInt64 COMMENT 'The number of nodes written at depth 52 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_53` UInt64 COMMENT 'The number of nodes written at depth 53 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_54` UInt64 COMMENT 'The number of nodes written at depth 54 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_55` UInt64 COMMENT 'The number of nodes written at depth 55 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_56` UInt64 COMMENT 'The number of nodes written at depth 56 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_57` UInt64 COMMENT 'The number of nodes written at depth 57 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_58` UInt64 COMMENT 'The number of nodes written at depth 58 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_59` UInt64 COMMENT 'The number of nodes written at depth 59 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_60` UInt64 COMMENT 'The number of nodes written at depth 60 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_61` UInt64 COMMENT 'The number of nodes written at depth 61 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_62` UInt64 COMMENT 'The number of nodes written at depth 62 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_63` UInt64 COMMENT 'The number of nodes written at depth 63 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_written_depth_64` UInt64 COMMENT 'The number of nodes written at depth 64 of account trie' Codec(DoubleDelta, ZSTD(1)),
    -- Storage tries node count (written)
    `storage_written_depth_0` UInt64 COMMENT 'The number of nodes written at depth 0 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_1` UInt64 COMMENT 'The number of nodes written at depth 1 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_2` UInt64 COMMENT 'The number of nodes written at depth 2 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_3` UInt64 COMMENT 'The number of nodes written at depth 3 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_4` UInt64 COMMENT 'The number of nodes written at depth 4 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_5` UInt64 COMMENT 'The number of nodes written at depth 5 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_6` UInt64 COMMENT 'The number of nodes written at depth 6 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_7` UInt64 COMMENT 'The number of nodes written at depth 7 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_8` UInt64 COMMENT 'The number of nodes written at depth 8 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_9` UInt64 COMMENT 'The number of nodes written at depth 9 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_10` UInt64 COMMENT 'The number of nodes written at depth 10 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_11` UInt64 COMMENT 'The number of nodes written at depth 11 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_12` UInt64 COMMENT 'The number of nodes written at depth 12 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_13` UInt64 COMMENT 'The number of nodes written at depth 13 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_14` UInt64 COMMENT 'The number of nodes written at depth 14 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_15` UInt64 COMMENT 'The number of nodes written at depth 15 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_16` UInt64 COMMENT 'The number of nodes written at depth 16 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_17` UInt64 COMMENT 'The number of nodes written at depth 17 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_18` UInt64 COMMENT 'The number of nodes written at depth 18 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_19` UInt64 COMMENT 'The number of nodes written at depth 19 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_20` UInt64 COMMENT 'The number of nodes written at depth 20 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_21` UInt64 COMMENT 'The number of nodes written at depth 21 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_22` UInt64 COMMENT 'The number of nodes written at depth 22 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_23` UInt64 COMMENT 'The number of nodes written at depth 23 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_24` UInt64 COMMENT 'The number of nodes written at depth 24 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_25` UInt64 COMMENT 'The number of nodes written at depth 25 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_26` UInt64 COMMENT 'The number of nodes written at depth 26 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_27` UInt64 COMMENT 'The number of nodes written at depth 27 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_28` UInt64 COMMENT 'The number of nodes written at depth 28 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_29` UInt64 COMMENT 'The number of nodes written at depth 29 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_30` UInt64 COMMENT 'The number of nodes written at depth 30 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_31` UInt64 COMMENT 'The number of nodes written at depth 31 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_32` UInt64 COMMENT 'The number of nodes written at depth 32 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_33` UInt64 COMMENT 'The number of nodes written at depth 33 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_34` UInt64 COMMENT 'The number of nodes written at depth 34 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_35` UInt64 COMMENT 'The number of nodes written at depth 35 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_36` UInt64 COMMENT 'The number of nodes written at depth 36 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_37` UInt64 COMMENT 'The number of nodes written at depth 37 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_38` UInt64 COMMENT 'The number of nodes written at depth 38 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_39` UInt64 COMMENT 'The number of nodes written at depth 39 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_40` UInt64 COMMENT 'The number of nodes written at depth 40 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_41` UInt64 COMMENT 'The number of nodes written at depth 41 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_42` UInt64 COMMENT 'The number of nodes written at depth 42 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_43` UInt64 COMMENT 'The number of nodes written at depth 43 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_44` UInt64 COMMENT 'The number of nodes written at depth 44 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_45` UInt64 COMMENT 'The number of nodes written at depth 45 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_46` UInt64 COMMENT 'The number of nodes written at depth 46 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_47` UInt64 COMMENT 'The number of nodes written at depth 47 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_48` UInt64 COMMENT 'The number of nodes written at depth 48 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_49` UInt64 COMMENT 'The number of nodes written at depth 49 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_50` UInt64 COMMENT 'The number of nodes written at depth 50 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_51` UInt64 COMMENT 'The number of nodes written at depth 51 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_52` UInt64 COMMENT 'The number of nodes written at depth 52 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_53` UInt64 COMMENT 'The number of nodes written at depth 53 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_54` UInt64 COMMENT 'The number of nodes written at depth 54 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_55` UInt64 COMMENT 'The number of nodes written at depth 55 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_56` UInt64 COMMENT 'The number of nodes written at depth 56 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_57` UInt64 COMMENT 'The number of nodes written at depth 57 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_58` UInt64 COMMENT 'The number of nodes written at depth 58 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_59` UInt64 COMMENT 'The number of nodes written at depth 59 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_60` UInt64 COMMENT 'The number of nodes written at depth 60 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_61` UInt64 COMMENT 'The number of nodes written at depth 61 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_62` UInt64 COMMENT 'The number of nodes written at depth 62 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_63` UInt64 COMMENT 'The number of nodes written at depth 63 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    `storage_written_depth_64` UInt64 COMMENT 'The number of nodes written at depth 64 of storage tries' Codec(DoubleDelta, ZSTD(1)),
    -- Account trie node counts (deleted)
    `account_deleted_depth_0` UInt64 COMMENT 'The number of nodes deleted at depth 0 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_1` UInt64 COMMENT 'The number of nodes deleted at depth 1 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_2` UInt64 COMMENT 'The number of nodes deleted at depth 2 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_3` UInt64 COMMENT 'The number of nodes deleted at depth 3 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_4` UInt64 COMMENT 'The number of nodes deleted at depth 4 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_5` UInt64 COMMENT 'The number of nodes deleted at depth 5 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_6` UInt64 COMMENT 'The number of nodes deleted at depth 6 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_7` UInt64 COMMENT 'The number of nodes deleted at depth 7 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_8` UInt64 COMMENT 'The number of nodes deleted at depth 8 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_9` UInt64 COMMENT 'The number of nodes deleted at depth 9 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_10` UInt64 COMMENT 'The number of nodes deleted at depth 10 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_11` UInt64 COMMENT 'The number of nodes deleted at depth 11 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_12` UInt64 COMMENT 'The number of nodes deleted at depth 12 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_13` UInt64 COMMENT 'The number of nodes deleted at depth 13 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_14` UInt64 COMMENT 'The number of nodes deleted at depth 14 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_15` UInt64 COMMENT 'The number of nodes deleted at depth 15 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_16` UInt64 COMMENT 'The number of nodes deleted at depth 16 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_17` UInt64 COMMENT 'The number of nodes deleted at depth 17 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_18` UInt64 COMMENT 'The number of nodes deleted at depth 18 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_19` UInt64 COMMENT 'The number of nodes deleted at depth 19 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_20` UInt64 COMMENT 'The number of nodes deleted at depth 20 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_21` UInt64 COMMENT 'The number of nodes deleted at depth 21 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_22` UInt64 COMMENT 'The number of nodes deleted at depth 22 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_23` UInt64 COMMENT 'The number of nodes deleted at depth 23 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_24` UInt64 COMMENT 'The number of nodes deleted at depth 24 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_25` UInt64 COMMENT 'The number of nodes deleted at depth 25 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_26` UInt64 COMMENT 'The number of nodes deleted at depth 26 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_27` UInt64 COMMENT 'The number of nodes deleted at depth 27 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_28` UInt64 COMMENT 'The number of nodes deleted at depth 28 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_29` UInt64 COMMENT 'The number of nodes deleted at depth 29 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_30` UInt64 COMMENT 'The number of nodes deleted at depth 30 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_31` UInt64 COMMENT 'The number of nodes deleted at depth 31 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_32` UInt64 COMMENT 'The number of nodes deleted at depth 32 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_33` UInt64 COMMENT 'The number of nodes deleted at depth 33 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_34` UInt64 COMMENT 'The number of nodes deleted at depth 34 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_35` UInt64 COMMENT 'The number of nodes deleted at depth 35 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_36` UInt64 COMMENT 'The number of nodes deleted at depth 36 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_37` UInt64 COMMENT 'The number of nodes deleted at depth 37 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_38` UInt64 COMMENT 'The number of nodes deleted at depth 38 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_39` UInt64 COMMENT 'The number of nodes deleted at depth 39 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_40` UInt64 COMMENT 'The number of nodes deleted at depth 40 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_41` UInt64 COMMENT 'The number of nodes deleted at depth 41 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_42` UInt64 COMMENT 'The number of nodes deleted at depth 42 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_43` UInt64 COMMENT 'The number of nodes deleted at depth 43 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_44` UInt64 COMMENT 'The number of nodes deleted at depth 44 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_45` UInt64 COMMENT 'The number of nodes deleted at depth 45 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_46` UInt64 COMMENT 'The number of nodes deleted at depth 46 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_47` UInt64 COMMENT 'The number of nodes deleted at depth 47 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_48` UInt64 COMMENT 'The number of nodes deleted at depth 48 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_49` UInt64 COMMENT 'The number of nodes deleted at depth 49 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_50` UInt64 COMMENT 'The number of nodes deleted at depth 50 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_51` UInt64 COMMENT 'The number of nodes deleted at depth 51 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_52` UInt64 COMMENT 'The number of nodes deleted at depth 52 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_53` UInt64 COMMENT 'The number of nodes deleted at depth 53 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_54` UInt64 COMMENT 'The number of nodes deleted at depth 54 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_55` UInt64 COMMENT 'The number of nodes deleted at depth 55 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_56` UInt64 COMMENT 'The number of nodes deleted at depth 56 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_57` UInt64 COMMENT 'The number of nodes deleted at depth 57 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_58` UInt64 COMMENT 'The number of nodes deleted at depth 58 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_59` UInt64 COMMENT 'The number of nodes deleted at depth 59 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_60` UInt64 COMMENT 'The number of nodes deleted at depth 60 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_61` UInt64 COMMENT 'The number of nodes deleted at depth 61 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_62` UInt64 COMMENT 'The number of nodes deleted at depth 62 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_63` UInt64 COMMENT 'The number of nodes deleted at depth 63 of account trie' Codec(DoubleDelta, ZSTD(1)),
    `account_deleted_depth_64` UInt64 COMMENT 'The number of nodes deleted at depth 64 of account trie' Codec(DoubleDelta, ZSTD(1)),
    -- Storage tries node counts (deleted)
    `storage_deleted_depth_0` UInt64 COMMENT 'The number of nodes deleted at depth 0 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_1` UInt64 COMMENT 'The number of nodes deleted at depth 1 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_2` UInt64 COMMENT 'The number of nodes deleted at depth 2 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_3` UInt64 COMMENT 'The number of nodes deleted at depth 3 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_4` UInt64 COMMENT 'The number of nodes deleted at depth 4 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_5` UInt64 COMMENT 'The number of nodes deleted at depth 5 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_6` UInt64 COMMENT 'The number of nodes deleted at depth 6 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_7` UInt64 COMMENT 'The number of nodes deleted at depth 7 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_8` UInt64 COMMENT 'The number of nodes deleted at depth 8 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_9` UInt64 COMMENT 'The number of nodes deleted at depth 9 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_10` UInt64 COMMENT 'The number of nodes deleted at depth 10 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_11` UInt64 COMMENT 'The number of nodes deleted at depth 11 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_12` UInt64 COMMENT 'The number of nodes deleted at depth 12 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_13` UInt64 COMMENT 'The number of nodes deleted at depth 13 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_14` UInt64 COMMENT 'The number of nodes deleted at depth 14 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_15` UInt64 COMMENT 'The number of nodes deleted at depth 15 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_16` UInt64 COMMENT 'The number of nodes deleted at depth 16 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_17` UInt64 COMMENT 'The number of nodes deleted at depth 17 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_18` UInt64 COMMENT 'The number of nodes deleted at depth 18 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_19` UInt64 COMMENT 'The number of nodes deleted at depth 19 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_20` UInt64 COMMENT 'The number of nodes deleted at depth 20 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_21` UInt64 COMMENT 'The number of nodes deleted at depth 21 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_22` UInt64 COMMENT 'The number of nodes deleted at depth 22 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_23` UInt64 COMMENT 'The number of nodes deleted at depth 23 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_24` UInt64 COMMENT 'The number of nodes deleted at depth 24 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_25` UInt64 COMMENT 'The number of nodes deleted at depth 25 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_26` UInt64 COMMENT 'The number of nodes deleted at depth 26 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_27` UInt64 COMMENT 'The number of nodes deleted at depth 27 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_28` UInt64 COMMENT 'The number of nodes deleted at depth 28 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_29` UInt64 COMMENT 'The number of nodes deleted at depth 29 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_30` UInt64 COMMENT 'The number of nodes deleted at depth 30 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_31` UInt64 COMMENT 'The number of nodes deleted at depth 31 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_32` UInt64 COMMENT 'The number of nodes deleted at depth 32 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_33` UInt64 COMMENT 'The number of nodes deleted at depth 33 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_34` UInt64 COMMENT 'The number of nodes deleted at depth 34 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_35` UInt64 COMMENT 'The number of nodes deleted at depth 35 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_36` UInt64 COMMENT 'The number of nodes deleted at depth 36 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_37` UInt64 COMMENT 'The number of nodes deleted at depth 37 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_38` UInt64 COMMENT 'The number of nodes deleted at depth 38 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_39` UInt64 COMMENT 'The number of nodes deleted at depth 39 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_40` UInt64 COMMENT 'The number of nodes deleted at depth 40 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_41` UInt64 COMMENT 'The number of nodes deleted at depth 41 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_42` UInt64 COMMENT 'The number of nodes deleted at depth 42 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_43` UInt64 COMMENT 'The number of nodes deleted at depth 43 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_44` UInt64 COMMENT 'The number of nodes deleted at depth 44 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_45` UInt64 COMMENT 'The number of nodes deleted at depth 45 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_46` UInt64 COMMENT 'The number of nodes deleted at depth 46 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_47` UInt64 COMMENT 'The number of nodes deleted at depth 47 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_48` UInt64 COMMENT 'The number of nodes deleted at depth 48 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_49` UInt64 COMMENT 'The number of nodes deleted at depth 49 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_50` UInt64 COMMENT 'The number of nodes deleted at depth 50 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_51` UInt64 COMMENT 'The number of nodes deleted at depth 51 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_52` UInt64 COMMENT 'The number of nodes deleted at depth 52 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_53` UInt64 COMMENT 'The number of nodes deleted at depth 53 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_54` UInt64 COMMENT 'The number of nodes deleted at depth 54 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_55` UInt64 COMMENT 'The number of nodes deleted at depth 55 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_56` UInt64 COMMENT 'The number of nodes deleted at depth 56 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_57` UInt64 COMMENT 'The number of nodes deleted at depth 57 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_58` UInt64 COMMENT 'The number of nodes deleted at depth 58 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_59` UInt64 COMMENT 'The number of nodes deleted at depth 59 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_60` UInt64 COMMENT 'The number of nodes deleted at depth 60 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_61` UInt64 COMMENT 'The number of nodes deleted at depth 61 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_62` UInt64 COMMENT 'The number of nodes deleted at depth 62 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_63` UInt64 COMMENT 'The number of nodes deleted at depth 63 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    `storage_deleted_depth_64` UInt64 COMMENT 'The number of nodes deleted at depth 64 of storage trie' Codec(DoubleDelta, ZSTD(1)),
    -- Standard metadata fields
    `meta_client_name` LowCardinality(String) COMMENT 'Name of the client that generated the event',
    `meta_client_id` String COMMENT 'Unique Session ID of the client that generated the event. This changes every time the client is restarted.' Codec(ZSTD(1)),
    `meta_client_version` LowCardinality(String) COMMENT 'Version of the client that generated the event',
    `meta_client_implementation` LowCardinality(String) COMMENT 'Implementation of the client that generated the event',
    `meta_client_os` LowCardinality(String) COMMENT 'Operating system of the client that generated the event',
    `meta_client_ip` Nullable(IPv6) COMMENT 'IP address of the client that generated the event' Codec(ZSTD(1)),
    `meta_client_geo_city` LowCardinality(String) COMMENT 'City of the client that generated the event' Codec(ZSTD(1)),
    `meta_client_geo_country` LowCardinality(String) COMMENT 'Country of the client that generated the event' Codec(ZSTD(1)),
    `meta_client_geo_country_code` LowCardinality(String) COMMENT 'Country code of the client that generated the event' Codec(ZSTD(1)),
    `meta_client_geo_continent_code` LowCardinality(String) COMMENT 'Continent code of the client that generated the event' Codec(ZSTD(1)),
    `meta_client_geo_longitude` Nullable(Float64) COMMENT 'Longitude of the client that generated the event' Codec(ZSTD(1)),
    `meta_client_geo_latitude` Nullable(Float64) COMMENT 'Latitude of the client that generated the event' Codec(ZSTD(1)),
    `meta_client_geo_autonomous_system_number` Nullable(UInt32) COMMENT 'Autonomous system number of the client that generated the event' Codec(ZSTD(1)),
    `meta_client_geo_autonomous_system_organization` Nullable(String) COMMENT 'Autonomous system organization of the client that generated the event' Codec(ZSTD(1)),
    `meta_network_id` Int32 COMMENT 'Ethereum network ID' Codec(DoubleDelta, ZSTD(1)),
    `meta_network_name` LowCardinality(String) COMMENT 'Ethereum network name',
    `meta_execution_version` LowCardinality(String) COMMENT 'Execution client version that generated the event',
    `meta_execution_version_major` LowCardinality(String) COMMENT 'Execution client major version that generated the event',
    `meta_execution_version_minor` LowCardinality(String) COMMENT 'Execution client minor version that generated the event',
    `meta_execution_version_patch` LowCardinality(String) COMMENT 'Execution client patch version that generated the event',
    `meta_execution_implementation` LowCardinality(String) COMMENT 'Execution client implementation that generated the event',
    `meta_labels` Map(String, String) COMMENT 'Labels associated with the event' Codec(ZSTD(1))
) ENGINE = ReplicatedReplacingMergeTree(
    '/clickhouse/{installation}/{cluster}/{database}/tables/{table}/{shard}',
    '{replica}',
    updated_date_time
) PARTITION BY intDiv(block_number, 5000000)
ORDER BY (
        block_number,
        meta_network_name,
    ) COMMENT 'Contains canonical execution block data.';
CREATE TABLE default.canonical_execution_trie_depth ON CLUSTER '{cluster}' AS default.canonical_execution_trie_depth_local ENGINE = Distributed(
    '{cluster}',
    default,
    canonical_execution_trie_depth_local,
    cityHash64(
        block_number,
        meta_network_name
    )
);