package flattener

// TableName is a typed ClickHouse target table identifier for flatteners.
type TableName string

func (t TableName) String() string {
	return string(t)
}

const (
	TableBeaconApiEthV1BeaconBlob                       TableName = "beacon_api_eth_v1_beacon_blob"
	TableBeaconApiEthV1BeaconCommittee                  TableName = "beacon_api_eth_v1_beacon_committee"
	TableBeaconApiEthV1EventsAttestation                TableName = "beacon_api_eth_v1_events_attestation"
	TableBeaconApiEthV1EventsBlobSidecar                TableName = "beacon_api_eth_v1_events_blob_sidecar"
	TableBeaconApiEthV1EventsBlock                      TableName = "beacon_api_eth_v1_events_block"
	TableBeaconApiEthV1EventsBlockGossip                TableName = "beacon_api_eth_v1_events_block_gossip"
	TableBeaconApiEthV1EventsChainReorg                 TableName = "beacon_api_eth_v1_events_chain_reorg"
	TableBeaconApiEthV1EventsContributionAndProof       TableName = "beacon_api_eth_v1_events_contribution_and_proof"
	TableBeaconApiEthV1EventsDataColumnSidecar          TableName = "beacon_api_eth_v1_events_data_column_sidecar"
	TableBeaconApiEthV1EventsFinalizedCheckpoint        TableName = "beacon_api_eth_v1_events_finalized_checkpoint"
	TableBeaconApiEthV1EventsHead                       TableName = "beacon_api_eth_v1_events_head"
	TableBeaconApiEthV1EventsVoluntaryExit              TableName = "beacon_api_eth_v1_events_voluntary_exit"
	TableBeaconApiEthV1ProposerDuty                     TableName = "beacon_api_eth_v1_proposer_duty"
	TableBeaconApiEthV1ValidatorAttestationData         TableName = "beacon_api_eth_v1_validator_attestation_data"
	TableBeaconApiEthV2BeaconBlock                      TableName = "beacon_api_eth_v2_beacon_block"
	TableBeaconApiEthV3ValidatorBlock                   TableName = "beacon_api_eth_v3_validator_block"
	TableCanonicalBeaconBlobSidecar                     TableName = "canonical_beacon_blob_sidecar"
	TableCanonicalBeaconBlock                           TableName = "canonical_beacon_block"
	TableCanonicalBeaconBlockAttesterSlashing           TableName = "canonical_beacon_block_attester_slashing"
	TableCanonicalBeaconBlockBlsToExecutionChange       TableName = "canonical_beacon_block_bls_to_execution_change"
	TableCanonicalBeaconBlockDeposit                    TableName = "canonical_beacon_block_deposit"
	TableCanonicalBeaconBlockExecutionTransaction       TableName = "canonical_beacon_block_execution_transaction"
	TableCanonicalBeaconBlockProposerSlashing           TableName = "canonical_beacon_block_proposer_slashing"
	TableCanonicalBeaconBlockSyncAggregate              TableName = "canonical_beacon_block_sync_aggregate"
	TableCanonicalBeaconBlockVoluntaryExit              TableName = "canonical_beacon_block_voluntary_exit"
	TableCanonicalBeaconBlockWithdrawal                 TableName = "canonical_beacon_block_withdrawal"
	TableCanonicalBeaconCommittee                       TableName = "canonical_beacon_committee"
	TableCanonicalBeaconElaboratedAttestation           TableName = "canonical_beacon_elaborated_attestation"
	TableCanonicalBeaconProposerDuty                    TableName = "canonical_beacon_proposer_duty"
	TableCanonicalBeaconSyncCommittee                   TableName = "canonical_beacon_sync_committee"
	TableCanonicalBeaconValidators                      TableName = "canonical_beacon_validators"
	TableCanonicalBeaconValidatorsPubkeys               TableName = "canonical_beacon_validators_pubkeys"
	TableCanonicalBeaconValidatorsWithdrawalCredentials TableName = "canonical_beacon_validators_withdrawal_credentials"
	TableConsensusEngineApiGetBlobs                     TableName = "consensus_engine_api_get_blobs"
	TableConsensusEngineApiNewPayload                   TableName = "consensus_engine_api_new_payload"
	TableExecutionBlockMetrics                          TableName = "execution_block_metrics"
	TableExecutionEngineGetBlobs                        TableName = "execution_engine_get_blobs"
	TableExecutionEngineNewPayload                      TableName = "execution_engine_new_payload"
	TableExecutionStateSize                             TableName = "execution_state_size"
	TableLibp2pAddPeer                                  TableName = "libp2p_add_peer"
	TableLibp2pConnected                                TableName = "libp2p_connected"
	TableLibp2pDeliverMessage                           TableName = "libp2p_deliver_message"
	TableLibp2pDisconnected                             TableName = "libp2p_disconnected"
	TableLibp2pDropRpc                                  TableName = "libp2p_drop_rpc"
	TableLibp2pDuplicateMessage                         TableName = "libp2p_duplicate_message"
	TableLibp2pGossipsubAggregateAndProof               TableName = "libp2p_gossipsub_aggregate_and_proof"
	TableLibp2pGossipsubBeaconAttestation               TableName = "libp2p_gossipsub_beacon_attestation"
	TableLibp2pGossipsubBeaconBlock                     TableName = "libp2p_gossipsub_beacon_block"
	TableLibp2pGossipsubBlobSidecar                     TableName = "libp2p_gossipsub_blob_sidecar"
	TableLibp2pGossipsubDataColumnSidecar               TableName = "libp2p_gossipsub_data_column_sidecar"
	TableLibp2pGraft                                    TableName = "libp2p_graft"
	TableLibp2pHandleMetadata                           TableName = "libp2p_handle_metadata"
	TableLibp2pHandleStatus                             TableName = "libp2p_handle_status"
	TableLibp2pJoin                                     TableName = "libp2p_join"
	TableLibp2pLeave                                    TableName = "libp2p_leave"
	TableLibp2pPeer                                     TableName = "libp2p_peer"
	TableLibp2pPrune                                    TableName = "libp2p_prune"
	TableLibp2pPublishMessage                           TableName = "libp2p_publish_message"
	TableLibp2pRecvRpc                                  TableName = "libp2p_recv_rpc"
	TableLibp2pRejectMessage                            TableName = "libp2p_reject_message"
	TableLibp2pRemovePeer                               TableName = "libp2p_remove_peer"
	TableLibp2pRpcDataColumnCustodyProbe                TableName = "libp2p_rpc_data_column_custody_probe"
	TableLibp2pRpcMetaControlGraft                      TableName = "libp2p_rpc_meta_control_graft"
	TableLibp2pRpcMetaControlIdontwant                  TableName = "libp2p_rpc_meta_control_idontwant"
	TableLibp2pRpcMetaControlIhave                      TableName = "libp2p_rpc_meta_control_ihave"
	TableLibp2pRpcMetaControlIwant                      TableName = "libp2p_rpc_meta_control_iwant"
	TableLibp2pRpcMetaControlPrune                      TableName = "libp2p_rpc_meta_control_prune"
	TableLibp2pRpcMetaMessage                           TableName = "libp2p_rpc_meta_message"
	TableLibp2pRpcMetaSubscription                      TableName = "libp2p_rpc_meta_subscription"
	TableLibp2pSendRpc                                  TableName = "libp2p_send_rpc"
	TableLibp2pSyntheticHeartbeat                       TableName = "libp2p_synthetic_heartbeat"
	TableMempoolTransaction                             TableName = "mempool_transaction"
	TableMevRelayBidTrace                               TableName = "mev_relay_bid_trace"
	TableMevRelayProposerPayloadDelivered               TableName = "mev_relay_proposer_payload_delivered"
	TableMevRelayValidatorRegistration                  TableName = "mev_relay_validator_registration"
	TableNodeRecordConsensus                            TableName = "node_record_consensus"
	TableNodeRecordExecution                            TableName = "node_record_execution"
)
