{
 "title": "Overview",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Events Ingested by Xatu Server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(event) (increase(xatu_server_event_ingester_decorated_events_received_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vector to Kafka",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum by(component_id, component_kind, component_type) (increase(vector_component_received_events_total{component_type=\"kafka\", component_kind=\"sink\"}[5m])) != 0",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Vector Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(vector_component_errors_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vector to Clickhouse",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "sum by(component_id, component_kind, component_type) (increase(vector_component_received_events_total{component_type=\"clickhouse\", component_kind=\"sink\"}[5m])) != 0",
     "legendFormat": "{{component_id}}"
    }
   ]
  },
  {
   "title": "Xatu Queue",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 16 },
   "targets": [
    { "expr": "xatu_processor_items_queued", "legendFormat": "{{processor}}" }
   ]
  },
  {
   "title": "Xatu Failed export",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 16 },
   "targets": [
    {
     "expr": "rate(xatu_processor_items_failed_total[$__interval])",
     "legendFormat": "{{processor}}"
    }
   ]
  }
 ]
}