{
 "title": "Beacon API Events",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network_name",
    "label": "Network",
    "query": "SELECT meta_network_name\nFROM ${table_prefix}beacon_api_eth_v1_events_block\nWHERE\n  slot_start_date_time >= toDateTime(${__from} / 1000)\n  AND slot_start_date_time <= toDateTime(${__to} / 1000)\nGROUP BY meta_network_name "
   },
   {
    "name": "client_name",
    "label": "Sentry",
    "query": "SELECT meta_client_name\nFROM ${table_prefix}beacon_api_eth_v1_events_block\nWHERE\n  slot_start_date_time >= toDateTime(${__from} / 1000)\n  AND slot_start_date_time <= toDateTime(${__to} / 1000)\n  AND meta_network_name IN (${network_name})\nGROUP BY meta_client_name "
   },
   {
    "name": "consensus_implementation",
    "label": "Consensus client",
    "query": "SELECT meta_consensus_implementation\nFROM ${table_prefix}beacon_api_eth_v1_events_block\nWHERE\n  slot_start_date_time >= toDateTime(${__from} / 1000)\n  AND slot_start_date_time <= toDateTime(${__to} / 1000)\n  AND meta_network_name IN (${network_name})\nGROUP BY meta_consensus_implementation "
   },
   {
    "name": "consensus_version",
    "label": "Consensus client version",
    "query": "SELECT meta_consensus_version\nFROM ${table_prefix}beacon_api_eth_v1_events_block\nWHERE\n  slot_start_date_time >= toDateTime(${__from} / 1000)\n  AND slot_start_date_time <= toDateTime(${__to} / 1000)\n  AND meta_network_name IN (${network_name})\n  AND meta_consensus_implementation IN (${consensus_implementation})\nGROUP BY meta_consensus_version "
   },
   {
    "name": "geo_continent_code",
    "label": "Continent",
    "query": "SELECT meta_client_geo_continent_code\nFROM ${table_prefix}beacon_api_eth_v1_events_block\nWHERE\n  slot_start_date_time >= toDateTime(${__from} / 1000)\n  AND slot_start_date_time <= toDateTime(${__to} / 1000)\n  AND meta_network_name IN (${network_name})\nGROUP BY meta_client_geo_continent_code "
   },
   { "name": "heatmap_interval", "label": "Heatmap interval (MS)", "query": "100,250" },
   { "name": "interval_tight", "query": "12s,60s,384s,3840s,92160s" },
   { "name": "interval", "query": "12s,60s,384s,3840s,92160s" },
   { "name": "interval_loose", "query": "384s,3840s,92160s" },
   { "name": "table_prefix", "label": "Prefix" },
   { "name": "attestation_prefix", "label": "Attestation Prefix" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active sentries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  count(DISTINCT(meta_client_name))\nFROM default.${table_prefix}beacon_api_slot\nWHERE\n  -- $__timeFilter(slot_start_date_time)\n  slot_start_date_time >= toDateTime(${__from:date:seconds})\n  AND slot_start_date_time <= (toDateTime(${__to:date:seconds}) - INTERVAL 1 MINUTE)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\nGROUP BY time\nORDER BY time\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Active Sentries",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n    meta_client_geo_latitude as latitude,\n    meta_client_geo_longitude as longitude,\n    meta_client_geo_city as city,\n    count(DISTINCT meta_client_name) as `count`\n    \nFROM \n    ${table_prefix}beacon_api_slot\nWHERE\n    slot_start_date_time >= now() - toIntervalMinute(2)\n    AND slot_start_date_time <= now() - toIntervalMinute(1)\n    AND meta_client_name IN (${client_name})\n    AND meta_network_name IN (${network_name})\n    AND meta_client_geo_continent_code IN (${geo_continent_code})\n    AND meta_consensus_implementation IN (${consensus_implementation})\n    AND meta_consensus_version IN (${consensus_version})\nGROUP BY\n    slot_start_date_time,\n    meta_client_geo_longitude,\n    meta_client_geo_latitude,\n    meta_client_geo_city\nORDER BY slot_start_date_time DESC\nLIMIT 1 by latitude, longitude\n"
    }
   ]
  },
  {
   "title": "Chain reorgs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  count(DISTINCT(slot))\nFROM default.${table_prefix}beacon_api_eth_v1_events_chain_reorg\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\nGROUP BY time\nORDER BY time DESC\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Blocks ingested",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "epoch_start_date_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as timestamp,\n    sumMerge(blocks) as count\nFROM default.${table_prefix}beacon_api_slot\n\nWHERE $timeFilter\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\n\nGROUP BY\n    timestamp",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(epoch_start_date_time), 120) * 120) * 1000 as timestamp,\n    sumMerge(blocks) as count\nFROM default.beacon_api_slot\n\nWHERE epoch_start_date_time >= toDateTime(1676109600) AND epoch_start_date_time <= toDateTime(1676116800)\n  AND meta_client_name IN ('xatu-sentry-ams3-goerli-teku-001','xatu-sentry-syd1-goerli-prysm-001','xatu-sentry-syd1-goerli-lodestar-001','xatu-sentry-syd1-goerli-nimbus-001','xatu-sentry-syd1-goerli-lighthouse-001','xatu-sentry-ams3-goerli-lighthouse-001','xatu-sentry-ams3-goerli-nimbus-001','xatu-sentry-ams3-goerli-lodestar-001','xatu-sentry-ams3-goerli-prysm-001','xatu-sentry-syd1-goerli-teku-001')\n  AND meta_network_name IN ('goerli')\n  AND meta_client_geo_continent_code IN ('OC','EU')\n  AND meta_consensus_implementation IN ('teku','prysm','nimbus','lodestar','lighthouse')\n  AND meta_consensus_version IN ('vUNKNOWN+gd368966','v3.4.0-38514c0+','v1.4.2','unknown (linux amd64)','v23.1.1-20fc35-stateofus')\n\nGROUP BY\n    timestamp",
     "round": "0s",
     "table": "${table_prefix}beacon_api_slot"
    }
   ]
  },
  {
   "title": "Attestations ingested",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "epoch_start_date_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as timestamp,\n    sumMerge(attestations) as count\nFROM default.${table_prefix}beacon_api_slot\n\nWHERE $timeFilter\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\n\nGROUP BY\n    timestamp",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(epoch_start_date_time), 120) * 120) * 1000 as timestamp,\n    sumMerge(attestations) as count\nFROM default.beacon_api_slot\n\nWHERE epoch_start_date_time >= toDateTime(1676109600) AND epoch_start_date_time <= toDateTime(1676116800)\n  AND meta_client_name IN ('xatu-sentry-ams3-goerli-teku-001','xatu-sentry-syd1-goerli-prysm-001','xatu-sentry-syd1-goerli-lodestar-001','xatu-sentry-syd1-goerli-nimbus-001','xatu-sentry-syd1-goerli-lighthouse-001','xatu-sentry-ams3-goerli-lighthouse-001','xatu-sentry-ams3-goerli-nimbus-001','xatu-sentry-ams3-goerli-lodestar-001','xatu-sentry-ams3-goerli-prysm-001','xatu-sentry-syd1-goerli-teku-001')\n  AND meta_network_name IN ('goerli')\n  AND meta_client_geo_continent_code IN ('OC','EU')\n  AND meta_consensus_implementation IN ('teku','prysm','nimbus','lodestar','lighthouse')\n  AND meta_consensus_version IN ('vUNKNOWN+gd368966','v3.4.0-38514c0+','v1.4.2','unknown (linux amd64)','v23.1.1-20fc35-stateofus')\n\nGROUP BY\n    timestamp",
     "round": "0s",
     "table": "${table_prefix}beacon_api_slot"
    }
   ]
  },
  { "title": "Summary per client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Active sentries (${consensus_implementation})",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "repeat": "consensus_implementation",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  count(DISTINCT(meta_client_name))\nFROM default.${table_prefix}beacon_api_slot\nWHERE\n  -- $__timeFilter(slot_start_date_time)\n  slot_start_date_time >= toDateTime(${__from:date:seconds})\n  AND slot_start_date_time <= (toDateTime(${__to:date:seconds}) - INTERVAL 1 MINUTE)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation = '${consensus_implementation}'\n  AND meta_consensus_version IN (${consensus_version})\nGROUP BY time\nORDER BY time\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Vector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transform routing",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum by (event) (increase(xatu_xatu_server_events_matched{client_name=~\"${client_name:regex}\", source=\"xatu-kafka-clickhouse\"}))",
       "legendFormat": "Matched - {{event}}"
      },
      {
       "expr": "sum by (event) (increase(xatu_xatu_server_events_unmatched{client_name=~\"${client_name:regex}\", source=\"xatu-kafka-clickhouse\"}))",
       "legendFormat": "Unmatched - {{event}}"
      }
     ]
    },
    {
     "title": "Clickhouse sink",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum by (component_id) (increase(vector_component_received_events_count_sum{component_kind=\"sink\", component_type=\"clickhouse\"}))",
       "legendFormat": "{{component_id}}"
      }
     ]
    },
    {
     "title": "Transform errors",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum by (component_id, error_type) (increase(vector_component_errors_total{component_kind=\"transform\"}))",
       "legendFormat": "{{component_id}} - {{error_type}}"
      }
     ]
    },
    {
     "title": "Sink errors",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "sum by (component_id, error_type) (increase(vector_component_errors_total{component_kind=\"sink\"}))",
       "legendFormat": "{{component_id}} - {{error_type}}"
      }
     ]
    }
   ]
  },
  { "title": "Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Block propagation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  max(propagation_slot_start_diff) max,\n  quantile(0.95)(propagation_slot_start_diff) p95,\n  avg(propagation_slot_start_diff) average,\n  quantile(0.50)(propagation_slot_start_diff) p50,\n  quantile(0.05)(propagation_slot_start_diff) p05,\n  min(propagation_slot_start_diff) min\nFROM default.${table_prefix}beacon_api_eth_v1_events_block\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND propagation_slot_start_diff < 100000\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\nGROUP BY time\nORDER BY time ASC\nLIMIT 10000"
    }
   ]
  },
  {
   "title": "Block propagation",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "slot_start_date_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries + 12000 as timestamp,\n    multiply(floor(divide(propagation_slot_start_diff, $heatmap_interval)), $heatmap_interval) as diff,\n    count() as count\nFROM default.${table_prefix}beacon_api_eth_v1_events_block\n\nWHERE $timeFilter\n  AND propagation_slot_start_diff < 100000\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\n\nGROUP BY\n    timestamp,\n    diff",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(slot_start_date_time), 12) * 12) * 1000 + 12000 as timestamp,\n    multiply(floor(divide(propagation_slot_start_diff, 250)), 250) as diff,\n    count() as count\nFROM default.beacon_api_eth_v1_events_block\n\nWHERE slot_start_date_time >= toDateTime(1685255484) AND slot_start_date_time <= toDateTime(1685256012)\n  AND propagation_slot_start_diff < 100000\n  AND meta_client_name IN ('xatu-sentry-ams3-mainnet-prysm-001','xatu-sentry-syd1-mainnet-prysm-002','xatu-sentry-sfo3-mainnet-prysm-001')\n  AND meta_network_name IN ('mainnet')\n  AND meta_client_geo_continent_code IN ('OC','NA','EU')\n  AND meta_consensus_implementation IN ('prysm')\n  AND meta_consensus_version IN ('unknown (linux amd64)')\n\nGROUP BY\n    timestamp,\n    diff",
     "round": "12s",
     "table": "${table_prefix}beacon_api_eth_v1_events_block"
    }
   ]
  },
  {
   "title": "Block propagation spread",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  stddevPop(propagation_slot_start_diff) `std dev population`,\n  quantile(0.90)(propagation_slot_start_diff) - quantile(0.10)(propagation_slot_start_diff) `p90 - p10`\nFROM default.${table_prefix}beacon_api_eth_v1_events_block\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND propagation_slot_start_diff < 10000\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\nGROUP BY time\nORDER BY time ASC\nLIMIT 10000"
    }
   ]
  },
  {
   "title": "Block propagation difference between sentries (by consensus client)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  max(diff) max,\n  quantile(0.95)(diff) p95,\n  avg(diff) average,\n  quantile(0.50)(diff) p50,\n  quantile(0.05)(diff) p05,\n  min(diff) min\nFROM (\n    SELECT\n        slot,\n        slot_start_date_time,\n        block,\n        meta_network_name,\n        max(propagation_slot_start_diff) - min(propagation_slot_start_diff) AS diff\n    FROM ${table_prefix}beacon_api_eth_v1_events_block\n    WHERE\n        $__timeFilter(slot_start_date_time)\n        AND meta_network_name IN (${network_name})\n        AND meta_client_geo_continent_code IN (${geo_continent_code})\n        AND meta_consensus_implementation IN (${consensus_implementation})\n        AND meta_consensus_version IN (${consensus_version})\n    GROUP BY slot, slot_start_date_time, block, meta_network_name, meta_consensus_implementation\n)\nWHERE\n  diff > 0\n  AND diff < 100000\nGROUP BY time\nORDER BY time ASC\nLIMIT 10000"
    }
   ]
  },
  {
   "title": "Unique Blocks per slot",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT\n  slot_start_date_time,\n  count(DISTINCT(block))\nFROM default.${table_prefix}beacon_api_eth_v1_events_block\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\nGROUP BY slot_start_date_time\nORDER BY slot_start_date_time ASC\nLIMIT 10000"
    }
   ]
  },
  {
   "title": "Latest epoch",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  max(epoch)\nFROM default.${table_prefix}beacon_api_eth_v1_events_block\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\nGROUP BY time\nORDER BY time ASC\nLIMIT 10000"
    }
   ]
  },
  {
   "title": "Latest slot",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  max(slot)\nFROM default.${table_prefix}beacon_api_eth_v1_events_block\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\nGROUP BY time\nORDER BY time ASC\nLIMIT 10000\n"
    }
   ]
  },
  {
   "title": "Blocks per sentry",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  meta_client_name as name,\n  sumMerge(blocks) as count\nFROM default.${table_prefix}beacon_api_slot\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\nGROUP BY time, meta_client_name\nORDER BY time ASC\nLIMIT 100000"
    }
   ]
  },
  { "title": "Block size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Block propagation for block size (25KiB buckets)",
   "type": "trend",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "WITH \n    filtered_v1 AS (\n        SELECT block, propagation_slot_start_diff\n        FROM default.beacon_api_eth_v1_events_block\n        WHERE slot_start_date_time >= $__fromTime AND slot_start_date_time <= $__toTime\n        AND propagation_slot_start_diff < 8000\n        AND meta_client_name IN (${client_name})\n        AND meta_network_name IN (${network_name})\n        AND meta_client_geo_continent_code IN (${geo_continent_code})\n        AND meta_consensus_implementation IN (${consensus_implementation})\n        AND meta_consensus_version IN (${consensus_version})\n    ),\n    filtered_v2 AS (\n        SELECT block_root, floor(block_total_bytes / 25600) * 25600 AS bucketed_bytes\n        FROM default.beacon_api_eth_v2_beacon_block\n        WHERE slot_start_date_time >= $__fromTime AND slot_start_date_time <= $__toTime\n    )\nSELECT \n    max(filtered_v1.propagation_slot_start_diff) max,\n    quantile(0.95)(filtered_v1.propagation_slot_start_diff) p95,\n    avg(filtered_v1.propagation_slot_start_diff) average,\n    quantile(0.50)(filtered_v1.propagation_slot_start_diff) p50,\n    quantile(0.05)(filtered_v1.propagation_slot_start_diff) p05,\n    min(filtered_v1.propagation_slot_start_diff) min,\n    filtered_v2.bucketed_bytes\nFROM \n    filtered_v1\nGLOBAL INNER JOIN \n    filtered_v2\nON \n    filtered_v1.block = filtered_v2.block_root\nGROUP BY\n    filtered_v2.bucketed_bytes\nORDER BY \n    filtered_v2.bucketed_bytes ASC;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Block propagation for block size (100KiB buckets)",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "WITH \n    filtered_v1 AS (\n        SELECT block, propagation_slot_start_diff\n        FROM default.beacon_api_eth_v1_events_block\n        WHERE slot_start_date_time >= $__fromTime AND slot_start_date_time <= $__toTime\n        AND propagation_slot_start_diff < 8000\n        AND meta_client_name IN (${client_name})\n        AND meta_network_name IN (${network_name})\n        AND meta_client_geo_continent_code IN (${geo_continent_code})\n        AND meta_consensus_implementation IN (${consensus_implementation})\n        AND meta_consensus_version IN (${consensus_version})\n    ),\n    filtered_v2 AS (\n        SELECT block_root, floor(block_total_bytes / 102400) * 102400 AS bucketed_bytes\n        FROM default.beacon_api_eth_v2_beacon_block\n        WHERE slot_start_date_time >= $__fromTime AND slot_start_date_time <= $__toTime\n    )\nSELECT \n    filtered_v2.bucketed_bytes,\n    max(filtered_v1.propagation_slot_start_diff) max,\n    quantile(0.95)(filtered_v1.propagation_slot_start_diff) p95,\n    avg(filtered_v1.propagation_slot_start_diff) average,\n    quantile(0.50)(filtered_v1.propagation_slot_start_diff) p50,\n    quantile(0.05)(filtered_v1.propagation_slot_start_diff) p05,\n    min(filtered_v1.propagation_slot_start_diff) min\nFROM \n    filtered_v1\nGLOBAL INNER JOIN \n    filtered_v2\nON \n    filtered_v1.block = filtered_v2.block_root\nGROUP BY\n    filtered_v2.bucketed_bytes\nORDER BY \n    filtered_v2.bucketed_bytes ASC;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Block propagation for block size (compressed, 25KiB buckets)",
   "type": "trend",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "WITH \n    filtered_v1 AS (\n        SELECT block, propagation_slot_start_diff\n        FROM default.beacon_api_eth_v1_events_block\n        WHERE slot_start_date_time >= $__fromTime AND slot_start_date_time <= $__toTime\n        AND propagation_slot_start_diff < 8000\n        AND meta_client_name IN (${client_name})\n        AND meta_network_name IN (${network_name})\n        AND meta_client_geo_continent_code IN (${geo_continent_code})\n        AND meta_consensus_implementation IN (${consensus_implementation})\n        AND meta_consensus_version IN (${consensus_version})\n    ),\n    filtered_v2 AS (\n        SELECT block_root, floor(block_total_bytes_compressed / 25600) * 25600 AS bucketed_bytes\n        FROM default.beacon_api_eth_v2_beacon_block\n        WHERE slot_start_date_time >= $__fromTime AND slot_start_date_time <= $__toTime\n    )\nSELECT \n    max(filtered_v1.propagation_slot_start_diff) max,\n    quantile(0.95)(filtered_v1.propagation_slot_start_diff) p95,\n    avg(filtered_v1.propagation_slot_start_diff) average,\n    quantile(0.50)(filtered_v1.propagation_slot_start_diff) p50,\n    quantile(0.05)(filtered_v1.propagation_slot_start_diff) p05,\n    min(filtered_v1.propagation_slot_start_diff) min,\n    filtered_v2.bucketed_bytes\nFROM \n    filtered_v1\nGLOBAL INNER JOIN \n    filtered_v2\nON \n    filtered_v1.block = filtered_v2.block_root\nGROUP BY\n    filtered_v2.bucketed_bytes\nORDER BY \n    filtered_v2.bucketed_bytes ASC;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Block propagation for block size (compressed, 100KiB buckets)",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "WITH \n    filtered_v1 AS (\n        SELECT block, propagation_slot_start_diff\n        FROM default.beacon_api_eth_v1_events_block\n        WHERE slot_start_date_time >= $__fromTime AND slot_start_date_time <= $__toTime\n        AND propagation_slot_start_diff < 8000\n        AND meta_client_name IN (${client_name})\n        AND meta_network_name IN (${network_name})\n        AND meta_client_geo_continent_code IN (${geo_continent_code})\n        AND meta_consensus_implementation IN (${consensus_implementation})\n        AND meta_consensus_version IN (${consensus_version})\n    ),\n    filtered_v2 AS (\n        SELECT block_root, floor(block_total_bytes_compressed / 102400) * 102400 AS bucketed_bytes\n        FROM default.beacon_api_eth_v2_beacon_block\n        WHERE slot_start_date_time >= $__fromTime AND slot_start_date_time <= $__toTime\n    )\nSELECT \n    filtered_v2.bucketed_bytes,\n    max(filtered_v1.propagation_slot_start_diff) max,\n    quantile(0.95)(filtered_v1.propagation_slot_start_diff) p95,\n    avg(filtered_v1.propagation_slot_start_diff) average,\n    quantile(0.50)(filtered_v1.propagation_slot_start_diff) p50,\n    quantile(0.05)(filtered_v1.propagation_slot_start_diff) p05,\n    min(filtered_v1.propagation_slot_start_diff) min\nFROM \n    filtered_v1\nGLOBAL INNER JOIN \n    filtered_v2\nON \n    filtered_v1.block = filtered_v2.block_root\nGROUP BY\n    filtered_v2.bucketed_bytes\nORDER BY \n    filtered_v2.bucketed_bytes ASC;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Block propagation for execution transactions size (25KiB buckets)",
   "type": "trend",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "WITH \n    filtered_v1 AS (\n        SELECT block, propagation_slot_start_diff\n        FROM default.beacon_api_eth_v1_events_block\n        WHERE slot_start_date_time >= $__fromTime AND slot_start_date_time <= $__toTime\n        AND propagation_slot_start_diff < 8000\n        AND meta_client_name IN (${client_name})\n        AND meta_network_name IN (${network_name})\n        AND meta_client_geo_continent_code IN (${geo_continent_code})\n        AND meta_consensus_implementation IN (${consensus_implementation})\n        AND meta_consensus_version IN (${consensus_version})\n    ),\n    filtered_v2 AS (\n        SELECT block_root, floor(execution_payload_transactions_total_bytes / 25600) * 25600 AS bucketed_bytes\n        FROM default.beacon_api_eth_v2_beacon_block\n        WHERE slot_start_date_time >= $__fromTime AND slot_start_date_time <= $__toTime\n    )\nSELECT \n    max(filtered_v1.propagation_slot_start_diff) max,\n    quantile(0.95)(filtered_v1.propagation_slot_start_diff) p95,\n    avg(filtered_v1.propagation_slot_start_diff) average,\n    quantile(0.50)(filtered_v1.propagation_slot_start_diff) p50,\n    quantile(0.05)(filtered_v1.propagation_slot_start_diff) p05,\n    min(filtered_v1.propagation_slot_start_diff) min,\n    filtered_v2.bucketed_bytes\nFROM \n    filtered_v1\nGLOBAL INNER JOIN \n    filtered_v2\nON \n    filtered_v1.block = filtered_v2.block_root\nGROUP BY\n    filtered_v2.bucketed_bytes\nORDER BY \n    filtered_v2.bucketed_bytes ASC;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Block propagation for execution transactions size (100KiB buckets)",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "WITH \n    filtered_v1 AS (\n        SELECT block, propagation_slot_start_diff\n        FROM default.beacon_api_eth_v1_events_block\n        WHERE slot_start_date_time >= $__fromTime AND slot_start_date_time <= $__toTime\n        AND propagation_slot_start_diff < 8000\n        AND meta_client_name IN (${client_name})\n        AND meta_network_name IN (${network_name})\n        AND meta_client_geo_continent_code IN (${geo_continent_code})\n        AND meta_consensus_implementation IN (${consensus_implementation})\n        AND meta_consensus_version IN (${consensus_version})\n    ),\n    filtered_v2 AS (\n        SELECT block_root, floor(execution_payload_transactions_total_bytes / 102400) * 102400 AS bucketed_bytes\n        FROM default.beacon_api_eth_v2_beacon_block\n        WHERE slot_start_date_time >= $__fromTime AND slot_start_date_time <= $__toTime\n    )\nSELECT \n    filtered_v2.bucketed_bytes,\n    max(filtered_v1.propagation_slot_start_diff) max,\n    quantile(0.95)(filtered_v1.propagation_slot_start_diff) p95,\n    avg(filtered_v1.propagation_slot_start_diff) average,\n    quantile(0.50)(filtered_v1.propagation_slot_start_diff) p50,\n    quantile(0.05)(filtered_v1.propagation_slot_start_diff) p05,\n    min(filtered_v1.propagation_slot_start_diff) min\nFROM \n    filtered_v1\nGLOBAL INNER JOIN \n    filtered_v2\nON \n    filtered_v1.block = filtered_v2.block_root\nGROUP BY\n    filtered_v2.bucketed_bytes\nORDER BY \n    filtered_v2.bucketed_bytes ASC;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Block propagation for execution transactions size (compressed, 25KiB buckets)",
   "type": "trend",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "WITH \n    filtered_v1 AS (\n        SELECT block, propagation_slot_start_diff\n        FROM default.beacon_api_eth_v1_events_block\n        WHERE slot_start_date_time >= $__fromTime AND slot_start_date_time <= $__toTime\n        AND propagation_slot_start_diff < 8000\n        AND meta_client_name IN (${client_name})\n        AND meta_network_name IN (${network_name})\n        AND meta_client_geo_continent_code IN (${geo_continent_code})\n        AND meta_consensus_implementation IN (${consensus_implementation})\n        AND meta_consensus_version IN (${consensus_version})\n    ),\n    filtered_v2 AS (\n        SELECT block_root, floor(execution_payload_transactions_total_bytes_compressed / 25600) * 25600 AS bucketed_bytes\n        FROM default.beacon_api_eth_v2_beacon_block\n        WHERE slot_start_date_time >= $__fromTime AND slot_start_date_time <= $__toTime\n    )\nSELECT \n    max(filtered_v1.propagation_slot_start_diff) max,\n    quantile(0.95)(filtered_v1.propagation_slot_start_diff) p95,\n    avg(filtered_v1.propagation_slot_start_diff) average,\n    quantile(0.50)(filtered_v1.propagation_slot_start_diff) p50,\n    quantile(0.05)(filtered_v1.propagation_slot_start_diff) p05,\n    min(filtered_v1.propagation_slot_start_diff) min,\n    filtered_v2.bucketed_bytes\nFROM \n    filtered_v1\nGLOBAL INNER JOIN \n    filtered_v2\nON \n    filtered_v1.block = filtered_v2.block_root\nGROUP BY\n    filtered_v2.bucketed_bytes\nORDER BY \n    filtered_v2.bucketed_bytes ASC;",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Block propagation for execution transactions size (compressed, 100KiB buckets)",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "WITH \n    filtered_v1 AS (\n        SELECT block, propagation_slot_start_diff\n        FROM default.beacon_api_eth_v1_events_block\n        WHERE slot_start_date_time >= $__fromTime AND slot_start_date_time <= $__toTime\n        AND propagation_slot_start_diff < 8000\n        AND meta_client_name IN (${client_name})\n        AND meta_network_name IN (${network_name})\n        AND meta_client_geo_continent_code IN (${geo_continent_code})\n        AND meta_consensus_implementation IN (${consensus_implementation})\n        AND meta_consensus_version IN (${consensus_version})\n    ),\n    filtered_v2 AS (\n        SELECT block_root, floor(execution_payload_transactions_total_bytes_compressed / 102400) * 102400 AS bucketed_bytes\n        FROM default.beacon_api_eth_v2_beacon_block\n        WHERE slot_start_date_time >= $__fromTime AND slot_start_date_time <= $__toTime\n    )\nSELECT \n    filtered_v2.bucketed_bytes,\n    max(filtered_v1.propagation_slot_start_diff) max,\n    quantile(0.95)(filtered_v1.propagation_slot_start_diff) p95,\n    avg(filtered_v1.propagation_slot_start_diff) average,\n    quantile(0.50)(filtered_v1.propagation_slot_start_diff) p50,\n    quantile(0.05)(filtered_v1.propagation_slot_start_diff) p05,\n    min(filtered_v1.propagation_slot_start_diff) min\nFROM \n    filtered_v1\nGLOBAL INNER JOIN \n    filtered_v2\nON \n    filtered_v1.block = filtered_v2.block_root\nGROUP BY\n    filtered_v2.bucketed_bytes\nORDER BY \n    filtered_v2.bucketed_bytes ASC;",
     "selectedFormat": 4
    }
   ]
  },
  { "title": "Blob sidecars", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 } },
  {
   "title": "Blob sidecar propagation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "\nSELECT\n  $__timeInterval(slot_start_date_time) as time,\n  max(propagation_slot_start_diff) max,\n  quantile(0.95)(propagation_slot_start_diff) p95,\n  avg(propagation_slot_start_diff) average,\n  quantile(0.50)(propagation_slot_start_diff) p50,\n  quantile(0.05)(propagation_slot_start_diff) p05,\n  min(propagation_slot_start_diff) min\nFROM default.${attestation_prefix}beacon_api_eth_v1_events_blob_sidecar\nWHERE\n  $__timeFilter(slot_start_date_time)\n  -- AND propagation_slot_start_diff < 30000\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\nGROUP BY time\nORDER BY time ASC\nLIMIT 10000",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Blob sidecar propagation",
   "type": "heatmap",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 118 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "slot_start_date_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries + 12000 as timestamp,\n    toUInt8(propagation_slot_start_diff / ${heatmap_interval}) * ${heatmap_interval} as diff,\n    sum(toUInt16(1)) as count\nFROM ${attestation_prefix}beacon_api_eth_v1_events_blob_sidecar\n\nWHERE $timeFilter\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\n  AND diff < 30000\n\nGROUP BY\n    timestamp,\n    diff\n    \nLIMIT 10000000\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(slot_start_date_time), 12) * 12) * 1000 + 12000 as timestamp,\n    toUInt8(propagation_slot_start_diff / 250) * 250 as diff,\n    sum(toUInt16(1)) as count\nFROM beacon_api_eth_v1_events_blob_sidecar\n\nWHERE slot_start_date_time >= toDateTime(1696882980) AND slot_start_date_time <= toDateTime(1696886580)\n  AND meta_client_name IN ('xatu-sentry-ams3-mainnet-prysm-001','xatu-sentry-sfo3-mainnet-prysm-001','xatu-sentry-syd1-mainnet-nimbus-001','xatu-sentry-syd1-mainnet-lodestar-001','xatu-sentry-sfo3-mainnet-lighthouse-001','xatu-sentry-syd1-mainnet-teku-001','xatu-sentry-ams3-mainnet-lighthouse-001','xatu-sentry-sfo3-mainnet-lodestar-001','xatu-sentry-ams3-mainnet-teku-001','xatu-sentry-syd1-mainnet-lighthouse-001','xatu-sentry-ams3-mainnet-lodestar-001','xatu-sentry-sfo3-mainnet-teku-001','xatu-sentry-sfo3-mainnet-nimbus-001','xatu-sentry-ams3-mainnet-nimbus-001','xatu-sentry-syd1-mainnet-prysm-001')\n  AND meta_network_name IN ('mainnet')\n  AND meta_client_geo_continent_code IN ('OC','NA','EU')\n  AND meta_consensus_implementation IN ('teku','prysm','nimbus','lodestar','lighthouse')\n  AND meta_consensus_version IN ('vUNKNOWN+g03d2812','v23.7.0-41634f-stateofus','v4.3.0-31daf3a+','unknown (linux amd64)','v1.10.0')\n  AND diff < 30000\n\nGROUP BY\n    timestamp,\n    diff\n    \nLIMIT 10000000",
     "round": "12s",
     "table": "${table_prefix}beacon_api_eth_v1_events_attestation"
    }
   ]
  },
  {
   "title": "Blob sidecar propagation difference between sentries",
   "type": "timeseries",
   "description": "The difference between when an blob sidecar is seen by the first and last sentry",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  max(diff) max,\n  quantile(0.95)(diff) p95,\n  avg(diff) average,\n  quantile(0.50)(diff) p50,\n  quantile(0.05)(diff) p05,\n  min(diff) min\nFROM (\n    SELECT\n        slot,\n        slot_start_date_time,\n        kzg_commitment,\n        meta_network_name,\n        max(propagation_slot_start_diff) - min(propagation_slot_start_diff) AS diff\n    FROM ${attestation_prefix}beacon_api_eth_v1_events_blob_sidecar\n    WHERE\n        $__timeFilter(slot_start_date_time)\n        AND slot_start_date_time <= toDateTime(${__to:date:seconds})\n        AND meta_network_name IN (${network_name})\n        AND meta_client_geo_continent_code IN (${geo_continent_code})\n        AND meta_consensus_implementation IN (${consensus_implementation})\n        AND meta_consensus_version IN (${consensus_version})\n    GROUP BY slot, slot_start_date_time, kzg_commitment, meta_network_name\n    HAVING diff > 0 AND diff < 30000\n)\nGROUP BY time\nORDER BY time ASC\nLIMIT 100000\n",
     "selectedFormat": 4
    }
   ]
  },
  { "title": "Attestations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 } },
  {
   "title": "Attestation propagation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "\nSELECT\n  $__timeInterval(slot_start_date_time) as time,\n  max(propagation_slot_start_diff) max,\n  quantile(0.95)(propagation_slot_start_diff) p95,\n  avg(propagation_slot_start_diff) average,\n  quantile(0.50)(propagation_slot_start_diff) p50,\n  quantile(0.05)(propagation_slot_start_diff) p05,\n  min(propagation_slot_start_diff) min\nFROM default.${attestation_prefix}beacon_api_eth_v1_events_attestation\nWHERE\n  $__timeFilter(slot_start_date_time)\n  -- AND propagation_slot_start_diff < 30000\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\nGROUP BY time\nORDER BY time ASC\nLIMIT 10000"
    }
   ]
  },
  {
   "title": "Attestation seen rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 155 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  count(DISTINCT signature) as attestations\nFROM default.${attestation_prefix}beacon_api_eth_v1_events_attestation\nWHERE\n    $__timeFilter(slot_start_date_time)\n    AND meta_client_name IN (${client_name})\n    AND meta_network_name IN (${network_name})\n    AND meta_client_geo_continent_code IN (${geo_continent_code})\n    AND meta_consensus_implementation IN (${consensus_implementation})\n    AND meta_consensus_version IN (${consensus_version})\nGROUP BY time\nORDER BY time ASC\nLIMIT 10000"
    },
    {
     "rawSql": "\nSELECT\n  $__timeInterval(slot_start_date_time) as time,\n  uniq(signature) AS total\nFROM default.${attestation_prefix}beacon_api_eth_v1_events_attestation\nWHERE\n    $__timeFilter(slot_start_date_time)\n    AND meta_client_name IN (${client_name})\n    AND meta_network_name IN (${network_name})\n    AND meta_client_geo_continent_code IN (${geo_continent_code})\n    AND meta_consensus_implementation IN (${consensus_implementation})\n    AND meta_consensus_version IN (${consensus_version})\nGROUP BY time\nORDER BY time ASC\nLIMIT 10000\n"
    }
   ]
  },
  {
   "title": "Attestation seen distance",
   "type": "timeseries",
   "description": "Similar to inclusion distance but instead of when it was included in a block, it's instead when a sentry saw a attestation and the \"distance\" between its target and the current slot. \"0\" being the attestation for the current slot, \"1\" being current slot - 1 etc.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toDateTime(slot_start_date_time) as time,\n  percent\nFROM \n(\n    SELECT\n        slot_start_date_time,\n        interval,\n        round((inclusion_count / interval_total) * 100, 2) AS percent\n    FROM\n    (\n        SELECT\n            slot_start_date_time,\n            interval,\n            inclusion_count,\n            sum(inclusion_count) OVER (PARTITION BY slot_start_date_time) AS interval_total\n        FROM\n        (\n            SELECT\n                slot_start_date_time,\n                floor(divide(propagation_slot_start_diff, 12000)) as interval,\n                count(DISTINCT signature) as inclusion_count\n            FROM default.${attestation_prefix}beacon_api_eth_v1_events_attestation\n\n            WHERE\n                $__timeFilter(slot_start_date_time)\n                AND meta_client_name IN (${client_name})\n                AND meta_network_name IN (${network_name})\n                AND meta_client_geo_continent_code IN (${geo_continent_code})\n                AND meta_consensus_implementation IN (${consensus_implementation})\n                AND meta_consensus_version IN (${consensus_version})\n            GROUP BY\n                slot_start_date_time,\n                interval\n            ORDER BY inclusion_count DESC\n        )\n    )\n)\nORDER BY time ASC, percent DESC"
    }
   ]
  },
  {
   "title": "Attestation propagation",
   "type": "heatmap",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 169 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "slot_start_date_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries + 12000 as timestamp,\n    toUInt8(propagation_slot_start_diff / ${heatmap_interval}) * ${heatmap_interval} as diff,\n    sum(toUInt16(1)) as count\nFROM ${attestation_prefix}beacon_api_eth_v1_events_attestation\n\nWHERE $timeFilter\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\n  AND diff < 30000\n\nGROUP BY\n    timestamp,\n    diff\n    \nLIMIT 10000000\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(slot_start_date_time), 12) * 12) * 1000 + 12000 as timestamp,\n    toUInt8(propagation_slot_start_diff / 250) * 250 as diff,\n    sum(toUInt16(1)) as count\nFROM beacon_api_eth_v1_events_attestation\n\nWHERE slot_start_date_time >= toDateTime(1688945436) AND slot_start_date_time <= toDateTime(1688949036)\n  AND meta_client_name IN ('xatu-sentry-syd1-sepolia-prysm-001','xatu-sentry-ams3-sepolia-nimbus-001','xatu-sentry-ams3-sepolia-lodestar-001','xatu-sentry-sfo3-sepolia-teku-001','xatu-sentry-sfo3-sepolia-lodestar-001','xatu-sentry-syd1-sepolia-lighthouse-001','xatu-sentry-syd1-sepolia-teku-001','xatu-sentry-ams3-sepolia-lighthouse-001','xatu-sentry-syd1-sepolia-lodestar-001','xatu-sentry-sfo3-sepolia-lighthouse-001','xatu-sentry-sfo3-sepolia-prysm-001','xatu-sentry-ams3-sepolia-prysm-001')\n  AND meta_network_name IN ('sepolia')\n  AND meta_client_geo_continent_code IN ('OC','NA','EU')\n  AND meta_consensus_implementation IN ('teku','prysm','nimbus','lodestar','lighthouse')\n  AND meta_consensus_version IN ('vUNKNOWN+gfccbaf1','v1.8.0','unknown (linux amd64)','v4.1.0-7c0b275+','v23.5.0-748be8-stateofus')\n  AND diff < 30000\n\nGROUP BY\n    timestamp,\n    diff\n    \nLIMIT 10000000",
     "round": "12s",
     "table": "${table_prefix}beacon_api_eth_v1_events_attestation"
    }
   ]
  },
  {
   "title": "Attestation propagation for proposed block",
   "type": "heatmap",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 188 },
   "targets": [
    {
     "rawSql": "WITH subquery AS (\n    WITH \n    filtered_blocks AS (\n        SELECT \n            slot, \n            slot_start_date_time\n        FROM beacon_api_eth_v2_beacon_block\n        WHERE $__timeFilter(slot_start_date_time)\n            AND meta_network_name IN (${network_name})\n    ),\n    filtered_attestations AS (\n        SELECT \n            signature, \n            slot_start_date_time,\n            slot,\n            propagation_slot_start_diff\n        FROM default.${attestation_prefix}beacon_api_eth_v1_events_attestation\n        WHERE $__timeFilter(slot_start_date_time)\n            AND meta_client_name IN (${client_name})\n            AND meta_network_name IN (${network_name})\n            AND meta_client_geo_continent_code IN (${geo_continent_code})\n            AND meta_consensus_implementation IN (${consensus_implementation})\n            AND meta_consensus_version IN (${consensus_version})\n            AND propagation_slot_start_diff BETWEEN 0 AND 12000\n    ),\n    min_propagations AS (\n        SELECT \n            signature, \n            slot_start_date_time, \n            MIN(intDiv(propagation_slot_start_diff, 250) * 250) as min_propagation_bucket\n        FROM filtered_attestations \n        GROUP BY \n            signature,\n            slot_start_date_time\n    )\n    SELECT \n        b.slot_start_date_time as slot_start_date_time, \n        m.min_propagation_bucket AS min_propagation_bucket, \n        COUNT(DISTINCT m.signature) AS count\n    FROM min_propagations m\n    JOIN filtered_attestations a \n        ON a.signature = m.signature \n        AND a.slot_start_date_time = m.slot_start_date_time\n        AND intDiv(a.propagation_slot_start_diff, 250) * 250 = m.min_propagation_bucket\n    JOIN filtered_blocks b \n        ON a.slot = b.slot\n    GROUP BY \n        b.slot_start_date_time, \n        m.min_propagation_bucket\n)\nSELECT \n    toDateTime(slot_start_date_time) as time,\n    min_propagation_bucket as diff,\n    count\nFROM subquery\nORDER BY \n    slot_start_date_time, \n    min_propagation_bucket"
    }
   ]
  },
  {
   "title": "Attestation agreement",
   "type": "timeseries",
   "description": "For a given slot, what beacon block roots had attestations against them",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toDateTime(slot_start_date_time) as time,\n  percent\nFROM \n(\n  SELECT\n      slot_start_date_time,\n      beacon_block_root,\n      round((attestation_count / beacon_block_root_total) * 100, 2) AS percent\n  FROM\n  (\n      SELECT\n          slot_start_date_time,\n          beacon_block_root,\n          attestation_count,\n          sum(attestation_count) OVER (PARTITION BY slot_start_date_time) AS beacon_block_root_total\n      FROM\n      (\n          SELECT\n              slot_start_date_time,\n              beacon_block_root,\n              sum(toUInt32(1)) AS attestation_count\n          FROM default.${attestation_prefix}beacon_api_eth_v1_events_attestation\n          WHERE\n              $__timeFilter(slot_start_date_time)\n              AND meta_client_name IN (${client_name})\n              AND meta_network_name IN (${network_name})\n              AND meta_client_geo_continent_code IN (${geo_continent_code})\n              AND meta_consensus_implementation IN (${consensus_implementation})\n              AND meta_consensus_version IN (${consensus_version})\n          GROUP BY\n              slot_start_date_time,\n              beacon_block_root\n          ORDER BY attestation_count DESC\n      )\n  )\n)\nORDER BY time ASC, percent DESC"
    }
   ]
  },
  {
   "title": "Attestation propagation spread",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  stddevPop(propagation_slot_start_diff) `std dev population`,\n  quantile(0.90)(propagation_slot_start_diff) - quantile(0.10)(propagation_slot_start_diff) `p90 - p10`\nFROM default.${attestation_prefix}beacon_api_eth_v1_events_attestation\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\nGROUP BY time\nORDER BY time ASC\nLIMIT 10000"
    }
   ]
  },
  {
   "title": "Attestation propagation difference between sentries",
   "type": "timeseries",
   "description": "The difference between when an attestation is seen by the first and last sentry",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 220 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  max(diff) max,\n  quantile(0.95)(diff) p95,\n  avg(diff) average,\n  quantile(0.50)(diff) p50,\n  quantile(0.05)(diff) p05,\n  min(diff) min\nFROM (\n    SELECT\n        slot,\n        slot_start_date_time,\n        signature,\n        meta_network_name,\n        max(propagation_slot_start_diff) - min(propagation_slot_start_diff) AS diff\n    FROM ${attestation_prefix}beacon_api_eth_v1_events_attestation\n    WHERE\n        $__timeFilter(slot_start_date_time)\n        AND slot_start_date_time <= toDateTime(${__to:date:seconds})\n        AND meta_network_name IN (${network_name})\n        AND meta_client_geo_continent_code IN (${geo_continent_code})\n        AND meta_consensus_implementation IN (${consensus_implementation})\n        AND meta_consensus_version IN (${consensus_version})\n    GROUP BY slot, slot_start_date_time, signature, meta_network_name\n    HAVING diff > 0 AND diff < 30000\n)\nGROUP BY time\nORDER BY time ASC\nLIMIT 100000\n"
    }
   ]
  },
  {
   "title": "Attestations per sentry",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 228 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  meta_client_name as name,\n  sumMerge(attestations) as count\nFROM default.${table_prefix}beacon_api_slot\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\nGROUP BY time, meta_client_name\nORDER BY time ASC\nLIMIT 10000"
    }
   ]
  },
  {
   "title": "Attestations per epoch per sentry",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 228 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  sumMerge(attestations) as count,\n  meta_client_name\nFROM default.${table_prefix}beacon_api_slot\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\nGROUP BY time, meta_client_name\nORDER BY time ASC\nLIMIT 10000"
    }
   ]
  },
  { "title": "Contribution and proof", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 237 } },
  {
   "title": "Contribution and proof propagation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 238 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(contribution_slot_start_date_time) as time,\n  max(contribution_propagation_slot_start_diff) max,\n  quantile(0.95)(contribution_propagation_slot_start_diff) p95,\n  avg(contribution_propagation_slot_start_diff) average,\n  quantile(0.50)(contribution_propagation_slot_start_diff) p50,\n  quantile(0.05)(contribution_propagation_slot_start_diff) p05,\n  min(contribution_propagation_slot_start_diff) min\nFROM default.${table_prefix}beacon_api_eth_v1_events_contribution_and_proof\nWHERE\n  $__timeFilter(contribution_slot_start_date_time)\n  -- AND contribution_propagation_slot_start_diff < 10000\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\nGROUP BY time\nORDER BY time ASC\nLIMIT 10000"
    }
   ]
  },
  {
   "title": "Contribution and proof propagation",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 247 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "contribution_slot_start_date_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries + 12000 as timestamp,\n    multiply(floor(divide(contribution_propagation_slot_start_diff, $heatmap_interval)), $heatmap_interval) as diff,\n    count() as count\nFROM default.${table_prefix}beacon_api_eth_v1_events_contribution_and_proof\n\nWHERE $timeFilter\n  -- AND contribution_propagation_slot_start_diff < 10000\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\n\nGROUP BY\n    timestamp,\n    diff",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(contribution_slot_start_date_time), 20) * 20) * 1000 + 12000 as timestamp,\n    multiply(floor(divide(contribution_propagation_slot_start_diff, 250)), 250) as diff,\n    count() as count\nFROM default.beacon_api_eth_v1_events_contribution_and_proof\n\nWHERE contribution_slot_start_date_time >= toDateTime(1676109600) AND contribution_slot_start_date_time <= toDateTime(1676116800)\n  \n  AND meta_client_name IN ('xatu-sentry-ams3-goerli-teku-001','xatu-sentry-syd1-goerli-prysm-001','xatu-sentry-syd1-goerli-lodestar-001','xatu-sentry-syd1-goerli-nimbus-001','xatu-sentry-syd1-goerli-lighthouse-001','xatu-sentry-ams3-goerli-lighthouse-001','xatu-sentry-ams3-goerli-nimbus-001','xatu-sentry-ams3-goerli-lodestar-001','xatu-sentry-ams3-goerli-prysm-001','xatu-sentry-syd1-goerli-teku-001')\n  AND meta_network_name IN ('goerli')\n  AND meta_client_geo_continent_code IN ('OC','EU')\n  AND meta_consensus_implementation IN ('teku','prysm','nimbus','lodestar','lighthouse')\n  AND meta_consensus_version IN ('vUNKNOWN+gd368966','v3.4.0-38514c0+','v1.4.2','unknown (linux amd64)','v23.1.1-20fc35-stateofus')\n\nGROUP BY\n    timestamp,\n    diff",
     "round": "12s",
     "table": "${table_prefix}beacon_api_eth_v1_events_contribution_and_proof"
    }
   ]
  },
  {
   "title": "Contribution and proof propagation spread",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 260 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(contribution_slot_start_date_time) as time,\n  stddevPop(contribution_propagation_slot_start_diff) `std dev population`,\n  quantile(0.90)(contribution_propagation_slot_start_diff) - quantile(0.10)(contribution_propagation_slot_start_diff) `p90 - p10`\nFROM default.${table_prefix}beacon_api_eth_v1_events_contribution_and_proof\nWHERE\n  $__timeFilter(contribution_slot_start_date_time)\n  -- AND contribution_propagation_slot_start_diff < 10000\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\nGROUP BY time\nORDER BY time ASC\nLIMIT 10000"
    }
   ]
  },
  { "title": "Chain reorgs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 266 } },
  {
   "title": "Chain reorgs (depth)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 267 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(event_date_time) as time,\n  max(depth),\n  meta_client_name\nFROM default.${table_prefix}beacon_api_eth_v1_events_chain_reorg\nWHERE\n  $__timeFilter(event_date_time)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\nGROUP BY time, meta_client_name, depth\nORDER BY time ASC\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Chain reorgs",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 279 },
   "targets": [
    {
     "rawSql": "SELECT\n  event_date_time,\n  meta_client_name,\n  epoch,\n  slot,\n  depth,\n  old_head_block,\n  new_head_block,\n  old_head_state,\n  new_head_state\nFROM default.${table_prefix}beacon_api_eth_v1_events_chain_reorg\nWHERE\n  $__timeFilter(event_date_time)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND meta_consensus_implementation IN (${consensus_implementation})\n  AND meta_consensus_version IN (${consensus_version})\nLIMIT 10000"
    }
   ]
  }
 ]
}