{
 "title": "Gossipsub Events",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network_name",
    "label": "Network",
    "query": "SELECT meta_network_name\nFROM libp2p_gossipsub_beacon_block\nWHERE\n  slot_start_date_time >= toDateTime(${__from} / 1000)\n  AND slot_start_date_time <= toDateTime(${__to} / 1000)\nGROUP BY meta_network_name "
   },
   {
    "name": "client_name",
    "label": "Sentry",
    "query": "SELECT meta_client_name\nFROM libp2p_gossipsub_beacon_block\nWHERE\n  slot_start_date_time >= toDateTime(${__from} / 1000)\n  AND slot_start_date_time <= toDateTime(${__to} / 1000)\n  AND meta_network_name IN (${network_name})\nGROUP BY meta_client_name "
   },
   {
    "name": "geo_continent_code",
    "label": "Continent",
    "query": "SELECT meta_client_geo_continent_code\nFROM libp2p_gossipsub_beacon_block\nWHERE\n  slot_start_date_time >= toDateTime(${__from} / 1000)\n  AND slot_start_date_time <= toDateTime(${__to} / 1000)\n  AND meta_network_name IN (${network_name})\nGROUP BY meta_client_geo_continent_code "
   },
   { "name": "heatmap_interval", "label": "Heatmap interval (MS)", "query": "100,250" },
   { "name": "interval_tight", "query": "12s,60s,384s,3840s,92160s" },
   { "name": "interval", "query": "12s,60s,384s,3840s,92160s" },
   { "name": "interval_loose", "query": "384s,3840s,92160s" },
   { "name": "table_prefix", "label": "Prefix" },
   { "name": "attestation_prefix", "label": "Attestation Prefix" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active sentries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  count(DISTINCT(meta_client_name))\nFROM default.libp2p_gossipsub_beacon_block\nWHERE\n  slot_start_date_time >= toDateTime(${__from:date:seconds})\n  AND slot_start_date_time <= (toDateTime(${__to:date:seconds}) - INTERVAL 1 MINUTE)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\nGROUP BY time\nORDER BY time\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Active Sentries",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n    meta_client_geo_latitude as latitude,\n    meta_client_geo_longitude as longitude,\n    meta_client_geo_city as city,\n    count(DISTINCT meta_client_name) as `count`\n    \nFROM \n    libp2p_gossipsub_beacon_block\nWHERE\n    slot_start_date_time >= now() - toIntervalMinute(2)\n    AND slot_start_date_time <= now() - toIntervalMinute(1)\n    AND meta_client_name IN (${client_name})\n    AND meta_network_name IN (${network_name})\nGROUP BY\n    slot_start_date_time,\n    meta_client_geo_longitude,\n    meta_client_geo_latitude,\n    meta_client_geo_city\nORDER BY slot_start_date_time DESC\nLIMIT 1 by latitude, longitude\n"
    }
   ]
  },
  {
   "title": "Peers sending us blocks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  count(DISTINCT(peer_id_unique_key))\nFROM default.libp2p_gossipsub_beacon_block\nWHERE\n  slot_start_date_time >= toDateTime(${__from:date:seconds})\n  AND slot_start_date_time <= (toDateTime(${__to:date:seconds}) - INTERVAL 1 MINUTE)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\nGROUP BY time\nORDER BY time\nLIMIT 1000"
    }
   ]
  },
  { "title": "Summary per client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Active sentries ${geo_continent_code}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "repeat": "geo_continent_code",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  count(DISTINCT(meta_client_name))\nFROM libp2p_gossipsub_beacon_block\nWHERE\n  slot_start_date_time >= toDateTime(${__from:date:seconds})\n  AND slot_start_date_time <= (toDateTime(${__to:date:seconds}) - INTERVAL 1 MINUTE)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code = '${geo_continent_code}'\nGROUP BY time\nORDER BY time\nLIMIT 1000"
    }
   ]
  },
  { "title": "Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Block arrival time in slot",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  max(propagation_slot_start_diff) max,\n  quantile(0.95)(propagation_slot_start_diff) p95,\n  avg(propagation_slot_start_diff) average,\n  quantile(0.50)(propagation_slot_start_diff) p50,\n  quantile(0.05)(propagation_slot_start_diff) p05,\n  min(propagation_slot_start_diff) min\nFROM default.libp2p_gossipsub_beacon_block FINAL\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND propagation_slot_start_diff < 100000\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\nGROUP BY time\nORDER BY time ASC\nLIMIT 10000"
    }
   ]
  },
  {
   "title": "Block arrival time in slot",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "slot_start_date_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    $timeSeries + 12000 as timestamp,\n    multiply(floor(divide(propagation_slot_start_diff, $heatmap_interval)), $heatmap_interval) as diff,\n    count() as count\nFROM default.libp2p_gossipsub_beacon_block FINAL\nWHERE $timeFilter\n  AND propagation_slot_start_diff < 100000\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\nGROUP BY\n    timestamp,\n    diff",
     "query": "SELECT\n    $timeSeries + 12000 as timestamp,\n    multiply(floor(divide(propagation_slot_start_diff, $heatmap_interval)), $heatmap_interval) as diff,\n    count() as count\nFROM default.libp2p_gossipsub_beacon_block FINAL\nWHERE $timeFilter\n  AND propagation_slot_start_diff < 100000\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\nGROUP BY\n    timestamp,\n    diff",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(slot_start_date_time), 60) * 60) * 1000 + 12000 as timestamp,\n    multiply(floor(divide(propagation_slot_start_diff, 250)), 250) as diff,\n    count() as count\nFROM default.libp2p_gossipsub_beacon_block FINAL\nWHERE slot_start_date_time >= toDateTime(1714092003) AND slot_start_date_time <= toDateTime(1714113603)\n  AND propagation_slot_start_diff < 100000\n  AND meta_client_name IN ('xatu-cl-mimicry-sfo3-holesky-002','xatu-cl-mimicry-syd1-holesky-002','xatu-cl-mimicry-sfo3-holesky-001','xatu-cl-mimicry-syd1-holesky-001')\n  AND meta_network_name IN ('holesky')\nGROUP BY\n    timestamp,\n    diff",
     "round": "0s",
     "table": "libp2p_gossipsub_beacon_block"
    }
   ]
  },
  {
   "title": "Block arrival time spread",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  stddevPop(propagation_slot_start_diff) `std dev population`,\n  quantile(0.90)(propagation_slot_start_diff) - quantile(0.10)(propagation_slot_start_diff) `p90 - p10`\nFROM default.libp2p_gossipsub_beacon_block FINAL\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND propagation_slot_start_diff < 10000\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\nGROUP BY time\nORDER BY time ASC\nLIMIT 10000"
    }
   ]
  },
  {
   "title": "Block arrival time difference between sentries (by consensus client)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  max(diff) max,\n  quantile(0.95)(diff) p95,\n  avg(diff) average,\n  quantile(0.50)(diff) p50,\n  quantile(0.05)(diff) p05,\n  min(diff) min\nFROM (\n    SELECT\n        slot,\n        slot_start_date_time,\n        block,\n        meta_network_name,\n        max(propagation_slot_start_diff) - min(propagation_slot_start_diff) AS diff\n    FROM libp2p_gossipsub_beacon_block FINAL\n    WHERE\n        $__timeFilter(slot_start_date_time)\n        AND meta_network_name IN (${network_name})\n        AND meta_client_geo_continent_code IN (${geo_continent_code})\n    GROUP BY slot, slot_start_date_time, block, meta_network_name\n)\nWHERE\n  diff > 0\n  AND diff < 100000\nGROUP BY time\nORDER BY time ASC\nLIMIT 10000"
    }
   ]
  },
  {
   "title": "Unique Blocks per slot",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT\n  slot_start_date_time,\n  count(DISTINCT(block))\nFROM default.libp2p_gossipsub_beacon_block FINAL\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\nGROUP BY slot_start_date_time\nORDER BY slot_start_date_time ASC\nLIMIT 10000"
    }
   ]
  },
  {
   "title": "Latest epoch",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  max(epoch)\nFROM default.libp2p_gossipsub_beacon_block FINAL\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\nGROUP BY time\nORDER BY time ASC\nLIMIT 10000"
    }
   ]
  },
  {
   "title": "Latest slot",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  max(slot)\nFROM default.libp2p_gossipsub_beacon_block FINAL\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\nGROUP BY time\nORDER BY time ASC\nLIMIT 10000\n"
    }
   ]
  },
  {
   "title": "Blocks per instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  meta_client_name as name,\n  COUNT(block) as count\nFROM default.libp2p_gossipsub_beacon_block FINAL\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\nGROUP BY time, meta_client_name\nORDER BY time ASC\nLIMIT 100000"
    }
   ]
  },
  { "title": "Block size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Block arrival time for block size (compressed, 25KiB buckets)",
   "type": "trend",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "WITH \n    filtered AS (\n        SELECT \n            message_size, \n            floor(message_size / 25600) * 25600 AS bucketed_bytes,\n            propagation_slot_start_diff\n        FROM \n            default.libp2p_gossipsub_beacon_block FINAL\n        WHERE \n            slot_start_date_time >= $__fromTime AND \n            slot_start_date_time <= $__toTime AND\n            propagation_slot_start_diff < 8000 AND\n            meta_client_name IN (${client_name}) AND\n            meta_network_name IN (${network_name}) AND\n            meta_client_geo_continent_code IN (${geo_continent_code})\n    )\nSELECT \n    bucketed_bytes,\n    MAX(propagation_slot_start_diff) AS max,\n    quantile(0.95)(propagation_slot_start_diff) AS p95,\n    AVG(propagation_slot_start_diff) AS avg,\n    quantile(0.50)(propagation_slot_start_diff) AS p50,\n    quantile(0.05)(propagation_slot_start_diff) AS p05,\n    MIN(propagation_slot_start_diff) AS min\nFROM \n    filtered\nGROUP BY \n    bucketed_bytes\nORDER BY \n    bucketed_bytes ASC;\n"
    }
   ]
  },
  {
   "title": "Block propagation for block size (100KiB buckets)",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "WITH \n    filtered AS (\n        SELECT \n            message_size, \n            floor(message_size / 102400) * 102400 AS bucketed_bytes,\n            propagation_slot_start_diff\n        FROM \n            default.libp2p_gossipsub_beacon_block FINAL\n        WHERE \n            slot_start_date_time >= $__fromTime AND \n            slot_start_date_time <= $__toTime AND\n            propagation_slot_start_diff < 8000 AND\n            meta_client_name IN (${client_name}) AND\n            meta_network_name IN (${network_name}) AND\n            meta_client_geo_continent_code IN (${geo_continent_code})\n    )\nSELECT \n    bucketed_bytes,\n    MAX(propagation_slot_start_diff) AS max,\n    quantile(0.95)(propagation_slot_start_diff) AS p95,\n    AVG(propagation_slot_start_diff) AS avg,\n    quantile(0.50)(propagation_slot_start_diff) AS p50,\n    quantile(0.05)(propagation_slot_start_diff) AS p05,\n    MIN(propagation_slot_start_diff) AS min\nFROM \n    filtered\nGROUP BY \n    bucketed_bytes\nORDER BY \n    bucketed_bytes ASC;\n"
    }
   ]
  },
  { "title": "Attestations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Attestation arrival time in slot",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  max(propagation_slot_start_diff) as  max,\n  quantile(0.95)(propagation_slot_start_diff) as  p95,\n  avg(propagation_slot_start_diff) as average,\n  quantile(0.50)(propagation_slot_start_diff) as p50,\n  quantile(0.05)(propagation_slot_start_diff) as p05,\n  min(propagation_slot_start_diff) as min\nFROM default.libp2p_gossipsub_beacon_attestation FINAL\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND (wallclock_slot - slot) < 2\n  AND isNotNull(attesting_validator_index)\n  AND propagation_slot_start_diff < 384000\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\nGROUP BY time\nORDER BY time ASC\nLIMIT 10000"
    }
   ]
  },
  {
   "title": "Attestation seen distance",
   "type": "timeseries",
   "description": "Similar to inclusion distance but instead of when it was included in a block, it's instead when a sentry saw a attestation and the \"distance\" between its target and the current slot. \"0\" being the attestation for the current slot, \"1\" being current slot - 1 etc.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toDateTime(slot_start_date_time) as time,\n  percent\nFROM \n(\n    SELECT\n        slot_start_date_time,\n        interval,\n        round((inclusion_count / interval_total) * 100, 2) AS percent\n    FROM\n    (\n        SELECT\n            slot_start_date_time,\n            interval,\n            inclusion_count,\n            sum(inclusion_count) OVER (PARTITION BY slot_start_date_time) AS interval_total\n        FROM\n        (\n            SELECT\n                slot_start_date_time,\n                floor(divide(propagation_slot_start_diff, 12000)) as interval,\n                count(DISTINCT source_root, target_root, aggregation_bits, beacon_block_root, attesting_validator_index, attesting_validator_committee_index) as inclusion_count\n            FROM default.libp2p_gossipsub_beacon_attestation FINAL\n\n            WHERE\n                $__timeFilter(slot_start_date_time)\n                AND meta_client_name IN (${client_name})\n                AND meta_network_name IN (${network_name})\n                AND meta_client_geo_continent_code IN (${geo_continent_code})\n                AND isNotNull(attesting_validator_index)\n            GROUP BY\n                slot_start_date_time,\n                interval\n            ORDER BY inclusion_count DESC\n        )\n    )\n)\nORDER BY time ASC, percent DESC"
    }
   ]
  },
  {
   "title": "Attestation arrival time in slot",
   "type": "heatmap",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "database": "default",
     "dateTimeColDataType": "slot_start_date_time",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries + 12000 as timestamp,\n    toUInt8(propagation_slot_start_diff / ${heatmap_interval}) * ${heatmap_interval} as diff,\n    sum(toUInt16(1)) as count\nFROM default.libp2p_gossipsub_beacon_attestation FINAL\n\nWHERE $timeFilter\n  AND (wallclock_slot - slot) < 2\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND diff < 30000\n  AND isNotNull(attesting_validator_index)\n\nGROUP BY\n    timestamp,\n    diff\n    \nLIMIT 10000000\n",
     "rawQuery": "SELECT\n    (intDiv(toUInt32(slot_start_date_time), 12) * 12) * 1000 + 12000 as timestamp,\n    toUInt8(propagation_slot_start_diff / 250) * 250 as diff,\n    sum(toUInt16(1)) as count\nFROM default.libp2p_gossipsub_beacon_attestation FINAL\n\nWHERE slot_start_date_time >= toDateTime(1714369860) AND slot_start_date_time <= toDateTime(1714373460)\n  AND (wallclock_slot - slot) < 2\n  AND meta_client_name IN ('example-instance')\n  AND meta_network_name IN ('mainnet')\n  AND meta_client_geo_continent_code IN ('')\n  AND diff < 30000\n  AND isNotNull(attesting_validator_index)\n\nGROUP BY\n    timestamp,\n    diff\n    \nLIMIT 10000000",
     "round": "12s",
     "table": "libp2p_gossipsub_beacon_attestation"
    }
   ]
  },
  {
   "title": "Attestation agreement",
   "type": "timeseries",
   "description": "For a given slot, what beacon block roots had attestations against them",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  toDateTime(slot_start_date_time) as time,\n  percent\nFROM \n(\n  SELECT\n      slot_start_date_time,\n      beacon_block_root,\n      round((attestation_count / beacon_block_root_total) * 100, 2) AS percent\n  FROM\n  (\n      SELECT\n          slot_start_date_time,\n          beacon_block_root,\n          attestation_count,\n          sum(attestation_count) OVER (PARTITION BY slot_start_date_time) AS beacon_block_root_total\n      FROM\n      (\n          SELECT\n              slot_start_date_time,\n              beacon_block_root,\n              sum(toUInt32(1)) AS attestation_count\n          FROM default.libp2p_gossipsub_beacon_attestation FINAL\n          WHERE\n              $__timeFilter(slot_start_date_time)\n              AND meta_client_name IN (${client_name})\n              AND meta_network_name IN (${network_name})\n              AND meta_client_geo_continent_code IN (${geo_continent_code})\n              AND isNotNull(attesting_validator_index)\n          GROUP BY\n              slot_start_date_time,\n              beacon_block_root\n          ORDER BY attestation_count DESC\n      )\n  )\n)\nORDER BY time ASC, percent DESC"
    }
   ]
  },
  {
   "title": "Attestation arrival time spread",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  stddevPop(propagation_slot_start_diff) `std dev population`,\n  quantile(0.90)(propagation_slot_start_diff) - quantile(0.10)(propagation_slot_start_diff) `p90 - p10`\nFROM default.libp2p_gossipsub_beacon_attestation FINAL\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND (wallclock_slot - slot) < 2\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\n  AND isNotNull(attesting_validator_index)\n  AND propagation_slot_start_diff < 384000\nGROUP BY time\nORDER BY time ASC\nLIMIT 10000"
    }
   ]
  },
  {
   "title": "Attestation propagation difference between instances",
   "type": "timeseries",
   "description": "The difference between when an attestation is seen by the first and last instance",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  max(diff) max,\n  quantile(0.95)(diff) p95,\n  avg(diff) average,\n  quantile(0.50)(diff) p50,\n  quantile(0.05)(diff) p05,\n  min(diff) min\nFROM (\n    SELECT\n        slot,\n        slot_start_date_time,\n        aggregation_bits,\n        committee_index,\n        meta_network_name,\n        max(propagation_slot_start_diff) - min(propagation_slot_start_diff) AS diff,\n        COUNT(*) as count\n    FROM default.libp2p_gossipsub_beacon_attestation FINAL\n    WHERE\n        $__timeFilter(slot_start_date_time)\n        AND slot_start_date_time <= toDateTime(${__to:date:seconds})\n        AND meta_network_name IN (${network_name})\n        AND meta_client_geo_continent_code IN (${geo_continent_code})\n        AND isNotNull(attesting_validator_index)\n    GROUP BY slot, slot_start_date_time, aggregation_bits, committee_index, meta_network_name\n    HAVING diff > 0 AND diff < 30000 AND count > 1\n)\nGROUP BY time\nORDER BY time ASC\nLIMIT 100000\n"
    }
   ]
  },
  {
   "title": "Attestations per instance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 133 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  meta_client_name as name,\n  COUNT(*) as count\nFROM\n  default.libp2p_gossipsub_beacon_attestation FINAL\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\nGROUP BY\n  meta_client_name, time\nORDER BY\n  meta_client_name, time\n"
    }
   ]
  },
  {
   "title": "Attestations per subnet",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 0, "y": 144 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  topic_name,\n  COUNT(*) as count\nFROM\n  default.libp2p_gossipsub_beacon_attestation FINAL\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\nGROUP BY\n  topic_name, time\nORDER BY\n  topic_name, time\n"
    }
   ]
  },
  {
   "title": "Unique block roots per slot",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 144 },
   "targets": [
    {
     "rawSql": "SELECT\n  slot_start_date_time,\n  count(DISTINCT(beacon_block_root))\nFROM default.libp2p_gossipsub_beacon_attestation FINAL\nWHERE\n  $__timeFilter(slot_start_date_time)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\n  AND meta_client_geo_continent_code IN (${geo_continent_code})\nGROUP BY slot_start_date_time\nORDER BY slot_start_date_time ASC\nLIMIT 10000"
    }
   ]
  }
 ]
}