{
 "title": "MEV Relays",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "network_name",
    "label": "Network",
    "query": "SELECT meta_network_name\nFROM mev_relay_bid_trace\nWHERE\n  slot_start_date_time >= toDateTime(${__from} / 1000)\n  AND slot_start_date_time <= toDateTime(${__to} / 1000)\nGROUP BY meta_network_name "
   },
   {
    "name": "client_name",
    "label": "Instance",
    "query": "SELECT meta_client_name\nFROM mev_relay_bid_trace\nWHERE\n  slot_start_date_time >= toDateTime(${__from} / 1000)\n  AND slot_start_date_time <= toDateTime(${__to} / 1000)\n  AND meta_network_name IN (${network_name})\nGROUP BY meta_client_name "
   },
   {
    "name": "geo_continent_code",
    "label": "Continent",
    "query": "SELECT meta_client_geo_continent_code\nFROM libp2p_gossipsub_beacon_block\nWHERE\n  slot_start_date_time >= toDateTime(${__from} / 1000)\n  AND slot_start_date_time <= toDateTime(${__to} / 1000)\n  AND meta_network_name IN (${network_name})\nGROUP BY meta_client_geo_continent_code "
   },
   { "name": "heatmap_interval", "label": "Heatmap interval (MS)", "query": "100,250" },
   { "name": "interval_tight", "query": "12s,60s,384s,3840s,92160s" },
   { "name": "interval", "query": "12s,60s,384s,3840s,92160s" },
   { "name": "interval_loose", "query": "384s,3840s,92160s" },
   { "name": "table_prefix", "label": "Prefix" },
   { "name": "attestation_prefix", "label": "Attestation Prefix" },
   {
    "name": "relay",
    "label": "Relay",
    "query": "SELECT relay_name\nFROM mev_relay_bid_trace\nWHERE\n  slot_start_date_time >= toDateTime(${__from} / 1000)\n  AND slot_start_date_time <= toDateTime(${__to} / 1000)\n  AND meta_network_name IN (${network_name})\nGROUP BY relay_name "
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeInterval(slot_start_date_time) as time,\n  count(DISTINCT(meta_client_name))\nFROM default.mev_relay_bid_trace\nWHERE\n  slot_start_date_time >= toDateTime(${__from:date:seconds})\n  AND slot_start_date_time <= (toDateTime(${__to:date:seconds}) - INTERVAL 1 MINUTE)\n  AND meta_client_name IN (${client_name})\n  AND meta_network_name IN (${network_name})\nGROUP BY time\nORDER BY time\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "Active Relay Monitors",
   "type": "geomap",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n    meta_client_geo_latitude as latitude,\n    meta_client_geo_longitude as longitude,\n    meta_client_geo_city as city,\n    count(DISTINCT meta_client_name) as `count`\n    \nFROM \n    mev_relay_bid_trace\nWHERE\n    slot_start_date_time >= now() - toIntervalMinute(2)\n    AND slot_start_date_time <= now() - toIntervalMinute(1)\n    AND meta_client_name IN (${client_name})\n    AND meta_network_name IN (${network_name})\nGROUP BY\n    slot_start_date_time,\n    meta_client_geo_longitude,\n    meta_client_geo_latitude,\n    meta_client_geo_city\nORDER BY slot_start_date_time DESC\nLIMIT 1 by latitude, longitude\n"
    }
   ]
  },
  { "title": "Block bids", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total unique bids",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n    slot_start_date_time,\n    uniqExact(unique_key) AS unique_bid_count\nFROM\n    default.mev_relay_bid_trace\nWHERE\n    $__timeFilter(slot_start_date_time)\n    AND meta_client_name IN (${client_name})\n    AND meta_network_name IN (${network_name})\n    AND relay_name IN (${relay})\nGROUP BY\n    slot_start_date_time\nORDER BY\n    slot_start_date_time ASC\n"
    }
   ]
  },
  {
   "title": "Total bids per relay",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bids" } },
   "targets": [
    {
     "rawSql": "SELECT\n    slot_start_date_time as \"time\",\n    relay_name,\n    uniqExact(unique_key) AS \"unique_bid_count\"\nFROM\n    default.mev_relay_bid_trace\nWHERE\n    $__timeFilter(slot_start_date_time)\n    AND meta_client_name IN (${client_name})\n    AND meta_network_name IN (${network_name})\n    AND relay_name IN (${relay})\nGROUP BY\n    slot_start_date_time,\n    relay_name\nORDER BY\n    slot_start_date_time ASC\n"
    }
   ]
  },
  {
   "title": "Max bid per relay",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "targets": [
    {
     "rawSql": "SELECT\n    slot_start_date_time AS \"time\",\n    relay_name,\n    MAX(toFloat64(value) / 1e18) AS max_value_eth\nFROM\n    default.mev_relay_bid_trace\nWHERE\n    $__timeFilter(slot_start_date_time)\n    AND meta_client_name IN (${client_name})\n    AND meta_network_name IN (${network_name})\n    AND relay_name IN (${relay})\nGROUP BY\n    slot_start_date_time,\n    relay_name\nORDER BY\n    slot_start_date_time ASC"
    }
   ]
  }
 ]
}