name: Claude PR Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-code-action:
    if: |
      (
        (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
        (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
        (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
        (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
      ) && (
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'COLLABORATOR' ||
        github.event.issue.author_association == 'OWNER' ||
        github.event.issue.author_association == 'MEMBER' ||
        github.event.issue.author_association == 'COLLABORATOR' ||
        github.event.review.author_association == 'OWNER' ||
        github.event.review.author_association == 'MEMBER' ||
        github.event.review.author_association == 'COLLABORATOR'
      )
    runs-on:
      - self-hosted-ghr
      - size-m-x64
    permissions:
      contents: write
      pull-requests: write
      issues: write
      actions: read
      checks: read
      repository-projects: read
      statuses: read
      id-token: write
    steps:
      - name: Run Claude PR Assistant
        uses: ethpandaops/.github/actions/claude-pr-assistant@master
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          # Optional overrides:
          # timeout_minutes: "90"
          # node_version: "22"
          # custom_instructions: |
          #   Additional custom instructions for this repository
          # allowed_tools: |
          #   Custom tool allowlist for this repository
